### ISSUE TITLE
Division by zero with only a single song

### ISSUE THREAD

**Issue by ExtremeMakerX** [OpenLoco/OpenLoco#1005]
**Version information:**
 - Platform: [e.g. Windows 10 64bit]
 - Versions: [21.05, older versions even 2019 but the 2018 version works fine]

**Describe the bug**
It's the Music Game Crashing Method that I did that makes it exit itself.
It doesn't show any error message even when I try running it with a command prompt.

**To Reproduce**
1 select only one soundtrack that is not a part of an era on the map
2 choose play customized selection of music 
3 when the music ends it exits itself
(I call it Music Game Crashing Method).

**Expected behaviour**
I expected that it closes itself when the music ends and then no error message by doing the Music Game Crashing Method. 
 
**Screenshots**
![Music Game Crashing Method](https://user-images.githubusercontent.com/79700465/122309756-dcf36e00-cedc-11eb-8e97-104607fc76dd.PNG)
![Opening Openloco Directly](https://user-images.githubusercontent.com/79700465/122310007-6a36c280-cedd-11eb-9b1e-e9fc972f1343.PNG)
![Opening it with cmd](https://user-images.githubusercontent.com/79700465/122310016-6dca4980-cedd-11eb-966c-5db81954f04e.PNG)

**Comment by janisozaur** [comment]
@ExtremeMakerX nice figuring out it's tied to music!

Division by zero in https://github.com/OpenLoco/OpenLoco/blob/475e9075b9b7750bf46cfe3ef61515d811a5844a/src/OpenLoco/Audio/Audio.cpp#L1077
