### ISSUE TITLE
Refactor Widget draw member functions

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenLoco/OpenLoco#1010]
As i didn't want to make a big refactor any bigger i never got around to turning the Widget::draw functions into normal member functions. Should be a simple task of removing the `static` and `widget` parts of the function and removing the `widget->` from the function body. 
https://github.com/OpenLoco/OpenLoco/blob/bfd99e849d231f25cb3a93992ac34f4f070efa8f/src/OpenLoco/Widget.h#L38-L67

**Comment by Truenya** [comment]
@duncanspumpkin Hello!
Got it!
PR #1012
https://github.com/OpenLoco/OpenLoco/pull/1012

**Comment by Truenya** [comment]
@duncanspumpkin Hello!
Now all requirements are satisfied
