### ISSUE TITLE
Create a Save Game Compare command line tool

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenLoco/OpenLoco#1013]
We have the ability to load s5 files with `std::unique_ptr<S5File> load(const fs::path& path)` and it would be very useful to be able to compare two files when working on vehicle functions. Therefore we should make a simple commandline tool to do that. This can be split into two main tasks:

- [ ] Handle command line arguments. We do not currently process the command line. This will need to be implemented/use a lib.
- [ ] Create an S5File compare function that can output useful comparison information to the console or to a file.

**Comment by AaronVanGeffen** [comment]
Perhaps we could go so far as to do chunk-based comparison. It would help to know what chunks/sections are different (e.g. tile elements, companies, stations).

**Comment by duncanspumpkin** [comment]
Well once you have the S5File its already broken into its constituent parts.

**Comment by AaronVanGeffen** [comment]
Yeah, that's what I was thinking as well. I was just adding that I'd like to see it in the diff report as well.

**Comment by duncanspumpkin** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/cmdline/CommandLine.hpp this is what is used for OpenRCT2. Suggest it is copied.

**Comment by AaronVanGeffen** [comment]
A command line tool to run simulations for a certain number of ticks has since been implemented. This should help make it easier to implement a comparison tool.

**Comment by memellis** [comment]
Hi 
I thought I would have a go at implementing:
- [ ] Create an S5File compare function that can output useful comparison information to the console or to a file. 
- [ ] Put the compare function in S5 namespace?
- [ ] Add a compare [options] <save file1> <save file> command line option in CommandLine.cpp
Any other thoughts, advice?

**Comment by LeftofZen** [comment]
Just have a check with @duncanspumpkin and @AaronVanGeffen about exactly what they want here, as we already have a simulation tool to check for similar things like this.

**Comment by memellis** [comment]
@AaronVanGeffen thanks for the latest thinking on this. Here are some questions:
- Is the optional reference file just another S5 save file?
-  



Very happy to wait for @duncanspumpkin reply.

> Just have a check with @duncanspumpkin and @AaronVanGeffen about exactly what they want here, as we already have a simulation tool to check for similar things like this.

Hi @LeftofZen will do!

**Comment by duncanspumpkin** [comment]
Yes pretty much same as what aaron said. We have two game state structures the s5 one that doesn't have type info (it's all just uintx) and the main one. Eventually they won't be the same though. `S5File` is actually a bit more than just the game state as it also has the tile elements and objects. For the first version just knowing the offset of the difference in the struct is all we need.

For example if we had two files and the only difference was entity 5 with a difference at offset 0xC. I would like it to print:
```
DIVERGENCE
ENTITY: 5
  OFFSET: 0xC
    LHS: 0xAA
    RHS: 0xAB
```

Thinking about it more entities and tile elements you will pretty much always also want to know the type as well.

**Comment by memellis** [comment]
Ok, thanks for the steer I'll have a go at what has been suggested.
