### ISSUE TITLE
Re-introduce progress bars for loading and saving

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenLoco/OpenLoco#1014]
The original game shows progress bars while a save game or scenario is being loaded or saved. Our own implementations currently do not show such progress bars.

Perhaps we can tap into the SawyerStreamReader and SawyerStreamWriter classes to show these progress bars?

**Comment by IntelOrca** [comment]
The decoding of the streams will be too quick for a progress bar. The time taken will be object loading which is a loop you can easily add a progress bar to.

**Comment by AaronVanGeffen** [comment]
You're probably right… It's always surprising to me how slow loading is in vanilla for me — OpenLoco is at least an order of magnitude faster. I can imagine extracting any packed objects would be relatively slow still, though, particularly on HDDs.

**Comment by duncanspumpkin** [comment]
I'm not sure it will be very easy to do the progress bar code is a bit messy and doesn't work how I'd like it to work. I think it might be better to leave this for now.

**Comment by memellis** [comment]
@duncanspumpkin OK I have a look at what I can work on. Any suggestions?
