### ISSUE TITLE
Create an ImageId Struct

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenLoco/OpenLoco#1019]
The way images are used in Locomotion (and all CS games) is that you have a uint32_t that has an image index for the first 0x7FFFF bits then you have a primary colour at offset 19 followed by a secondary colour at offset 24 and finally flags at offsets 29, 30, 31. Primary colours can be either 0x1F or 0xFF in size depending on the flags. If we ever want to increase the range of the images (or colours) we will need to use something else for this structure.

OpenRCT2 has started doing this by using the ImageId struct:

https://github.com/OpenRCT2/OpenRCT2/blob/d635345841d98a7c3b1bc7712c9b3fd13785d5d1/src/openrct2/drawing/Drawing.h#L331-L501.

I suggest this is pretty much copied whole as it pretty much follows everything we require. The one issue with the OpenRCT2 struct is that it also has the tertiary colour saved. Tertiary colour is normally passed into functions on a separate register and due to not owning all memory in OpenLoco we will need to either not support tertiary colour in the image id struct or we will need to not use the struct in Loco memory. 

By using this struct we will have much simpler ways of access the raw image id and raw colours as well as making it easy to recolour images. A search of the codebase for 0x7FFFF shows we have used that constant 3 times so far. << 19 has been used ~15 times but we have the Gfx::recolour function which normally handles it. The Gfx::recolour functions would be moved into the ImageId struct.

**Comment by AaronVanGeffen** [comment]
Has since been implemented
