### ISSUE TITLE
Excessive CPU usage with "Load Game" window opened

### ISSUE THREAD

**Issue by janisozaur** [OpenLoco/OpenLoco#1021]
**Version information:**
 - Platform: Ubuntu 20.04
 - Version: 21.05
 - Build/commit: 7bdc32d (current master)

**Describe the bug**
The CPU usage spikes when "Load Game" window is opened from the title menu

**Comment by AaronVanGeffen** [comment]
For me, the title screen itself makes OpenLoco consume 15% CPU. The load screen increases that to 17~21%. Not great, but nothing too extreme either. Is this different for you?

**Comment by janisozaur** [comment]
Yes, it's quite different. 65% when simply sitting on title screen, 100% when the "Load Game" window gets opened. Same behaviour when testing with v21.05 release binary with wine. In both cases FPS was capped.
