### ISSUE TITLE
[Readme] update the links present in the readme

### ISSUE THREAD

**Issue by aaroosh-07** [OpenLoco/OpenLoco#1045]
Links present in the readme of the project are broken. they need to be updated for the new links.

**Comment by aaroosh-07** [comment]
can I resolve this issue?

**Comment by AaronVanGeffen** [comment]
What links are you talking about?

**Comment by aaroosh-07** [comment]
Building the game
license
more information

**Comment by aaroosh-07** [comment]
and we can add a link for contribution

**Comment by AaronVanGeffen** [comment]
Haha, no, nice try.

**Comment by aaroosh-07** [comment]
If you click on those links they are not working properly
