### ISSUE TITLE
OpenLoco doesn't work because my (local) account name has a special character in it.

### ISSUE THREAD

**Issue by MadeInDutch** [OpenLoco/OpenLoco#1048]
**Version information:**
 - Windows 10 (64-bit)
 - Version: 21.05
 - Build/commit: e6e665a

**Bug description**
If I try to launch OpenLoco (whether through the desktop shortcut or through the original file location), it will crash in a second. This happens on my laptop's main account (whose user folder has a Turkish ş, and an account name with the Romanian ș), but not on a test account I made with an s instead of these special characters. No surprises here, it worked. I've had this same issue on a range of programs, from game launchers to setup programs, which is why I made that test account in the first place. I bloody hope this issue is fixable (and fixed within the next version) because I really wanna get into Locomotion.

**To Reproduce**
Steps to reproduce the behaviour:
1. Make a local Windows account with a special character.
2. Install Locomotion and OpenLoco
3. Try to launch OpenLoco
4. See the error

**Expected behaviour**
I expected the game to load in the same way OpenRCT2 or CorsixTH do.

**Additional context**
Please remember, this happened on a local Windows account, not a Microsoft account. And I also only run into this issue with my account name on my new laptop. Programs that worked on my old laptop do not work on my new laptop despite my account name being the exact same on both machines (although on this new machine the name of the Users folder uses a Turkish ş instead of a Romanian ș, which might be causing all of the problems in the first place). I don't know if this is an issue with said programs or an issue with Windows 10 (probably both, let's be honest).

Thank you.

**Comment by AaronVanGeffen** [comment]
Thanks for the report. We've had some people report similar issues in the past, but most of them (save for #913) ought to have been fixed in v21.05.

**Comment by MadeInDutch** [comment]
I see. When can we (roughly) expect version 21.07?

**Comment by AaronVanGeffen** [comment]
Our version scheme uses the year of release for the major version and the month for the minor number. So 21.07 would be July 2021 — sometime this month.

**Comment by MadeInDutch** [comment]
Unfortunately, the new version hasn't fixed things for me. It just seems to refuse to load.

**Comment by AaronVanGeffen** [comment]
We were unable to address this for v21.07, unfortunately.  I do consider it a priority to fix, however.

**Comment by MadeInDutch** [comment]
I see

**Comment by duncanspumpkin** [comment]
Could you try https://github.com/OpenLoco/OpenLoco/pull/1057

**Comment by MadeInDutch** [comment]
How do I install this patch?

**Comment by duncanspumpkin** [comment]
https://github.com/OpenLoco/OpenLoco/suites/3266491319/artifacts/76038498 is a link to its build artifact. just unzip to use this version.

**Comment by MadeInDutch** [comment]
Yeah it still doesn't work...

**Comment by duncanspumpkin** [comment]
:( thats a pity was really confident on this one will keep searching.

Did it provide any warnings in the console?

**Comment by MadeInDutch** [comment]
Nope. It appears blank for a second, then it just closes.

**Comment by AaronVanGeffen** [comment]
Could you open the game from a Windows console (cmd)? There might be an error message in the console that's disappearing.

**Comment by MadeInDutch** [comment]
How do I do that?

**Comment by AaronVanGeffen** [comment]
[This article](https://www.howtogeek.com/235101/10-ways-to-open-the-command-prompt-in-windows-10/) contains several ways to open a command prompt in Windows.

In a command prompt, type `cd \path\to\where\you\installed\openloco`, then press enter. There, to launch OpenLoco, type `openloco`, and press enter.

This assumes you've installed OpenLoco on the same drive as your Windows install. If this isn't the case, your first step would be to change drives, e.g. type `D:` followed by enter.

**Comment by MadeInDutch** [comment]
![resim](https://user-images.githubusercontent.com/67276601/126064379-b92c2143-b8a2-4f73-afb0-6d12dc402205.png)
Welp

**Comment by AaronVanGeffen** [comment]
Could you share a screenshot of the contents of that directory?

**Comment by MadeInDutch** [comment]
how?

**Comment by AaronVanGeffen** [comment]
Any way will do. Just take a screenshot from Explorer ('normal' desktop folder view) if it's easier.

**Comment by MadeInDutch** [comment]
![resim](https://user-images.githubusercontent.com/67276601/126064509-226c561a-7725-4f5e-af87-f649fa27ed32.png)

**Comment by AaronVanGeffen** [comment]
Hmm, that does look complete. I'm afraid I'm out of ideas. Perhaps @duncanspumpkin has an idea why it's not giving any output. (I'm not on Windows, so I can't easily check.)

**Comment by duncanspumpkin** [comment]
Could you try this version think ive fixed it https://github.com/OpenLoco/OpenLoco/suites/3268437797/artifacts/76090806

**Comment by MadeInDutch** [comment]
I FINALLY FIGURED OUT THE PROBLEM.

The user folder corresponding to my local account had a special character (which I mentioned before). I managed to change the name without losing any data, and as such OpenLoco works great for me now. Thank you for the support!

**Comment by duncanspumpkin** [comment]
I'd still like to have it working anyway so I'll keep the issue open

**Comment by duncanspumpkin** [comment]
After further testing #1057 you can have local accounts with non-ASCII characters for loading but for saving it still jumps into too many original functions that can't handle non-ASCII characters. You get quite a weird experience when using non-ASCII characters as it wants to rebuild a lot of the files every load but after that fails to save it loads up correctly.

**Comment by MadeInDutch** [comment]
Well I'd always had issues with a couple of games because my user folder had a non ASCII character. Aside from OpenLoco not working, I had the installers for a lot of programs not working, Minecraft crashed all the time, I couldn't save in RCT Classic, I couldn't save on RCT3 and CorsixTH without running as admin, etc. It messes a lot with your programs.
