### ISSUE TITLE
Placing stations causes game to crash

### ISSUE THREAD

**Issue by NSTrains** [OpenLoco/OpenLoco#1058]
- Platform: Windows 10 21h1
 - Game Version: 21.07
 

In a save game, placing a station causes the game to crash

To reproduce:
1. Open a save game
2. Right click the railroad track
3. Go to the station tab and try to place a station
4. The game should crash (for me it does)

**Comment by duncanspumpkin** [comment]
Can you test if it also crashes if you do it the other way round select track from the main menu then go to the station tab.

**Comment by NSTrains** [comment]
It crashes both ways only on one save game

**Comment by AaronVanGeffen** [comment]
Could you attach the save game in question? (GitHub will let you if you zip it.)

**Comment by NSTrains** [comment]
[Altoona.zip](https://github.com/OpenLoco/OpenLoco/files/6837473/Altoona.zip)
Here is the save game

**Comment by duncanspumpkin** [comment]
This was probably #1070 causing the crash.

**Comment by LeftofZen** [comment]
On 22.02 this just hard-crashes immediately on loading the save in https://github.com/OpenLoco/OpenLoco/blob/master/src/OpenLoco/Vehicles/Vehicle.cpp#L178

**Comment by LeftofZen** [comment]
In vanilla it doesn't load the save since it's missing an object:
![image](https://user-images.githubusercontent.com/7483209/153971370-122f2990-11c1-492c-addb-662cac2c4365.png)

So I wonder why OpenLoco tries to load the save if it's missing an object...

**Comment by LeftofZen** [comment]
#1328 fixes my hard-crash related to this issue and I get the correct 'missing object data' message. @NSTrains, can you upload this custom object, or PM it to me on discord?

**Comment by LeftofZen** [comment]
I've managed to get the objects needed and I can get the save to load, and I can place stations normally with no problems. It IS glitchy in the sense that I can't seem to place any of the custom stations or signals, I can only place vanilla  stations and signals, but that does work.

**Comment by AaronVanGeffen** [comment]
Presumably fixed?
