### ISSUE TITLE
Unable to place signal properly

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenLoco/OpenLoco#1099]
**Version information:**
 - Platform: Linux
 - Version: 21.07+
 - Build/commit: ae294ad80e92e7fdd604e2f33f29c6e88d509363

The signal ghost appears fine, but clicking it leads to the signal being built incorrectly.

Over track with ghost:
![Screenshot](https://user-images.githubusercontent.com/604665/128932553-f9e46dbf-7351-41fa-932f-93a7e24fa1e6.png)

Placing down in same position:
![Screenshot_1](https://user-images.githubusercontent.com/604665/128932555-0f31e98c-a59a-4676-b66d-14d43a416367.png)

**Comment by duncanspumpkin** [comment]
by built incorrectly do you just mean back to front?

**Comment by AaronVanGeffen** [comment]
Yes, it is facing the wrong direction.
