### ISSUE TITLE
Right clicking on a road I've built either makes the game crash or causes the road price to go crazy

### ISSUE THREAD

**Issue by Slax2317** [OpenLoco/OpenLoco#1123]
**Version information**
 - Platform: Windows 10 Pro 21H1
 - Version: 21.08
 - Build/commit: 7aecfa5

**Describe the bug**
Game crashes when clicking with the right mouse button on a road I've built (doesn't seem to work with already-present roads)

**To Reproduce**
- Start or load any map
- Build a road, even just one square
- Right click on it
- Game crashes or price skyrockets

This is a dmp files that the game generates when I right click on a road I've built and the game crashes: https://github.com/OpenLoco/OpenLoco/files/7028080/2690d0ee-dc7c-469e-9b78-8c42760bfd98.OpenLoco.v21.08.7aecfa5.dmp.zip

**Screenshot**
This is when i right click on a road and the price increases a lot, or sometimes it even goes negative (nice trick to get some free cash lol)
![image](https://user-images.githubusercontent.com/82705614/130369077-15ab0648-df82-46ef-b12e-631a9ef3e55f.png)
![image](https://user-images.githubusercontent.com/82705614/130369210-884a5313-c16e-41d3-b7d8-33c1d0d3c370.png)

Thank you in advance

**Comment by duncanspumpkin** [comment]
Crashes in a paint function that hasn't been implemented.
