### ISSUE TITLE
Remove dangerous constructor

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenLoco/OpenLoco#1172]
https://github.com/OpenLoco/OpenLoco/blob/master/src/OpenLoco/Math/Vector.hpp#L146

This constructor can be dangerous to use it will zero out the z coordinate which is perhaps not what the user expects. There is currently only one user of this (after https://github.com/OpenLoco/OpenLoco/pull/1171) and that user is using it correctly. It would mean that assigning a Vec3 from a Vec2 needs to be done explicitly which i think is sensible

**Comment by ZehMatt** [comment]
You mean removing the Vec2 version? I'm not sure what one should fix.
