### ISSUE TITLE
Separate road and tracks visibility toggle.

### ISSUE THREAD

**Issue by dansq** [OpenLoco/OpenLoco#1180]
**Describe the solution you'd like**
It would be nice to have a separate toggle for railroad tracks visibility and roads visibility.

**Describe alternatives you've considered**
Sometimes rotating and moving the camera around helps but does not solve the issue when there are roads and tracks close together at different height levels.

**Additional context**
Currently railroad tracks and roads hidden/visible toggle applies to both types at the same time, this makes creating dense networks a bit tricky sometimes.

**Screenshot 1: visibility on**
![tracks_on](https://user-images.githubusercontent.com/14081061/133934562-93ca87c7-27ac-49ac-802e-c0f18267130e.png)
**Screenshot 2: visibility off**
![tracks_off](https://user-images.githubusercontent.com/14081061/133934563-5632cdf9-8927-44cf-8276-0c36c597990a.png)

**Comment by AaronVanGeffen** [comment]
Completely agree. This has annoyed me in the past as well. 

I'd also like to introduce a station visibility toggle, separating it from the building/scenery toggle.
