### ISSUE TITLE
ios_base::failbit set: iostream stream error still present in current build avaliable from github repository

### ISSUE THREAD

**Issue by Robert-J-Powell** [OpenLoco/OpenLoco#1204]
**Version information:**
 - Platform: Windows 10 Pro 21H1
 - Version: 21.09-8
 - Build/commit: 26d40d5

**Describe the bug**
ios_base::failbit set: iostream stream error

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Open Locomotion directory'
2. Click on 'openloco.exe'
3. boot process for game begins

**Expected behaviour**
Expected openloco to load the files from my locomtoiton directory and then boot the game

**Screenshots**
![iostream](https://user-images.githubusercontent.com/92318384/136806756-efd3d9f9-9ce2-442f-9294-8ea8fa000136.png)
.

**Additional context**
Downloaded latest client from the github repository as a zip file, unzipped files to my gaming drive under  (D:\OLoco) and ran the file, pointed it to my locomotion directory (D:\GOG Galaxy\Games\Locomotion) and got the error.

**Comment by duncanspumpkin** [comment]
Resolved on master. We will do another release sometime soon as well to fix this for release builds.
