### ISSUE TITLE
Pressing 'Z' to rotate objects rarely works as intended.

### ISSUE THREAD

**Issue by Derpercoaster** [OpenLoco/OpenLoco#1207]
Platform: Windows 10
Version: V20.10
Build/commit: (ee516cf)

Simply put, pressing the 'Z' button to rotate an object does not work consistently. In fact, it hardly works at all.

Steps to reproduce the behaviour:
1. Open the building menu for anything (road, track, building etc). do not place it.
2. Press 'Z' (rotation key) to rotate it.
3. The result will likely be nothing.

Expected behaviour
I expect it to rotate the held object every time 'z' is pressed.

Other Notes: Rotating vehicles seems to work correctly, but nothing else responds correctly.

**Comment by AaronVanGeffen** [comment]
The About window reflects the original version of Locomotion. OpenLoco's version number is presented in the lower left corner of the title screen. 

I have no problems rotating elements on v21.09+, for what it's worth.

**Comment by Derpercoaster** [comment]
Ah, that makes sense. Thanks. I suppose I should update then. I think this can be closed now.
