### ISSUE TITLE
Game Crash When Attempting to Save a Custom Scenario Using the "Improved" Terrain Option.

### ISSUE THREAD

**Issue by Derpercoaster** [OpenLoco/OpenLoco#1218]
Platform Windows 10
Version: 21.09-8
Build: 26d40d5

Bug:

Title explains everything. The game crashes when yo attempt to save a custom scenario that uses the "improved" terrain style instead of the original.

To Reproduce:

Steps to reproduce the behaviour:
1. Open scenario editor
2. Make your way to the generation option window
3. Set terrain style to "improved"
4. Attempt to either save the scenario as a playable map (may require completing scenario editor steps) or as a landscape
5. Game will freeze and crash
**Expected behaviour**
The game should save the landscape/scenario properly when prompted.

**Comment by AaronVanGeffen** [comment]
The crash happens regardless of whether the scenario is using the 'improved' terrain generator or not.

I think this is the result of #1122, which I wrote thinking #781 had already been merged. I'll work on a fix.
