### ISSUE TITLE
Competing Companies' Stations and Vehicles can be Viewed by the Player

### ISSUE THREAD

**Issue by Derpercoaster** [OpenLoco/OpenLoco#1221]
Simply put, having an option to select which company's stations and vehicles are displayed in their respective windows. Imagine a dropdown menu with every company in it on each of the aformentioned windows. When you select a different company, the stations/vehicles displayed in the in-game windows would be that company's instead of your own. This would allow you to easily find assets owned by other companies without having to scour the map for them yourself.

**Comment by duncanspumpkin** [comment]
I am not sure what you mean. Could you draw some images of what you expect.

**Comment by AaronVanGeffen** [comment]
Currently, you can already switch companies in these listing windows. Just use the company selection dropdown in the top-right corner. Is that what you meant?
