### ISSUE TITLE
Cheat for Vehicle Reliability Broken on Mulitple Locomotives

### ISSUE THREAD

**Issue by jmz1115** [OpenLoco/OpenLoco#1229]
**Version information:**
 - Platform: Win 10
 - Version: 21.10
 - Build/commit: 3bec790

**Describe the bug**
On trains with multiple power sources, the cheat for "set reliability to 100" and "set reliability to 0" do not stay permanently. They briefly change and then change back to their original value.

**To Reproduce**
Steps to reproduce the behaviour:
1. Build a train with 2 engines (number of cars does not matter)
2. use the cheat "set reliability to 100" or "set reliability to 0"
3. If observing the list of your trains, notice that all units change to 100 or 0, but after a brief delay (1 second or so) the train you just created will switch reliability back to the original value

**Expected behaviour**
Reliability remains permanently at whichever value selected

**Additional context**
It appears that the cheat only changes the value of the first engine that it encounters, but not the second. So the average value is impacted, but if you go to the individual train set, the first engine stays with whatever the cheat set it at.

**Comment by duncanspumpkin** [comment]
https://github.com/OpenLoco/OpenLoco/blob/aa1c6bf2bd530de26a1095f058c2b0fa53b49a79/src/OpenLoco/GameCommands/Cheat.cpp#L168

This should have been setting the reliability of each cars first bogie not just the first bogie.
