### ISSUE TITLE
Wrong vehicle capacity in Build window

### ISSUE THREAD

**Issue by pparik** [OpenLoco/OpenLoco#1236]
**Version information:**
 - Platform: Fedora 33
 - Version: 21.10

**Describe the bug**
A wrong capacity is shown in the Build window for any type of transport.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Build Trains/Buses/... window
2. Click on a vehicle that has some cargo capacity

**Expected behaviour**
The correct capacity is shown.

**Screenshots**

![Screenshot1](https://user-images.githubusercontent.com/26385735/139294536-f15869bb-9478-4c56-a9e0-73ae1d2e0c7b.png)
![Screenshot2](https://user-images.githubusercontent.com/26385735/139294540-61555411-1adb-4ad6-97c6-089762b69549.png)

**Comment by pparik** [comment]
This bug manifests only in some savegames. Savegames from original Locomotion are ok. Is it possible the capacity values are broken during save/load?

**Comment by duncanspumpkin** [comment]
Okay that is interesting.

**Comment by Derpercoaster** [comment]
I use The Windows 10 version of OpenLoco (with the Steam version of the game) and also experience this problem. It usually occurs when I open the vehicle construction window and choose a different tab than the current one. I seem to get integer limits as the broken numbers (it changes depending on the vehicle, and possibly the year).

**Comment by pparik** [comment]
As far as I can tell, the bug manifests itself only in the Build new X window. The built vehicles are loaded at a station to their 'normal' capacity, as expected.

**Comment by pparik** [comment]
@duncanspumpkin, I have applied your fix and it works, thanks! :)
