### ISSUE TITLE
Enhancement: Ability to change the size of the mountain tool 

### ISSUE THREAD

**Issue by Derpercoaster** [OpenLoco/OpenLoco#1238]
**Describe the solution you'd like**
Currently, the mountain only allows a single tile to be the "base" of the mountain (see screenshots 1 and 4). My idea is to allow that size to be able to be increased while still creating mountain slopes (see screenshot 3, possibly 2 as well).

**Additional context**
OpenRCT2 has the exact feature I am requesting. I've included screenshots from both games for reference.

**Screenshots**

The default mountain size in OpenRCT2, currently the only possible size in OpenLoco:
![0](https://user-images.githubusercontent.com/60452987/139492063-4be470c6-684d-4e3a-82a4-cd4ee0acf83a.png)

"Corner" sized mountain, made by only drawing the mountain from a single tile corner (this would ideally be added too):
![1](https://user-images.githubusercontent.com/60452987/139492064-12057b5a-0ed2-43bf-8799-0fa7cf5f263e.png)

The feature I am requesting, being able to draw larger mountains with the mountain tool:
![2](https://user-images.githubusercontent.com/60452987/139492065-078b6e60-2eb0-48f1-b6f0-c2e6ce6f413d.png)

What is currently possible in OpenLoco:
![image](https://user-images.githubusercontent.com/60452987/139492100-b6aeffc2-a13e-4214-93f9-5385f6e7f1d9.png)

**Comment by AaronVanGeffen** [comment]
This would be nice, but requires more implementation. Currently, the game commands related to land tools still use the original Locomotion routines. They have to be reimplemented before we can expand them.

**Comment by AaronVanGeffen** [comment]
This is addressed by #2228.
