### ISSUE TITLE
Bug: News Sound Effects do not play at all.

### ISSUE THREAD

**Issue by Derpercoaster** [OpenLoco/OpenLoco#1240]
**Version information:**
 - Platform: Windows 10
 - Version: 21.10
 - Build/commit: 3bec790

**Describe the bug**
In the vanilla game, applause/booing/wow sound effects play when news is displayed, depending on the nature of the news. However, these sounds never play in OpenLoco.

**Expected behaviour**
These sounds should always play when news appears.

**Comment by AaronVanGeffen** [comment]
Why was this closed? Did the bug not happen as reported after all?

**Comment by Derpercoaster** [comment]
The bug still occurs, I didn’t mean to close it. I was distracted and
thought it was a different bug report I had made. It can be reopened.

**Comment by Derpercoaster** [comment]
I've noticed many sounds (mostly with vehicles) are played incorrectly. Sounds that are meant to change in pitch never do, and certain vehicles play the wrong sound (usually vehicles with an idling engine sound). Sometimes sounds are played by the wrong vehicle (I've heard steam locomotives play the "clickety clack" sound instead of a whistle).

Is it possible these are related at all? none of this occurs in the original game.

**Comment by duncanspumpkin** [comment]
We don't have a sound mixer in the code atm so we can't do pitch changes. That is a known bug. Keep this issue just for news sound effects

**Comment by duncanspumpkin** [comment]
I think this has been fixed now.

**Comment by LeftofZen** [comment]
> I think this has been fixed now.

agreed

**Comment by AaronVanGeffen** [comment]
Should it be added to the changelog?

**Comment by LeftofZen** [comment]
I think it should be retrospectively added to the changelog for 22.03
