### ISSUE TITLE
Total train power display bug

### ISSUE THREAD

**Issue by pparik** [OpenLoco/OpenLoco#1241]
**Version information:**
 - Platform: Fedora 33
 - Version: 21.10

**Describe the bug**
The total power of a train is shown incorrectly when the value overflows 24,000.

**To Reproduce**
Steps to reproduce the behaviour:
1. Build a train with multiple engines until the total power goes negative.

**Expected behaviour**
The total power is displayed correctly always.

**Screenshots**

The total power is still correct but approaches the limit:
![image](https://user-images.githubusercontent.com/26385735/139529710-db83f55b-16de-4e2c-9d71-2be08d7dcdc7.png)

After adding another engine:
![image](https://user-images.githubusercontent.com/26385735/139529727-ef9cf421-c728-4a3f-a9a2-e3837fb34751.png)

**Comment by duncanspumpkin** [comment]
Does this happen in vanilla. I would hazard a guess and say it does.

**Comment by pparik** [comment]
> Does this happen in vanilla. I would hazard a guess and say it does.

In CSL GOG, the total power is capped at 48,895 kW, regardless of the number of engines added after that.
![image](https://user-images.githubusercontent.com/26385735/139555087-33d9aba6-bf1a-4240-b382-51accbb1a0bb.png)

**Comment by duncanspumpkin** [comment]
No this will be unrelated. This is clearly a sign unsign issue i.e 1 bit. Quite different to the word difference of the capacity

**Comment by LeftofZen** [comment]
I wanted to fix this but currently it isn't possible to do 'correctly':

1. String is 'drawn' here: https://github.com/OpenLoco/OpenLoco/blob/e3c2904dff69fafec3d633b3aac154765e751de0/src/OpenLoco/Windows/Vehicle.cpp#L1423
2. The args being pushed on are correct - with 9xSD70's, the `train.veh2->totalPower` is 32000, and with 10 of them, it is 36000. It is clear this crosses the signed 16-bit integer limit.
3. The string format is `StringIds::vehicle_details_total_power_and_weight` which is string_id 329:
https://github.com/OpenLoco/OpenLoco/blob/e3c2904dff69fafec3d633b3aac154765e751de0/src/OpenLoco/Localisation/StringIds.h#L320
4. Which is here: https://github.com/OpenLoco/OpenLoco/blob/e3c2904dff69fafec3d633b3aac154765e751de0/data/language/en-GB.yml#L346
5. As we can see, the string format uses `{POWER}` to print the power, presumably to do an internal calculation to calculate the 'displayed' power from the totalPower and the weight, and to add the 'kW' formatting.
6. So how is `{POWER}` formatted/drawn? That comes back to the `Gfx::DrawString` command, which hasn't been reverse-engineered yet: https://github.com/OpenLoco/OpenLoco/blob/e3c2904dff69fafec3d633b3aac154765e751de0/src/OpenLoco/Graphics/Gfx.cpp#L985

So, we could fudge a fix by converting this to uint32_t in the string format in the yml and calculated the effective power ourselves, but I think the proper fix for this will rely on this drawString method `drawString_494BBF` being reverse-engineered first.

**Comment by LeftofZen** [comment]
I'll leave the above as reference to the past, but I have indeed fixed this. Here's the additional steps:
7. Looking in IDA at this function:

![image](https://user-images.githubusercontent.com/7483209/158722909-4b24bdcb-04f0-4fc6-9bd3-97864c868bfa.png)

We can see there are some called to reverse-engineered string formatting functions!

8. Digging through a few methods, we come to https://github.com/OpenLoco/OpenLoco/blob/e3c2904dff69fafec3d633b3aac154765e751de0/src/OpenLoco/Localisation/StringManager.cpp#L509
Which is where the `{POWER}` string is formatted, with control code 142. We can see we pop off the power value as `int16_t` instead of `uint16_t`. This change fixes the bug:

![image](https://user-images.githubusercontent.com/7483209/158723396-edc67fb4-1647-46b3-9ebf-a48dbf82b275.png)

**Comment by LeftofZen** [comment]
Addendum - the total power is now limited by the `uint16_t` limit, ie 65,536, which the game uses as 'horsepower' (ie imperial units). For kW, this value is now limited to `48,889` kW, or `65,535hp`:

![image](https://user-images.githubusercontent.com/7483209/158723510-377fc2bc-a714-476b-b523-23b101ba7d7f.png)
![image](https://user-images.githubusercontent.com/7483209/158723525-d5b38e6b-d2fa-4250-8d89-75fce36d9964.png)

**Comment by pparik** [comment]
@LeftofZen , in Vanilla, the max total power is 48,895 kW, so it seems OpenLoco is using a different coefficient (0.746) to Vanilla (0.7461).

**Comment by LeftofZen** [comment]
Nice pickup, I don't see why we shouldn't at least change it to match vanilla.

**Comment by duncanspumpkin** [comment]
In vanilla it did power * 764 / 1024 = power * 0.74609375
