### ISSUE TITLE
Bug: Impossible to save Landscape files in Scenario Editor

### ISSUE THREAD

**Issue by Derpercoaster** [OpenLoco/OpenLoco#1250]
**Version information:**
 - Platform: Windows 10
 - Version: 21.10
 - Build/commit: 3bec790

**Describe the bug**
Attempting to save a landscape whilst in the scenario editor doesn't work. When you click "save landscape", and then click "OK", the landscape doesn't actually save. The only way to save it is to click "load" and use the save button on the "save before loading" prompt, which is ridiculous.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open scenario editor
2. Do whatever you want in it, and then click "save landscape" in the options menu
3. Name it whatever you want, and click "OK"
4. Result: The landscape won't actually be saved.

**Expected behaviour**
Saving a landscape should obviously save the landscape.

**Additional context**
If you make enough changes (or wait long enough, whichever comes first), and click "Load Landscape", the game will prompt you to save before loading (as it should). This is the only way to actually save a landscape currently.

**Comment by LeftofZen** [comment]
Is this still an issue? I am able to save scenarios with no issues in v22.03, would you be able to confirm if this is still an issue for you?

**Comment by LeftofZen** [comment]
Whoops my apologies, I misunderstood and thought the scenario wasn't saving when you go through the editor stops, but that wasn't the problem, it was saving the landscape file itself. I can confirm this isn't saving for me either.

**Comment by LeftofZen** [comment]
So uh yeah, this one is quite obvious. We simply don't call the `saveGame()` code when the 'Save Landscape' button is pressed. Ooof.

`Save Landscape` code: https://github.com/OpenLoco/OpenLoco/blob/10d7c631febe268f3f7eb4796ceac2f5ac629682/src/OpenLoco/Windows/ToolbarTopAlt.cpp#L149

Code from the prompt to save:
https://github.com/OpenLoco/OpenLoco/blob/10d7c631febe268f3f7eb4796ceac2f5ac629682/src/OpenLoco/Game.cpp#L268

**Comment by Derpercoaster** [comment]
I thought this one was fixed in a previous version. I distinctly remember it working after updating the game. Am I wrong?

**Comment by LeftofZen** [comment]
Perhaps it was fixed and the bugged again in a subsequent change.

I fired up 22.03.1 and tried saving the landscape from the toolbar menu, and it didn't work as you described. The code backs this up, as you can see from before my code change here, the game showed the save window, but didn't actually run any code to do the saving itself.
