### ISSUE TITLE
Crash: Game Crashed When exiting a Modded Scenario

### ISSUE THREAD

**Issue by Derpercoaster** [OpenLoco/OpenLoco#1252]
**Version information:**
 - Platform: Windows 10
 - Version: 21.10
 - Build/commit: 3bec790

**Describe the bug**
I have numerous modded assets installed into the game. Whenever I try to exit the scenario editor or a scenario that includes them, the game  predictably crashes. However, some of the modded assets replace vanilla assets, and yet vanilla scenarios (which contain those replaced assets) seem to work fine. Crash reports are included below (five total). This is a completely predictable issue that seems consistent throughout each instance.

[1f0bc491-5f84-46e2-a51e-ba28032a44eb(OpenLoco, v21.10 (3bec790 on master)).zip](https://github.com/OpenLoco/OpenLoco/files/7532486/1f0bc491-5f84-46e2-a51e-ba28032a44eb.OpenLoco.v21.10.3bec790.on.master.zip)

[275adf75-e036-4db8-b11c-5652f3e1659f(OpenLoco, v21.10 (3bec790 on master)).zip](https://github.com/OpenLoco/OpenLoco/files/7532487/275adf75-e036-4db8-b11c-5652f3e1659f.OpenLoco.v21.10.3bec790.on.master.zip)

[2759f16e-af03-45d3-ab64-b0f83b810ece(OpenLoco, v21.10 (3bec790 on master)).zip](https://github.com/OpenLoco/OpenLoco/files/7532488/2759f16e-af03-45d3-ab64-b0f83b810ece.OpenLoco.v21.10.3bec790.on.master.zip)

[bfa1caac-e3f9-4918-98b4-3013fa695ddf(OpenLoco, v21.10 (3bec790 on master)).zip](https://github.com/OpenLoco/OpenLoco/files/7532489/bfa1caac-e3f9-4918-98b4-3013fa695ddf.OpenLoco.v21.10.3bec790.on.master.zip)

[e425528b-e3a2-409f-984e-a8053eaa624b(OpenLoco, v21.10 (3bec790 on master)).zip](https://github.com/OpenLoco/OpenLoco/files/7532491/e425528b-e3a2-409f-984e-a8053eaa624b.OpenLoco.v21.10.3bec790.on.master.zip)

**Comment by Derpercoaster** [comment]
If I need to provide the modded assets, just let me know.

**Comment by LeftofZen** [comment]
@Derpercoaster if you have the save and the custom objects, that'd help greatly in repro-ing the issue

**Comment by Derpercoaster** [comment]
I am trying to send the files in a zip folder (I am NOT sending the literally hundreds of assets one by one), but the file keeps getting rejected by Github. It says " is not included in the list", in those exact words.

**Comment by duncanspumpkin** [comment]
If you are on discord you can pm the file. GitHub at least used to work with zips perhaps it has changed

**Comment by LeftofZen** [comment]
And also, I noticed github doesn't like .rar or .7z or anything, but it does like .zip, maybe that's it?

**Comment by Derpercoaster** [comment]
I am compressing it with .zip. It refuses to work

**Comment by LeftofZen** [comment]
Dang, then yeah pm me or duncan the file

**Comment by Derpercoaster** [comment]
Is there a discord for this github or something? I'm not in it if there is.
Also, I tried uploading other file types (docx etc) just to see it if it would work, and it didn't. Github isn't letting me upload a lot of things

**Comment by AaronVanGeffen** [comment]
There's a link to our Discord in the readme for this repository.

**Comment by LeftofZen** [comment]
I spoke with Derpercoaster on discord and we were unable to repro this issue. In future if this issue occurs again, we'll make a new issue with some repro steps.
