### ISSUE TITLE
Delete key does not work

### ISSUE THREAD

**Issue by pparik** [OpenLoco/OpenLoco#1254]
**Version information:**
 - Platform: Fedora 33
 - Version: 21.10

**Describe the bug**
The Delete key does not work in input boxes, it instead inserts a random integer (sometimes negative).

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any input box (e.g. rename a station, train, etc.)
2. Use arrow keys to move inside the input box
3. Press Delete

**Expected behaviour**
The character immediately after the cursor is removed, as in Vanilla.

**Screenshots**
Delete pressed 10 times, 10 random integers inserted, starting with -24,570.
![image](https://user-images.githubusercontent.com/26385735/141689866-a6b24713-acc1-47d4-95b3-e7ed48202da0.png)

**Comment by DanKorell** [comment]
I also get similar behaviour on v22.03.1. Pressing delete causes numbers to appear. I saw this when entering my name, renaming vehicles, etc.
