### ISSUE TITLE
Original Bug: EW-IV Driving Carriage not Considered a Locomotive

### ISSUE THREAD

**Issue by Derpercoaster** [OpenLoco/OpenLoco#1255]
**Version information:**
 - Platform: Windows 10
 - Version: 21.10
 - Build/commit: 3bec790

**Describe the bug**
The EW-IV driving carriage is not considered a locomotive by the game, and as such can't be used on trains without another locomotive. It also doesn't have any horsepower rating attached to it.

**Expected behaviour**
I should be able to use the aformentioned vehicle for its intended purpose.

**Comment by eldomtom2** [comment]
This is intended behaviour - the EW-IV driving carriage is not a locomotive in real life. It is a control car - a carriage with controls for the driver that link to the locomotive at the other end of the train. This is not a bug and should not be "fixed".

**Comment by LeftofZen** [comment]
@eldomtom2 is correct, this is not a bug, this is how the locos work both in game in IRL

**Comment by LeftofZen** [comment]
although I agree it is potentially confusing as some vehicles such as the APT have a `passenger` carriage, a `driving` carriage and a `power` carriage, whilst the EW-IV only has `passenger` and `driving`

**Comment by Derpercoaster** [comment]
> although I agree it is potentially confusing as some vehicles such as the APT have a `passenger` carriage, a `driving` carriage and a `power` carriage, whilst the EW-IV only has `passenger` and `driving`

It does feel really weird. No other vehicles that exist in a set (driving, passenger, power) allow unrelated vehicles to be added to the consist. It makes me wonder why there isn't just a normal passenger carriage instead of the EW-IV set.

**Comment by LeftofZen** [comment]
yeah true, does anyone with actual locomotive knowledge (@eldomtom2 ?) know how these trains are powered IRL?

**Comment by eldomtom2** [comment]
By an electric locomotive at the other end of the train, in the case of these specific carriages by the Re 460 which is included in the game.

Here's a video of a real life example: https://www.youtube.com/watch?v=akRxBTvTVcI

**Comment by LeftofZen** [comment]
Awesome, thankyou very much for that! @Derpercoaster there's your answer!
