### ISSUE TITLE
Compiling on Ubuntu 20.04

### ISSUE THREAD

**Issue by in3rsha** [OpenLoco/OpenLoco#1257]
I'm trying to compile this game on Ubuntu 20.04.

At first, there is an issue with the dependency `libyaml-cpp-dev:i386` not being available, so to get around this I installed `libyaml-cpp-dev` (not sure if this will work).

Then when compiling, I get this error:

```
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


CMake Error: The source directory "/home/user/Desktop/OpenLoco/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

To try and get around this, I've pulled this version of OpenLoco which should work on Ubuntu 20.04: https://github.com/janisozaur/OpenLoco/

However, at the compilation stage I still get the same error.

I thought it might work if I just copied the `CMakeLists.txt` file to the `build/` folder, but then I get this error:

```
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


CMake Warning at CMakeLists.txt:10 (find_package):
  By not providing "FindCCache.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "CCache", but
  CMake did not find one.

  Could not find a package configuration file provided by "CCache" with any
  of the following names:

    CCacheConfig.cmake
    ccache-config.cmake

  Add the installation prefix of "CCache" to CMAKE_PREFIX_PATH or set
  "CCache_DIR" to a directory containing one of the above files.  If "CCache"
  provides a separate development package or SDK, be sure it has been
  installed.


-- The CXX compiler identification is GNU 9.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:31 (message):
  Building in-source is not supported! Create a build dir and remove
  /home/user/Desktop/OpenLoco/build/CMakeCache.txt


-- Configuring incomplete, errors occurred!
See also "/home/user/Desktop/OpenLoco/build/CMakeFiles/CMakeOutput.log".
```

I'm not sure where to go from here on getting OpenLoco to compile.

Has anyone had any success in getting OpenLoco to compile on Ubuntu 20.04?

**Comment by janisozaur** [comment]
Clean your workdir (e.g. `git clean -dxf`) and follow the steps in our readme: https://github.com/OpenLoco/OpenLoco#linux--macos-1

**Comment by janisozaur** [comment]
I suppose you were using #1007, which grew quite stale since it was opened. I've rebased it now and retested, works fine on my end.

**Comment by YJSoft** [comment]
![image](https://user-images.githubusercontent.com/5893514/141710136-c538b739-dce4-4b7d-abc9-a618a02b27f7.png)

I can confirm with #1007 compile and run works.(with clean install of Ubuntu 20.04)

p.s.) Methods from [README.md](https://github.com/OpenLoco/OpenLoco#42-compiling-and-running)(a.k.a. Building the game on Linux) works, but [Building the game on Ubuntu](https://github.com/OpenLoco/OpenLoco/wiki/Building-on-Ubuntu) is not. I think wiki should be updated.

**Comment by in3rsha** [comment]
Okay thank you. I think I'm getting somewhere, although I'm now getting stuck in relation to `yaml-cpp`.

Forgive me for repeating the same steps again, but I'll run through my process so far.

I've installed the following dependencies (using `libyaml-cpp-dev` instead of `libyaml-cpp-dev:i386`:

```
sudo apt-get install --no-install-recommends -y \
    pkg-config:i386 \
    g++-multilib \
    cmake \
    git \
    ninja-build \
    libsdl2-dev:i386 \
    libsdl2-mixer-dev:i386 \
    libpng-dev:i386 \
    libyaml-cpp-dev
```

Then the following build steps:

```
git clone https://github.com/OpenLoco/OpenLoco.git
cd OpenLoco
mkdir build
cd build
CXXFLAGS="-m32" cmake ..
```

This gives me the following error:

```
CMake Error at CMakeLists.txt:260 (find_package):
  Could not find a package configuration file provided by "yaml-cpp" with any
  of the following names:

    yaml-cppConfig.cmake
    yaml-cpp-config.cmake

  Add the installation prefix of "yaml-cpp" to CMAKE_PREFIX_PATH or set
  "yaml-cpp_DIR" to a directory containing one of the above files.  If
  "yaml-cpp" provides a separate development package or SDK, be sure it has
  been installed.
```

So it seems it can't find `yaml-cpp`. So I tried compiling the dependency from here: https://github.com/jbeder/yaml-cpp

```
git clone https://github.com/jbeder/yaml-cpp.git
cd yaml-cpp
mkdir build
cd build
cmake -YAML_BUILD_SHARED_LIBS=ON ..
```

This seems to compile without any error.

But when I try and compile OpenLoco again I get the same error:

```
CMake Error at CMakeLists.txt:260 (find_package):
  Could not find a package configuration file provided by "yaml-cpp" with any
  of the following names:

    yaml-cppConfig.cmake
    yaml-cpp-config.cmake

  Add the installation prefix of "yaml-cpp" to CMAKE_PREFIX_PATH or set
  "yaml-cpp_DIR" to a directory containing one of the above files.  If
  "yaml-cpp" provides a separate development package or SDK, be sure it has
  been installed.
```

I thought I could fix this by changing the location to find the package on line 260 of CMakeLists.txt as follows:

```
#find_package(yaml-cpp REQUIRED HINTS /usr/lib32/cmake/yaml-cpp
find_package(yaml-cpp REQUIRED HINTS /path/to/yaml-cpp/build)
```

But then I get this error:

```
-- Could NOT find CCache (missing: CCache_EXECUTABLE)
CMake Error at CMakeLists.txt:260 (find_package):
  Could not find a configuration file for package "yaml-cpp" that is
  compatible with requested version "".

  The following configuration files were considered but not accepted:

    /home/user/Desktop/yaml-cpp/build/yaml-cpp-config.cmake, version: 0.7.0 (64bit)
```

So I'm pretty sure the problem is with my `yaml-cpp` dependency.

I know this is not a problem with this project, but do you know how I could go about compiling the `yaml-cpp` dependency correctly for use with compiling OpenLoco?

**Comment by janisozaur** [comment]
Yaml-cpp is mispackaged, use the code from #1007

**Comment by janisozaur** [comment]
Additionally, the error you got was because while you compiled yaml-cpp, it was a 64-bit build, v which you tried linking to 32-bit executable. You may retry compiling a 32-bit version, just like you have to do with OpenLoco itself

**Comment by in3rsha** [comment]
Thank you.

I updated to use the code from branch #1007 with this:

```
gh pr checkout 1007
```

I then recompiled `yaml-cpp`.

When I now try to compile OpenLoco I see this new error message:

```
CMake Error at CMakeLists.txt:247 (find_package):
  By not providing "FindSDL2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SDL2", but
  CMake did not find one.

  Could not find a package configuration file provided by "SDL2" with any of
  the following names:

    SDL2Config.cmake
    sdl2-config.cmake

  Add the installation prefix of "SDL2" to CMAKE_PREFIX_PATH or set
  "SDL2_DIR" to a directory containing one of the above files.  If "SDL2"
  provides a separate development package or SDK, be sure it has been
  installed.
```

I have already installed both of these dependencies with:

```
sudo apt-get install libsdl2-dev:i386
sudo apt-get install libsdl2-mixer-dev:i386
```

Do you know where I should go from here? Sorry to be a pain.

**Comment by janisozaur** [comment]
Can you join our discord? OpenLoco Discord: https://discord.gg/vEuNRHD

**Comment by AaronVanGeffen** [comment]
This should no longer be an issue as of #1576.
