### ISSUE TITLE
Building on Arch Linux

### ISSUE THREAD

**Issue by fenuks** [OpenLoco/OpenLoco#1265]
**Version information:**
 - Platform: [Arch Linux]
 - Version: [21.10, but also latest git]
 - Build/commit: [c880ae24]

**Describe the bug**
I want to prepare AUR package for OpenLoco, and found few issues in the process.
- it doesn't build for with GCC 11.1.0 because of -Werror
For default build `-Wno-error=cpp` needs to be added, and for CMAKE_BUILD_TYPE=release:
`-Wno-error=cpp -Wno-error=stringop-overflow= -Wno-error=array-bounds -Wno-error=stringop-overread`
- install target doesn't copy [data/language](https://github.com/OpenLoco/OpenLoco/tree/master/data/language) files. Trying to run installed executable yields:
```
Warning: file "/usr/bin/data/language" could not be not found
filesystem error: directory iterator cannot open directory: No such file or directory [/usr/bin/data/language]
```
I could include that folder manually, but I think it shouldn't be in `/usr/bin/data/language`, but in `/usr/share/openloco/languages`. Currently, it's not possible to configure this, location is hardcoded [here](https://github.com/OpenLoco/OpenLoco/blob/c880ae24d827e67d1d5275285d0a1d5f5e35590e/src/OpenLoco/Environment.cpp#L258)

**To Reproduce**
Steps to reproduce the behaviour:
Users of Arch-based distros can use this PKGFILE:
```sh
pkgname=openloco
pkgver=21.10
pkgrel=1
pkgdesc="An open source re-implementation of Chris Sawyer's Locomotion"
arch=('x86_64')
url="https://github.com/OpenLoco/OpenLoco"
license=('MIT')
depends=(lib32-libpng libzip lib32-sdl2 lib32-sdl2_mixer lib32-yaml-cpp breakpad)
makedepends=('cmake')
source=("https://github.com/OpenLoco/OpenLoco/archive/refs/tags/v${pkgver}.tar.gz")
sha1sums=('e80d156c500b4de32264e959a77aebf3e020783b')

build() {
  cd "${srcdir}/OpenLoco-${pkgver}"
  mkdir -p build
  cd build
  # CXXFLAGS="-m32 -Wno-error=cpp" cmake -B. -H.. \
  #   -DCMAKE_INSTALL_PREFIX=/usr
  CXXFLAGS="-m32 -Wno-error=cpp -Wno-error=stringop-overflow= -Wno-error=array-bounds -Wno-error=stringop-overread" cmake -B. -H.. \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=release
  make
}

package() {
  cd "${srcdir}/OpenLoco-${pkgver}/build"
  make DESTDIR="${pkgdir}" install
}
```
, otherwise it is possible to manually invoke above commands, and install game into /usr/local.

**Expected behaviour**
- building with GCC 11 without passing any additional flags
- it should be possible to specify custom path where language file are stored
- language files should be copied to that directory when `make install` is issued

**Comment by AaronVanGeffen** [comment]
To avoid the warnings, you can disable `-Werror` by passing `-DSTRICT=NO` when invoking cmake.
https://github.com/OpenLoco/OpenLoco/blob/c880ae24d827e67d1d5275285d0a1d5f5e35590e/CMakeLists.txt#L38

For the language files, we could look for them in more (platform-dependent) directories. I would welcome a PR for this.

**Comment by fenuks** [comment]
Thank you, as for configurable location for language files, I will try to look into that.
