### ISSUE TITLE
Crash: Game Crashed when Switching between tabs in Vehicle Building Menu

### ISSUE THREAD

**Issue by Derpercoaster** [OpenLoco/OpenLoco#1266]
**Version information:**
 - Platform: Windows 10
 - Version: 21.10
 - Build/commit: 3bec790

**Describe the bug**
I was customizing vehicle colors and decided to switch from the train tab to the bus tab to see how my choices would look. The game immediately crashed.

**To Reproduce**
Steps to reproduce the behaviour:
Not sure if this can be replicated, but:
1. Have the company color menu open (I had custom colors for all vehicle types)
2. Have "Build New Vehicle" menu open
3. Switch from one tab to another (I switched from train to bus after changing the colors of both)
4. Crash

**Crash Report**
[741fcd97-2ef0-4467-a1bf-05aa129ac9fd(OpenLoco, v21.10 (3bec790 on master)).zip](https://github.com/OpenLoco/OpenLoco/files/7584308/741fcd97-2ef0-4467-a1bf-05aa129ac9fd.OpenLoco.v21.10.3bec790.on.master.zip)

(P.S.: We really need to allow .dmp files to be an accepted format)

**Comment by LeftofZen** [comment]
I was unable to repro this locally. Does this still happen for you in v22.03.1 @Derpercoaster?

**Comment by Derpercoaster** [comment]
> I was unable to repro this locally. Does this still happen for you in v22.03.1 @Derpercoaster?

I haven't played the game in the past few months, so I don't know. I also can't check anytime soon, since I'm a bit busy with life.
