### ISSUE TITLE
"Malformed vehicle. Incorrect subType!"

### ISSUE THREAD

**Issue by LeftofZen** [OpenLoco/OpenLoco#1279]
**Version information:**
 - Platform: Win10 21H1 (19043.1348)
 - Version: 21.10
 - Build/commit: 3bec790

**Describe the bug**
I receive "Malformed vehicle. Incorrect subType!" exception. Vehicle head can't figure out it's connected vehicles? I got into this state by deleting a vehicle with cargo in it, then erasing the track it was on. About 10 seconds after that, I get this exception. I presume the vehicle isn't being disposed of correctly when it is deleted in-game.

**To Reproduce**
I'm not sure what the exact setup steps are, but I've attached a save file that triggers this exception. Load and wait about 10 seconds.
[Race to Read.zip](https://github.com/OpenLoco/OpenLoco/files/7660672/Race.to.Read.zip)

**Expected behaviour**
Not crash

**Screenshots**
N/A

**Additional context**
N/A

**Comment by LeftofZen** [comment]
I see the command `GameCommand::vehicleSell` hasn't decompiled yet, so  probably not much hope on fixing the original cause here. However I was able to resume playing by returning nullptr instead of throwing, and checking for nullptr where this train/vehicle is being dereferenced.

**Comment by luk3ZPL** [comment]
#1279 First of all I set back date to 1 Dec. No little summary:
0. crash is appearing when date changes from 31 Dec 1906 to 1 Jan 1907, but when you change it to 1 Jan 1907 after load the game there is no crash
1. you may have only 6 active windows with trains opened at the same time
2. crash still occuring when you sell all your vehicles
Does it look like vehicle properties somehow was changed during gameplay ?

**Comment by duncanspumpkin** [comment]
Looks to be caused by the game not cleaning up vehicle audio objects.
