### ISSUE TITLE
trees in operation are dying

### ISSUE THREAD

**Issue by ERRORTEK23** [OpenLoco/OpenLoco#128]
When there is a lot of track and a lot of train the trees will all die. And extreme is not nice, then a man has to plant trees. If it could be turned off to keep the trees out.

**Comment by jgottula** [comment]
Is this actually something that Locomotion simulates? I wasn't under the impression that trees near operational tracks would die off more than usual.

It is definitely true that Locomotion simulates normal tree growth / dying as the seasons go by, though.

**Comment by duncanspumpkin** [comment]
@ERRORTEK23 can you provide more information on this? I can't tell if you are saying this is a bug or if its a feature you want added.

**Comment by ERRORTEK23** [comment]
I would say funce. Or it could be planting a forest like in the editor. As YetiWiz mentions in Make mountain tool available when adjusting land in-game.

**Comment by AaronVanGeffen** [comment]
The tree cluster tool has been available in-game for a while now. Presuming that meets this request.
