### ISSUE TITLE
Deleting track that causes a train to crash also causes the game to crash

### ISSUE THREAD

**Issue by LeftofZen** [OpenLoco/OpenLoco#1280]
**Version information:**
 - Platform: Win10 21H1 (19043.1348)
 - Version: 21.10
 - Build/commit: 3bec790

**Describe the bug**
Game crashes.

**To Reproduce**
1. Set up a train line
2. Add a train with vehicles
3. Start the train
4. Right-click to select a piece of track ahead of the train
5. Press and hold the "delete track" button, ensuring you delete track in the direction of the oncoming train
6. Keep deleting track until the train has completely in-game crashed
7. Attempt to 'stop' the train from the vehicle window
8. Boom

**Expected behaviour**
Not crash

**Screenshots**
![crash](https://user-images.githubusercontent.com/7483209/144944079-00338e71-19b8-4257-a742-95e03510ec55.png)

**Additional context**
* Attached is the core dump from the crash.

**Core dump**
[49694e82-40f2-4f34-834c-fdc673e3e0fd(OpenLoco, v21.10 (3bec790 on master)).zip](https://github.com/OpenLoco/OpenLoco/files/7664405/49694e82-40f2-4f34-834c-fdc673e3e0fd.OpenLoco.v21.10.3bec790.on.master.zip)

**Comment by Derpercoaster** [comment]
The reason the game is crashing here has nothing to do with track. The game crashes when you remove a crashed vehicle while the "[Vehicle] has crashed!" pop-up window is still present. If the window is allowed to disappear or you close it first, the game will not crash.

**Comment by LeftofZen** [comment]
Just adding a comment that @Derpercoaster is correct here, the crash happens as they describe it. I also tested this in vanilla and it doesn't occur, so its just an OpenLoco bug we've introduced

**Comment by Derpercoaster** [comment]
> ...its just an OpenLoco bug we've introduced

How does something like that happen? I mean, I know bugs come up when code is changed, but it still gets me that a bug is able to crash the game. Is it calling for a line of code on an infinite loop or something, and using up resources?

**Comment by duncanspumpkin** [comment]
It's usually due to something silly. What we implement isn't 1:1 identical sometimes edge cases are considered impossible and code not implemented. Sometimes it's because we write more robust code that for example cleans up things better but the original incorrectly expected it not to clean up. And sometimes it's just a mistake.

**Comment by LeftofZen** [comment]
A computer does exactly what it's told to do, and if you tell it do do the wrong thing, it'll attempt to do the wrong thing because it doesn't know any better.

In this case I don't know what the exact bug is so I can't give a perfect analogy, but *for example* a common 'crashing' bug or error in programming is a [segmentation fault](https://en.wikipedia.org/wiki/Segmentation_fault), usually shortened to 'segfault'. 
Basically this is where the program has tried to access some data from a memory location but that memory location is invalid, either because it doesn't exist, or because it is outside the memory space allocated to it by the parent process/OS, or because it doesn't have permission from the OS to access it, etc. In these cases, what is the computer supposed to do to recover from such an error? There is nothing it can do, because it can't 'guess' at what you intended the correct operation to be. The way to fix things like this is to simply avoid the segfault altogether, by ensuring your program only accesses valid memory locations. If a programmer forgets to write the code to check the memory address is valid, then the computer will indeed try to access that location, then OS will say 'nope' and it'll terminate your program for being naughty.

That was an extremely simplified explanation of a single type of 'crash', but basically crashes are where you are instructing the computer to do something that doesn't make sense and the OS terminates your program so that it (the OS) can remain alive and running.

And now I see duncan replied whilst I was writing this, rip ;(
