### ISSUE TITLE
Bug: Unable to Open Tabs to Build new Track/Road

### ISSUE THREAD

**Issue by Derpercoaster** [OpenLoco/OpenLoco#1281]
**Version information:**
 - Platform: Windows 10
 - Version: 21.10
 - Build/commit: 3bec790

**Describe the bug**
Occasionally, clicking the "build new track (or road)" tabs does not open them. Instead they immediately close themselves, and the only way to fix the issue is to reload the save.

**To Reproduce**
Not sure how to reproduce this bug

**Expected behaviour**
Tabs should always open when clicked

**Additional context**
Right-clicking to build track/roads still works, but once you click to select a location for the road/track piece, the window closes itself again. This makes it impossible to build with a track/road type that is not already present.

**Comment by LeftofZen** [comment]
I've also experienced this issue many times, and I also just save+reload to fix it. I haven't been able to determine the conditions that cause this issue yet, so if anyone else with this issue can find a set of steps that reproduce the problem, this would make fixing this bug much easier.

**Comment by Roeliooo** [comment]
Bug is still present in latest veraion 22.02. I don't know how to reproduce it. Seems randomly..

**Comment by DanKorell** [comment]
I only found OpenLoco the other day, so I've started with v22.03.1, and this issue is present here too. However, it did also go away on its own, too, as I didn't save and reload.
