### ISSUE TITLE
Bug: Tutorial Levels Reset the Screen Resolution and Zoom Factor to Default Values

### ISSUE THREAD

**Issue by Derpercoaster** [OpenLoco/OpenLoco#1283]
**Version information:**
 - Platform: Windows 10
 - Version: 21.10
 - Build/commit: 3bec790

**Describe the bug**
When starting a tutorial level, the screen resolution and zoom factor are resetto the default values if they were not already set to the default values.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start a tutorial level with the screen resolution and zoom set to anything other than the default values (Which are the largest 4:3 ratio and 1.00, respectively. For reference, I use the largest 16:9 ratio and a zoom of 2.00 when I play the game).

**Expected behaviour**
Window resolution and zoom should by modified by the tutorial

**Comment by Derpercoaster** [comment]
I cannot provide a screenshot because that would require me to screenshot my desktop, which I cannot because I have personal files I do not want anyone else seeing.

Also of note, if the game window is maximized (assuming you are playing in windowed mode), the tutorial un-maximizes it.

**Comment by IntelOrca** [comment]
This is a permenent restriction. The tutorials are recordings of mouse input, so all the UI needs to be exactly as it was when it was recorded hence the fixed resolution.

Not sure about the zoom factor, it could probably be improved to handle that.
