### ISSUE TITLE
Disable vehicle obsolete date

### ISSUE THREAD

**Issue by strongbowe1** [OpenLoco/OpenLoco#1316]
It would be nice to have checkbox in the options to disable the vehicle obsolete date - being able to buy vehicles that are not longer available due to reaching the obsolete date. Thus we could create retro trains, planes, etc. in our games.

**Comment by LeftofZen** [comment]
And similarly, a cheat to unlock vehicles that haven't been 'invented'

**Comment by LeftofZen** [comment]
relates to #1350 and follows on from #1354
