### ISSUE TITLE
Vehicle capacity string is misaligned

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenLoco/OpenLoco#1319]
**Version information:**
 - Platform: Linux
 - Version: 21.10+
 - Build/commit: g5cfc91fa

The vehicle capacity string appears to be preceded by an extra space, misaligning with the string above.

![Screenshot (1)](https://user-images.githubusercontent.com/604665/152682243-b19e0a67-484b-4838-a61d-66070a6282d1.png)

**Comment by AaronVanGeffen** [comment]
The added space is already in the string used:
https://github.com/OpenLoco/OpenLoco/blob/b5122ff47db6162dadc4ae2e2adb4bce576430ca/data/language/en-GB.yml#L1287

Compared to the 'total' string, which does not have the extra space after the colour formatting code:
https://github.com/OpenLoco/OpenLoco/blob/b5122ff47db6162dadc4ae2e2adb4bce576430ca/data/language/en-GB.yml#L1312

**Comment by LeftofZen** [comment]
fixed in #1322
