### ISSUE TITLE
No checkmark when completeing a scenario

### ISSUE THREAD

**Issue by 0skis** [OpenLoco/OpenLoco#1320]
**Version information:**
 - Platform: Windows 10
 - Version: 22.02-1(f119eb5 on master)

**Describe the bug**
No checkmark is given to a scenario when it is completed. Can be reproduced on the first one.

**To Reproduce**
Beat any scenario i guess.

**Screenshots**
https://gyazo.com/b2344ecfcf106087e0a6a85f58ac0302
https://gyazo.com/ac25775035be450c4b23dddbf60d1f86

**Comment by 0skis** [comment]
![image](https://user-images.githubusercontent.com/43298214/152704301-98a3832e-5107-4343-85b8-bd27072640ab.png)

**Comment by 0skis** [comment]
https://gyazo.com/5db375314027ba3c092c7670e8a7120f

**Comment by 0skis** [comment]
I will let you know that this issue is not present in the previous release (v21.10 (3bec790 on master))

**Comment by duncanspumpkin** [comment]
Is that failed to open exception occurring when you are completing a scenario as well?

**Comment by 0skis** [comment]
> Is that failed to open exception occurring when you are completing a scenario as well?

No, I get the 'Challenge completed' pop-up as normal. The attached error messages appear when saving on a new scenario
