### ISSUE TITLE
Increase vehicle waiting times overall

### ISSUE THREAD

**Issue by YetiWiz** [OpenLoco/OpenLoco#134]
The waiting times for vehicles in general in this game are a joke. I mean, where in the world does a train after waiting at a signal for only under a minute, suddenly turn around and start driving in the wrong direction? What on earth was Chris thinking? It's as if he forgot to change the debug waiting times back to normal.
Same thing with road vehicles waiting at a rail crossing for example. What if the train crossing the road breaks down and doesn't pass in the 24 seconds the bus is willing to wait? That's right, the bus will turn around and possibly end up stuck due to its horrible pathfinding. That's an even bigger problem for trams, which cannot simply switch to the appropriate track after turning around (btw. a track switch piece for trams would be useful, probably a .dat).
I think the best solution here would be if you could adjust the waiting times by yourself in some kind of advanced settings editor. But the standard ones should be tweaked nevertheless. Even better if you could set them individually for every vehicle, a new tab in the vehicle window for that kind of stuff would be great, but that would require changing the save format so maybe later down the road.

**Comment by auge8472** [comment]
ACK, maybe it's an additional option to disable reversal of vehicles at all.

> Even better if you could set them individually for every vehicle, a new tab in the vehicle window for that kind of stuff would be great

Are you sure? One player can operate **many** vehicles. It would be a mess to tweak the settings one by one. Maybe an option per vehicle class (Busses, Trucks, trams, trains).

**Comment by YetiWiz** [comment]
> Are you sure? One player can operate many vehicles. It would be a mess to tweak the settings one by one. Maybe an option per vehicle class (busses, trucks, trams, trains).

Well they would all use the global values by default, it's just that if you want to modify a specific vehicle for whatever reason.

**Comment by senner007** [comment]
I agree that would be a nice feature, although it would add a lot more complexity to the gameplay. The best solution would probably be to implement smarter pathfinding. At least I think there should some logic that prevents trains from turning around when running in a track with one-way signals.

**Comment by AaronVanGeffen** [comment]
The routines for this logic have recently been implemented. We can change the waiting times, or abandon them entirely. Any thoughts?

**Comment by AaronVanGeffen** [comment]
This behaviour has been made optional since.
