### ISSUE TITLE
Refactor Audio::playSound(soundId, pan)

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenLoco/OpenLoco#1407]
Whilst looking at #1352 i noticed a refactoring opportunity a big amount of callers of Audio::playSound are wasting time calculating a value that is never used.
The problem is with `void playSound(SoundId id, const Map::Pos3& loc, int32_t pan);` this function should **ONLY** be used by the audio hooks. Never by code we are writing. This is because we have `void playSound(SoundId id, const Map::Pos3& loc);` and `void playSound(SoundId id, int32_t pan);` instead. Any callers that use `playSound(SoundId id, const Map::Pos3& loc, int32_t pan)` and specify a value for `pan` will end up doing exactly the same code as `playSound(SoundId id, int32_t pan);` i.e. `loc` is never used!

Remove all callers of `void playSound(SoundId id, const Map::Pos3& loc, int32_t pan);` outside of hooks. If they are specifying a pan other than `kPlayAtLocation` they should have their `loc` removed (unless this is in the Hooks file). Add a note that the function should **ONLY** be used by Hooks.

For example:
BuildVehicle.cpp L748
`Audio::playSound(Audio::SoundId::clickDown, Map::Pos3{ x, y, static_cast<int16_t>(pan) }, pan);`
becomes:
`Audio::playSound(Audio::SoundId::clickDown, pan);`

**Comment by memellis** [comment]
Is it OK if I have a go at creating a merge request for this issue?

**Comment by memellis** [comment]
Hi @duncanspumpkin 

Has this issue been addressed now?

**Comment by duncanspumpkin** [comment]
Yup looks like its all addressed.
