### ISSUE TITLE
Loading a scenario causes "Malformed vehicle. Incorrect subType!"

### ISSUE THREAD

**Issue by IntelOrca** [OpenLoco/OpenLoco#1424]
**Version information:**
 - Platform: Windows 11
 - Version: 22.03.1
 - Build/commit: 02931ef6bdb40a1f5fc70ceef84c4680cbfe90af

**Describe the bug**
Malformed vehicle. Incorrect subType!

**To Reproduce**
1. Wait on title screen until you see the flour mills. (see screenshot)
2. Open Boulders Breakers.

**Screenshots**
![image](https://user-images.githubusercontent.com/1482259/161377461-64e83656-a051-4132-8059-d8e5bb4dfabf.png)

**Additional context**
```
>	openloco.dll!OpenLoco::Vehicles::VehicleBase::as<OpenLoco::Vehicles::Vehicle2or6,6>() Line 182	C++
 	openloco.dll!OpenLoco::Vehicles::VehicleBase::asVehicle2Or6() Line 223	C++
 	openloco.dll!OpenLoco::Audio::VehicleChannel::update() Line 135	C++
 	openloco.dll!OpenLoco::Audio::updateVehicleNoise() Line 813	C++
 	openloco.dll!OpenLoco::tickLogic() Line 883	C++
 	openloco.dll!OpenLoco::tickLogic(int count) Line 839	C++
 	openloco.dll!OpenLoco::tick() Line 780	C++
 	openloco.dll!OpenLoco::fixedUpdate() Line 1125	C++
 	openloco.dll!OpenLoco::update() Line 1144	C++
 	openloco.dll!OpenLoco::run() Line 1181	C++
 	openloco.dll!OpenLoco::main(const OpenLoco::CommandLineOptions & options) Line 1267	C++
 	openloco.dll!OpenLoco::main(const char * args) Line 1300	C++
```

**Comment by luk3ZPL** [comment]
There is no problem with v22.03 a759b81 (25 day ago). If those title screens are pure save games just like in OpenTTD that means game could even crash by title screen. Solusion - turn off all vehicles from title screen.

**Comment by LeftofZen** [comment]
I also tried this, and no crash for me, how strange

**Comment by LeftofZen** [comment]
maybe similar to #1279

**Comment by LeftofZen** [comment]
The save I gave in #1279 still triggers the 'malformed vehicle' crash though, so maybe that could be an easier way to repro/test a fix.

**Comment by luk3ZPL** [comment]
First of all I set back date to 1 Dec. No little summary:
0. crash is appearing when date changes from 31 Dec 1906 to 1 Jan 1907, but when you change it to 1 Jan 1907 after load the game there is no crash
1. you may have only 6 active windows with trains opened at the same time
2. crash still occuring when you sell all your vehicles
Does it look like vehicle properties somehow was changed during gameplay ?
