### ISSUE TITLE
No lower limit on towns in scenario editor landscape generator

### ISSUE THREAD

**Issue by LeftofZen** [OpenLoco/OpenLoco#1430]
**Version information:**
 - Platform: Win11
 - Version: e.g. 22.03.1
 - Build/commit: e.g. 0c4cc36

**Describe the bug**
In scenario editor the `-` stepper for `No. of towns` is unbounded on decrement.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Scenario Editor
2. Go to Landscape Generation window
3. Go to Towns tab
4. Click `-` (decrement) stepper past 0 and see it wrap to 255
5. Trying to `+` (increment) resets the limit to 80.

**Expected behaviour**
Decrement operation stops at 1

**Screenshots**
![image](https://user-images.githubusercontent.com/7483209/161435290-e20610ed-e226-4e1d-bc95-37d5d748d3de.png)

**Additional context**

**Comment by AaronVanGeffen** [comment]
> Expected behaviour
> Decrement operation stops at 0

It should probably stop at 1, as it's not possible to create a scenario without any towns in it.

**Comment by LeftofZen** [comment]
> It should probably stop at 1, as it's not possible to create a scenario without any towns in it.

Just an off-by-one bug in my issue report :p
