### ISSUE TITLE
Vehicles should display their length on the vehicle details window

### ISSUE THREAD

**Issue by LeftofZen** [OpenLoco/OpenLoco#1433]
**Describe the solution you'd like**
Vehicles display their length on the vehicle details window, in both metric/imperial, and in in-game tiles:
![image](https://user-images.githubusercontent.com/7483209/161456040-92624335-b45d-47b6-8674-e8d44d157eab.png)

Vehicles also display their length in the build vehicles window as one of their stats.

**Describe alternatives you've considered**
- Having length display in both vehicle and build windows would be the most useful.
- Unsure how to display the 'tiles' part. OpenTTD just lists the number and doesn't display 'tiles' as text, so that could be an option.

**Additional context**
- Suggested by @YetiWiz on discord
- Implementation can be mostly copy-pasted from #1306

**Comment by LeftofZen** [comment]
VehicleObject doesn't have a length anywhere in it so I'm not sure how the length of a vehicle is determined by the game

**Comment by LeftofZen** [comment]
* VehicleObject::var_24[0] kind of looked promising, but some of the values didn't make sense for the length of the train
* its definitely not `VehicleObject::var_113` or `VehicleObject::var_04`
* it could be calculated by the game from the sprite widths?

**Comment by duncanspumpkin** [comment]
var_24 is what you want but its a bit more complex than just that!
```cpp
        auto vehObject = ObjectManager::get<VehicleObject>(vehicleTypeId);
        auto length = 0;
        for (auto i = 0; i < vehObject->var_04; ++i)
        {
            if (vehObject->var_24[i].body_sprite_ind == 0xFF)
            {
                continue;
            }

            auto unk = vehObject->var_24[i].body_sprite_ind & (VehicleObject::kMaxBodySprites - 1);
            length += vehObject->bodySprites[unk].bogey_position;
        }
        return length;
```
This looks to be how it works but i do see there is a version of this that *2 the length for some reason.

**Comment by duncanspumpkin** [comment]
Yeah so move https://github.com/OpenLoco/OpenLoco/blob/master/src/OpenLoco/Vehicles/VehicleHead.cpp#L318 into the VehicleObject struct and drop the comment about it possibly only being for Road its valid for both road and rail.

**Comment by LeftofZen** [comment]
@YetiWiz I know you were working on this feature, any updates? If not, feel free to push your branch and I can finish it off.
