### ISSUE TITLE
Choice to Invert Right-Click Dragging to Move View

### ISSUE THREAD

**Issue by Derpercoaster** [OpenLoco/OpenLoco#1457]
**Describe the solution you'd like**
Currently, right-clicking and dragging the view goes in the same direction as you drag. There should be an option to invert this control so dragging one way causes the view to move the other way (many other games have this, including OpenRCT2)

**Additional context**
I think it's worth noting that many people who use touchscreens are used to dragging moving the view in the opposite direction (myself included), so this game's controls feel very wrong in comparison.

**Comment by LeftofZen** [comment]
Just had a quick look at this and its trivial to implement, I will add this in the next day or so :)

**Comment by Derpercoaster** [comment]
To be clear, by "add this", you mean implement it as a feature in a future update, right? I've seen people make fixes to code and such that involves having to actually modify the game code yourself ("yourself" being the player).

**Comment by LeftofZen** [comment]
Yes, I did the code change this morning and you can see the PR linked on this issue. It'll be in the next release (sadly we just did a release yesterday, so the next one is a month away at best), but once its merged to master you could always compile and run the master branch yourself, then you'd have that feature immediately.

**Comment by LeftofZen** [comment]
It'll be here in the options
![image](https://user-images.githubusercontent.com/7483209/163095150-5d0fb188-e536-4bb9-a5c0-db8bad90bd7b.png)

**Comment by Derpercoaster** [comment]
> Yes, I did the code change this morning and you can see the PR (pull request) linked on this issue. It'll be in the next release, though sadly we just did a release yesterday, so the next one is a month away at best, sorry! But once its merged to master you could always compile and run the master branch yourself, then you'd have that feature immediately.

I would probably use the PRs often if I could actually figure out how they work. I've never been able to.

**Comment by LeftofZen** [comment]
> I would probably use the PRs often if I could actually figure out how they work. I've never been able to.

I'm happy to explain how they work on discord if you'd like?

**Comment by Derpercoaster** [comment]
Sure thing.
