### ISSUE TITLE
Slow right-click scrolling

### ISSUE THREAD

**Issue by orffen** [OpenLoco/OpenLoco#1475]
**Version information:**
 - Platform: Windows 11
 - Version: 22.04
 - Build/commit: 01bc308

**Describe the bug**
Right-click scrolling is slow/laggy. Seems like there is some kind of acceleration being applied.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start OpenLoco
2. Start the Boulder Breakers scenario
3. Hold right-click and move the mouse

**Expected behaviour**
Right-click scrolling as per OpenTTD/OpenRCT2/vanilla Locomotion

**Comment by LeftofZen** [comment]
I am on Win 11 and I don't experience this behaviour. Does it happen on all scenarios? Does it happen in vanilla loco?

**Comment by orffen** [comment]
Doesn't happen in vanilla Locomotion. Does happen in all scenarios, and in windowed, borderless or fullscreen modes.

Looks to be linked to the frame limiter - when I disable the frame limiter, I get normal scrolling. With it enabled, I'm locked to 40 FPS and the scrolling is incredible slow at normal mouse speeds and ridiculously fast when exaggerating mouse movement.

**Comment by LeftofZen** [comment]
Ah yep turning off the frame unlimiter and its super laggy, that'll have to be fixed

**Comment by LeftofZen** [comment]
This is super weird, this *only* happens in release builds. In a debug build, the right-click scroll on frame-limited is normal. @duncanspumpkin any ideas?

**Comment by pnkrtz** [comment]
The "speed" of the scrolling depends oddly on my zoom level.

**Comment by AaronVanGeffen** [comment]
This is still happening on latest master, but only when 'uncap fps' is disabled.

@ZehMatt I believe you investigated this briefly. Did you find out anything at the time?

**Comment by ZehMatt** [comment]
I did briefly look into it but I don't think I've ever found the issue behind it, but panning with mouse under Release builds and Uncap FPS off is really terrible, I'm gonna go with a long shot and guess there is some undefined behavior here at least which would explain why it happens with release builds and not debug builds

**Comment by AaronVanGeffen** [comment]
Sounds likely. It might also be a compiler-specific issue, as I haven't been able to reproduce it on Linux (gcc nor clang). I just ran into it testing Windows builds through Wine on macOS.

**Comment by AaronVanGeffen** [comment]
Tried bisecting this using the Win32 releases. The regression seems to have been introduced between v22.02 and v22.03. The most prominent change introduced in v22.03 is the new OpenAL audio backend.

v20.05: fine (but not trapped in window)
v21.05: fine (and trapped in window)
v22.02: fine
v22.05: bad
v22.04: bad
v22.03: bad

@ZehMatt I don't have access to a Windows IDE setup or compiler. Could you help bisect between v22.02 and v22.03?

**Comment by ZehMatt** [comment]
Unfortunately bisect is a bit annoying due to the switch between cmake and preconfigured VS sln, I'll first try to see if I can figure this out and use that as the last resort before I spent a lot of time switching forth and back.
