### ISSUE TITLE
loaded train gets stuck on hill due to not enough power

### ISSUE THREAD

**Issue by NSTrains** [OpenLoco/OpenLoco#1504]
Platform: Windows 10 Home 21H2 
Version: 22.05
Build/commit: ?

Loaded trains keep stopping on a hill when it has not enough power

Steps to reproduce the behaviour:
1. Load any save game or scenario
2. Have a loaded train attempt to climb a hill with not enough power
3. The train will slow down to 5 mph (or 8.04 kph)
4. The train will stop on the hill and get stuck with no way of getting it un-stuck

Expected behaviour:
The train will still go up the hill but only 5 mph (or 8.04 kph) due to lack of enough power

Evidence:
Here is a link to YouTube that shows what the train is doing https://www.youtube.com/watch?v=1zkgwAKDWmY&ab_channel=NSTrains

I have had a steam engine do this before but I was able to remove it from the track on the original game.

**Comment by luk3ZPL** [comment]
Could you add a save game I'll try it ?
