### ISSUE TITLE
Mouse moves out of window when looking around.

### ISSUE THREAD

**Issue by Tommygun7468** [OpenLoco/OpenLoco#151]
When right-clicking to look around the map, the mouse will continue to move and go out of the game which results in the camera stopping to bring the mouse back into the game.

**Comment by AaronVanGeffen** [comment]
Which OS are you using?

**Comment by Tommygun7468** [comment]
Version 18.02

**Comment by AaronVanGeffen** [comment]
I meant the operating system you're using, and its version; not the version of the game. This is relevant, because the code path Windows uses for these things differs from Linux and macOS.

**Comment by Tommygun7468** [comment]
64bit, windows 10, version 1709

**Comment by cyberkitsune** [comment]
Also having this issue, Windows 10 64bit with multiple monitors.

**Comment by poland153** [comment]
I am experiencing the same issue while scrolling. Also on Win10x64 and dual monitors (playing game on left monitor, nothing open on right monitor).

I also have to note that while moving the view right does make the cursor leave the game, if I scroll left/up/down it will only move the view however much room is left on the screen for the cursor. If I remember correctly, in vanilla you could just right click move view forever without having to release and reset your cursor position.

**Comment by AaronVanGeffen** [comment]
Yes, the cursor is not locking into place properly. Currently, we rely on the original game's routines to do this. This will be eventually resolved when we have implemented the relevant routines in our C++ codebase.
