### ISSUE TITLE
No music in game

### ISSUE THREAD

**Issue by Xardoz** [OpenLoco/OpenLoco#1510]
**Version information:**
 - Platform: Windows 10 64bits
 - Version: 22.05.1 (but I tried too with previous versions)

I have music in the title screen, but every time I launch a scenario, in-game, I don't have music playing (and if I go to the sound options, I have what's on the screenshot 'screen1' attached). Even if I select one music, no music plays.

If I save, music suddenly starts and work normally (in the options, it becomes what's on 'screen2').
If I load a game, music starts normally. 

Screen 1 : 
![screen 1](https://user-images.githubusercontent.com/35117010/168929492-985e2f4a-b149-4b62-a509-e86d4d0c0032.jpg)

Screen 2 : 
![screen 2](https://user-images.githubusercontent.com/35117010/168929494-ac24f371-c9ab-4036-86dc-77c5ced89124.jpg)

**Comment by IntelOrca** [comment]
Caused by 6fe045b28a602a1b4e3134fc6bcf652993f2e9c7
