### ISSUE TITLE
force breakdowns on vehicles

### ISSUE THREAD

**Issue by NSTrains** [OpenLoco/OpenLoco#1519]
Able to force breakdowns on all vehicles, for trains you can force breakdown on one locomotive or multiple locomotives.

**Comment by LeftofZen** [comment]
I don't quite understand why you'd want this feature, or how it'd be presented in game. Is it supposed to be a cheat? A button on a vehicle window? For multi-loco trains there is no way to select an individual loco currently (that I know of), so how would the player select that loco to make it break down?

**Comment by NSTrains** [comment]
I just thought of it because OpenRCT2 has it as in the vehicle windows and maybe it could be the same on Openloco?

**Comment by AaronVanGeffen** [comment]
OpenRCT2 has it for ride hacking purposes. Aside from testing, I'm not sure what purpose it would serve in OpenLoco?

**Comment by NSTrains** [comment]
it not that useful, I don't know why I want it in here because its mostly useless.

**Comment by NSTrains** [comment]
If this is not needed I will close it
