### ISSUE TITLE
Garbled text in vehicle details

### ISSUE THREAD

**Issue by LeftofZen** [OpenLoco/OpenLoco#1522]
**Version information:**
 - Platform: win11
 - Version: latest master
 - Build/commit: 8cfd2f1acf3795af5b2c0edd3dcac762c3df3a68

**Describe the bug**
I'm getting garbled text for vehicle details. Happens even in vanilla maps. Doesn't happen all the time though, seems more common on trains. 

I couldn't replicate this on 22.05.1 but could replicate it on master. It's probably caused by #1501 

**To Reproduce**
1. Load a save
2. Open vehicle details for a train
3. See if text corrupted

**Expected behaviour**
Normal text rendering

**Screenshots**
![image](https://user-images.githubusercontent.com/7483209/170393148-821e9964-73ce-4e11-aa17-7ee3249e53be.png)

**Additional context**
Seems to happen 100% of the time on this save, though it does have custom objects.
[a_megapark_original.zip](https://github.com/OpenLoco/OpenLoco/files/8775459/a_megapark_original.zip)

**Comment by AaronVanGeffen** [comment]
I can't reproduce this on Linux. Has this been addressed since?
