### ISSUE TITLE
HighSpeed assets crash the game

### ISSUE THREAD

**Issue by Trombone2015** [OpenLoco/OpenLoco#1523]
- Platform: Windows 11
 - Version: 22.05.1

OpenLoco crashes while selecting a vehicle during scenario editor.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://www.locomotiondepot.net/amitrains/locotrains
2. Click on LocoTrains High Speed Pack Reloaded (1.0)
3. Download the file and export it to downloads. 
4. Cope the .DAT files from the download folder to the ObjData folder in the Locomtion folder. 
5. Start OpenLoco and create a new scenario in scenario editor. 
6. Create a random landscape and go to object selection. 
7. Try to select "HighSpeed 'TGV' etc. The game will crash. 

**Expected behaviour**
OpenLoco will produces an error message once you hover over one of the HighSpeed trains in the vehicles tab. 

**Additional context**
Save file:
[1b8bc55b-0a91-4b2b-950b-caf337e4cf56(OpenLoco, v22.05.1 (914ac6c on master)).zip](https://github.com/OpenLoco/OpenLoco/files/8775456/1b8bc55b-0a91-4b2b-950b-caf337e4cf56.OpenLoco.v22.05.1.914ac6c.on.master.zip)

**Comment by Sebazzz** [comment]
The crash doesn't happen anymore as of.

However this is logged to the console, which might be the original cause of the crash:

```
OpenLoco, v24.04-17 (b1293bd6 on supplement-nl-translations)
Object index out of date.
Object has too few images for body sprites!
Tick interrupted
Object has too few images for body sprites!
Object has too few images for body sprites!
Object has too few images for body sprites!
Object has too few images for body sprites!
Object has too few images for body sprites!
Object has too few images for body sprites!
```
