### ISSUE TITLE
Terrain painting off the map crashes the game

### ISSUE THREAD

**Issue by LeftofZen** [OpenLoco/OpenLoco#1536]
**Version information:**
 - Platform: Windows 11
 - Version: e.g. 22.05.1
 - Build/commit: on 22.05.1 release, also latest master

**Describe the bug**
Game crash when painting terrain off the map

**To Reproduce**
Steps to reproduce the behaviour:
1. Open any map
2. Open Land tool
3. Put tool into paint mode
4. Select any size for the tool that is > 1 tile
5. Attempt to paint land on the edge of the map with the paint tool partially off the map.
6. Crash.

**Expected behaviour**
No crash, ie same behaviour as regular non-paint land tool 

**Screenshots**
Clicking to paint terrain here will cause the issue
![image](https://user-images.githubusercontent.com/7483209/173191111-102b1a10-9805-415e-92fb-5d4b08ea093a.png)

**Additional context**
Caused by #1435 by me (@LeftofZen). I assume that before that change, the call to changeLandMaterial came after the bounds check performed by the normal land tool. When the method is called on it's own, presumably that bounds check is now accidentally skipped, resulting in the crash.

In release build the game crashes in ChangeLandMaterial.cpp::changeLandMaterial, in the for loop iterator.
In debug build, the game terminates with a 'loco_global bounds check' failure.

Unfortunately neither `lowerLand` or `raiseLand` game commands are reverse-engineered, and those commands are what calculate when the selection rectangle is out of map bounds.

**Comment by AaronVanGeffen** [comment]
This has been resolved in the mean time.
