### ISSUE TITLE
Not building on MacOS Monterey 12.4

### ISSUE THREAD

**Issue by dspacejs** [OpenLoco/OpenLoco#1538]
**Version information:**
 - Platform: MacOS
 - Version: 12.4
 - Build/commit: 55d11136aebdb70545cc822c44801d79df20c17b

**Describe the bug**
I can't build the game. I'm getting complier errors:

```
$ cmake .. "-DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x86-osx
-- Could NOT find CCache (missing: CCache_EXECUTABLE)
-- Unsupported CXXFLAG: -Wno-clobbered
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_TOOLCHAIN_FILE


-- Build files have been written to: /Users/daniel/Documents/Dev/sandbox/OpenLoco/build
```

It's generated the openloco.app, however it's only 1KB and doesn't run.

**To Reproduce**
I'm not sure how to reproduce this.

**Expected behaviour**
The game to build successfully.

**Comment by AaronVanGeffen** [comment]
Unfortunately, this is unsurprising. In the project's current state, we can only build 32-bit binaries. Therefore, any macOS version after 10.14 is currently not supported.

We aim to introduce 64-bit support as soon as we no longer rely on the original, 32-bit (Intel x86) binary.

**Comment by dspacejs** [comment]
@AaronVanGeffen oh right, thanks for the clarification.

What's the ETA on when I can expect this to work on my machine? I don't have any other devices at home right now I can play the game on.

**Comment by AaronVanGeffen** [comment]
I can't give you an ETA; we simply still have loads of reimplementing to do. However, you can probably already play the game if you use CrossOver (Wine) to run the Windows version of OpenLoco through Rosetta.

**Comment by dspacejs** [comment]
@AaronVanGeffen I can't seem to get the original GOG installer working with CrossOver.

It runs the game's installer and it says it's installed successfully. However, the CrossOver installer gets stuck during this installation process. 

Have you had any success with this? Thanks.

**Comment by janisozaur** [comment]
Don't install it - use `innoextract` to extract the assets. You can get some more info here: https://github.com/OpenRCT2/OpenRCT2/wiki/Installation-on-Linux-and-macOS
