### ISSUE TITLE
Date on bottom right changes to misssing string id: 2237

### ISSUE THREAD

**Issue by LordMaurits** [OpenLoco/OpenLoco#1541]
**Version information:**
 - Platform: Windows 10
 - Version:Release v22.05.1

**Describe the bug**
Instead of date in bottom left it shows "(misssing string id: 2237". Also in the terminal of openloco "formatString: nullptr for string id: 2237" is continuesly printed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start any game (from before or from the release of v22.05.1)

The correct date is shown in the original game.

**Screenshots**
![OpenLoco 14_06_2022 22_40_08](https://user-images.githubusercontent.com/107511954/173684796-0401f102-c520-4706-afaa-9da5013585c7.png)

**Comment by duncanspumpkin** [comment]
This happens if you have installed the game incorrectly. You need to have the localisation files for the specific version you have installed.

**Comment by duncanspumpkin** [comment]
There will have been a localisation folder in the zip that is meant to replace your current localisation folder

**Comment by LordMaurits** [comment]
Ah okay thanks for all your help, I will look into it.

Op wo 15 jun. 2022 om 08:19 schreef Duncan ***@***.***>:
