### ISSUE TITLE
Vehicle Count

### ISSUE THREAD

**Issue by glenjimen** [OpenLoco/OpenLoco#1542]
**Describe the solution you'd like**
During the reimplementation of this game, a train's detail windows has been modified to show the maximum cargo that train can carry.  I think it would be helpful to also show a counter of the total number of vehicles in a train, especially considering that only about 17 vehicles can be displayed in a window before you need to scroll down to see the rest.   A counter for both locomotives and rolling stock would be most helpful to the player.

Copied from Discord:
I really like how the cargo capacity is displayed in a train's detail page.  Extra information like this is helpful and can indicate the number of cars in your consist.  Would it be possible to also add a car count?  I tend to run lots of unit trains like this, and train length is important for it to fit in a station.  This train is only 13 cars, longer trains cannot even be displayed in the window, so a simple car count would be very helpful.  
I feel like this is something that could be added without too much hassle.  The max cargo capacity is already there, which requires a car-count variable.  An improvement would be to have two counters, number of cars & number of locomotives.  I guess you would differentiate by looking at how much horsepower a vehicle has.  But just the total vehicle count would help me very much.

**Describe alternatives you've considered**
The old way to figure out train lengths is to scroll thru the window and manually count the locos and cars.  You can also place the train, then count the cars, or compare it's length to something on the map.  This is slow and accident prone.

**Comment by LeftofZen** [comment]
Should be straightforward copy-paste from #1306

**Comment by LeftofZen** [comment]
Thoughts?
This one belonged in the vehicle details window, not the cargo window.
It currently prints a value even for things like planes and ships which is always 1, so I might handle that a bit better and only draw the value if it's > 1

**Comment by auge8472** [comment]
Maybe it's to late to consider, maybe an issue on it's own. Anyway. Beside the number of vehicles in a consist it would be helpful to know the ***tile** length* of a train. This, because a train, that is longer than the station(s) will need much longer for loading and unloading than a train, that does not exceed the station length.

**Comment by LeftofZen** [comment]
I can agree with that, this would aid with gameplay, I'll see that I can do but no promises
