### ISSUE TITLE
wont load at all

### ISSUE THREAD

**Issue by Hotmagmashot** [OpenLoco/OpenLoco#1544]
**Version information:**
 - Platform: [e.g. Windows 10]
 - Version: [e.g. 22.05.1]
 - Build/commit: [e.g. f08479f]

**Describe the bug**
Every time i go to start the game up it does a save dump and admin roaming

**Expected behaviour**
To start up with no issues

**Additional context**
Keeps doing a save dump and im very unsure of why i do have mods however

**Comment by LeftofZen** [comment]
Without telling us any information about what version you're on, what OS, what custom objects you have, etc, it is hard for us to figure out what issue you're having.

Can you fill in the version information properly, try starting OpenLoco on the latest 22.05.1, and and also try removing all your custom objs?

**Comment by Hotmagmashot** [comment]
I definitely could try but i have the latest version could i have
downloaded too many mods?

**Comment by LeftofZen** [comment]
It's not a question of too many, just that perhaps there is an obj that is corrupted and the game can't load it. I'd recommend trying to run the game with a clean install and no custom objs. If that works then we know its probably the objs, and if it doesn't work we know it's something more fundamental. Can you at least tell us what OS you're using?

**Comment by Hotmagmashot** [comment]
windows
