### ISSUE TITLE
Larger stations

### ISSUE THREAD

**Issue by nicklitey** [OpenLoco/OpenLoco#1546]
I've been playing heavily modded loco since the early 2010s, and one patch that I've always had trouble getting working is the larger stations patch, or "community patch 0.2.1". Is this a patch possible to be applied to openloco, or is a larger station limit a feature we could see implemented?

**Comment by AaronVanGeffen** [comment]
This is a request we get quite often, tracked in #358. Unfortunately, the old 'long station patch' is not compatible at this point. We aim to tackle requests like these with a new save format after our C++ implementation has reached completion.
