### ISSUE TITLE
Add [[nodiscard]] to ImageId struct

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenLoco/OpenLoco#1547]
https://github.com/OpenLoco/OpenLoco/blob/b60f1e5c68089aff891195ee8412e25697e7cbe4/src/OpenLoco/Graphics/ImageId.h#L18

Should add a [[nodiscard]] to almost everything in ImageId. Discarding the result has already been the source of one bug in OpenRCT2.

**Comment by IntelOrca** [comment]
This is one of those things where you want `nodiscard` to be the default and only to specify where it is discardable...

**Comment by duncanspumpkin** [comment]
> This is one of those things where you want `nodiscard` to be the default and only to specify where it is discardable...

Yup at least in c++23 you can constexpr everything in one go. Maybe one day that will apply to attributes.
