### ISSUE TITLE
Spanish lenguage is actually "Spanglish" (Some texts are in english)

### ISSUE THREAD

**Issue by md500** [OpenLoco/OpenLoco#1549]
**Version information:**
 - Platform: Windows 10 Enterprise 1809
 - Version:  v22.05.1
 - Build/commit: 914ac6c

**Describe the bug**
When i set the game to my native language to Spanish, some texts are in English (Spanglish). Happens also with campaing descriptions and elements to transport (ej. "Necesita Iron Ore y Coal para producir Steel" instead of "Necesita Mineral de Hierro y Carbón para producir Acero" ). Also happens with some notices.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the game.
2. Set the game to Spanish.
3. Open Campaings and set any campaing.
4. Open Industries.
5. Wait a time to spawn Notices issue about Production Down.

**Expected behaviour**
Complete Spanish like as OpenRCT2

**Screenshots**
Complete Spanish from Original Game:
![Complete Spanish](https://user-images.githubusercontent.com/3111925/175458401-99520f4a-a1fc-44e9-bada-15c06527e91c.jpg)

Openloco With Spanglish:

![Spanglish](https://user-images.githubusercontent.com/3111925/175458526-56bafd4b-044c-4035-ad39-33c12fe46fe3.jpg)

**Additional context**
Can i send the LOCO.exe Spanish file to help with the translation? Seems that GOG and Steam doesnt have Spanish Language and only in original game, which seems hard to find it.

**Comment by LeftofZen** [comment]
We have a set of language files, including Spanish, here:
https://github.com/OpenLoco/OpenLoco/blob/master/data/language/es-ES.yml

As we (the developers) mostly speak English, only the English language file (en-GB.yml) gets updated regularly. When the game is trying to draw text on the screen it looks for a "string id" in the language file, which is the number associated with each line of text in these language files. If the game cannot find that number in the current language file it will default to the English version, which is why you are seeing mixed English and Spanish.

I'm not sure what you mean by the `loco.exe spanish file`? But I thin kthe best way to contribute would be to add to the Spanish translation file that I linked above and submit a pull request with your changes. You'd have to search for string ids in the English file that are not in the Spanish file, and add them to it. I can write a script to help find the missing lines from the Spanish (and other language files) if that helps?

**Comment by md500** [comment]
![Screenshot_20220625-020335056](https://user-images.githubusercontent.com/3111925/175760769-3615a6e8-1ce3-45f8-b1d6-7143ecfd789c.jpg)
It can be helpful about the script. Tried searching any English string in es-ES.yml (to find missing translated) and can't find it miserably....

**Comment by AaronVanGeffen** [comment]
At the moment, the Spanish localisation file is unmaintained. This means it contains 2130 language strings out of the the 2258 strings used by the game. In other words, 128 strings are missing, and will fall back to using the English string instead.

If you would like to contribute to translating these, you can copy the missing strings from [en-GB.yml](https://github.com/OpenLoco/OpenLoco/blob/master/data/language/en-GB.yml) and add them to [es-ES.yml](https://github.com/OpenLoco/OpenLoco/blob/master/data/language/es-ES.yml) to translate.

**Comment by duncanspumpkin** [comment]
This actually looks like an object loading bug. The objects aren't loading the localised text.

**Comment by LeftofZen** [comment]
Despite the object loading bug, there is still a real issue that the other language files are unmaintained, so I did make that little script that displays differences between `en-Gb.yml` and the other files. Script is here: https://github.com/OpenLoco/decompilation-tools/tree/master/Tools/LanguageFileAnalyser

You can run it yourself, or here is the output from my run this morning:
[output.txt](https://github.com/OpenLoco/OpenLoco/files/8987889/output.txt)

**Comment by duncanspumpkin** [comment]
Would I be correct in saying the original game didn't allow changing languages except on install? @IntelOrca do you know more about this? I went and looked at the object code and it always loads the english US localisation in OpenLoco but it looks to be hardcoded.

**Comment by AaronVanGeffen** [comment]
> Would I be correct in saying the original game didn't allow changing languages except on install?

You are correct. Like RCT2, all strings were hardcoded in the .exe file, except for those in object string tables. We haven't implemented the latter yet, though.

**Comment by duncanspumpkin** [comment]
> > Would I be correct in saying the original game didn't allow changing languages except on install?
> 
> You are correct. Like RCT2, all strings were hardcoded in the .exe file, except for those in object string tables. We haven't implemented overrides for the latter yet, though.
> 
> > I went and looked at the object code and it always loads the english US localisation in OpenLoco but it looks to be hardcoded.
> 
> With the object loading implemented, we can now at least use the right string keys from the object string tables, when available, I suppose.

Object loading is still not implemented. It's not far off though and it would be easy enough to hook.
