### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by skyace65** [OpenLoco/OpenLoco#1553]
**Version information:**
 - Platform: Windows 10 (Build 19044)
 - Version: 22.06
 - Build/commit: 5eac98c

**Describe the bug**
OpenLoco is crashing on startup

**To Reproduce**
Steps to reproduce the behaviour:
1. Run OpenLoco.exe
2. select the install path if this is the first time running it

**Expected behaviour**
Open Loco should start normally

**Additional context**
I tried deleting the appdata folder for OpenLoco after the first crash, it's still happening after regenerating the folder.

**Comment by AaronVanGeffen** [comment]
This will be addressed by #1552
