### ISSUE TITLE
Failed to load save game (not duplicate to #1561)

### ISSUE THREAD

**Issue by NSTrains** [OpenLoco/OpenLoco#1562]
**Version information:**
 - Platform: Windows 10
 - Version: 22.06.1
 - Build/commit: adb6f6c

**Describe the bug**
when I try to play a save game, openloco says an object is missing, but I have the object in the correct folder. The vanilla game loads the save game fine without problems.

**To Reproduce**
Steps to reproduce the behaviour:
1.Start OpenLoco
2. Try to play any save game that has 'FLIPPER2' or 'Engine Flipper Diesel Sound'
3. OpenLoco will say missing object 'FLIPPER2'

**Expected behaviour**
The save game will load without problems

Here is the save game im trying to open. I don't know if it auto included the files for the save game, I know I have tried it before and it didn't include the files. So maybe a bug?
[The Industry River.zip](https://github.com/OpenLoco/OpenLoco/files/9059136/The.Industry.River.zip)

**Comment by duncanspumpkin** [comment]
`FLIPPER2` has been incorrectly created. Invalid cost_index value has been used which would cause invalid memory access. In addition `0xFFFF` (-1) has been used as the speed but max speed is `0x7FFF` this causes another validation failure. This second failure could be corrected but would lead to more messy code.

**Comment by duncanspumpkin** [comment]
In the future we could fix the object on load but need to implement the load code and adjust the object packing code.

**Comment by NSTrains** [comment]
you asked for the missing mods on discord, here the are
https://www.tt-forums.net/download/file.php?id=20579
[SNDRS3L1.zip](https://github.com/OpenLoco/OpenLoco/files/9127709/SNDRS3L1.zip)
1

**Comment by NSTrains** [comment]
issue fixed
