### ISSUE TITLE
Crash after updating, and right click scrolling is broken

### ISSUE THREAD

**Issue by OfficialMaxBox** [OpenLoco/OpenLoco#1581]
Hi there, I just updated OpenLoco for my once-in-a-blue-moon play, and I got a few months into Boulder Breakers when the game crashed. Additionally, the camera while holding right-click barely moves and requires a fast movement of the mouse to get it to move even a little. If needed, I can record a short clip showing its behavior. 

As I was only a few months in, there is no saved game, but attached in the zip file are the dump file and a screenshot of the game just before it crashed. I had just bought some flatbed wagons for a new train. 

Version: v22.06.1, (adb6f6c on master)
[OpenLoco Crash and SS.zip](https://github.com/OpenLoco/OpenLoco/files/9204356/OpenLoco.Crash.and.SS.zip)

**Comment by AaronVanGeffen** [comment]
Slow right-click scrolling has previously been reported in #1475. Appears to only happen in release builds, oddly enough.

**Comment by AaronVanGeffen** [comment]
Closing this, as #1475 has been solved since.
