### ISSUE TITLE
MacOS 10.13.6 "OpenLoco has quit unexpectedly"

### ISSUE THREAD

**Issue by NSTrains** [OpenLoco/OpenLoco#1585]
**Version information:**
 - Platform: MacOS 10.13.6
 - Version: 22.06.1
 - Build/commit: f08479f

**Describe the bug**
On MacOS 10.13 High Sierra, when I try to run the app it says it quit unexpectedly.

**To Reproduce**
Steps to reproduce the behaviour:
1. You need to have both the original game and OpenLoco installed
2. With both installed, try to run OpenLoco
3. You will get an error saying that OpenLoco quit unexpectedly.

**Expected behaviour**
OpenLoco will run fine and will work like its on windows 10 or 11

I have never done this before and saw an issue about it before.

**Comment by AaronVanGeffen** [comment]
Unfortunately, this sounds like #1556. Not sure how to fix it yet. You could try an earlier version of OpenLoco, but we're not quite sure how far back this goes yet.
