### ISSUE TITLE
Windows 11 21H2 + Steam: Openloco crashes in ship build menu when moving with mouse

### ISSUE THREAD

**Issue by olfsch123** [OpenLoco/OpenLoco#1587]
**Version information:**
 - Platform: Win 11
 - Version: 21H2
 - Build/commit: Locomotion installed with Steam

**Describe the bug**
When i open the build menu -> ships and i move fast over all available ships, the whole game crashes.

**To Reproduce**
Open build ships, move fast over alle ships with your mouse

**Comment by janisozaur** [comment]
You haven't provided commit for this issue.

Our Windows builds come with breakpad, please submit crash dump.

**Comment by duncanspumpkin** [comment]
I think this will be the multiline bug. Try the 22.05 release

**Comment by olfsch123** [comment]
With 22.05 it works.

I don't know hot to use breakpad and what you mean with commit :-)

**Comment by janisozaur** [comment]
> I don't know hot to use breakpad

Just have the game crash and submit the dump it produces

> what you mean with commit

Which version of OpenLoco is problematic, out of those: https://github.com/OpenLoco/OpenLoco/commits/master

**Comment by AaronVanGeffen** [comment]
> With 22.05 it works.

Then it's probably the issue Duncan was thinking of. Could you try a dev/master build? You can find them in the Checks tab on the GitHub project page.
