### ISSUE TITLE
Feature request: Autosave

### ISSUE THREAD

**Issue by hemmofa** [OpenLoco/OpenLoco#159]
First of all: I was delighted to see this appear on the OpenRCT2 github after I wanted to check up on that project.

While the game is still in development, an autosave function would be really great.
For me, this means I can play this old gem a lot and don't lose too much stuff if/when it crashes.

**Comment by janisozaur** [comment]
There's already autosave implemented and most likely on by default.

**Comment by janisozaur** [comment]
Loops, my bad, I thought it was our other project.

**Comment by AaronVanGeffen** [comment]
Implemented in #690
