### ISSUE TITLE
game freezes on last day of month

### ISSUE THREAD

**Issue by NSTrains** [OpenLoco/OpenLoco#1595]
**Version information:**
 - Platform: Windows 10
 - Version: 22.06.1
 - Build/commit: adb6f6c

**Describe the bug**
on the last day of every month, the game decides to freeze with nothing on the cmd console.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start OpenLoco'
2. Load and scenario or save game
3. Wait until the last day of the month
4. The game will freeze on the last day of month

**Expected behaviour**
The game will continue to run without freezing

So far I have only played with one save game and it has happened 2 times
https://transfer.sh/FthFgB/openloco.DMP

**Comment by janisozaur** [comment]
Version: 22.06.1
Build/commit: https://github.com/OpenLoco/OpenLoco/commit/f08479fb84b5ad950b8c1389ab4dee216854a508

These are two very different versions. One is a latest release about two months old, the other one is over four months old. Can you verify which one is it?

**Comment by NSTrains** [comment]
adb6f6c

**Comment by NSTrains** [comment]
also could it be that I have 2 openloco folders?

**Comment by NSTrains** [comment]
now I can't seem to reproduce the issue

**Comment by NSTrains** [comment]
so my game is freezing at the end of every month, and the autosave is set to every month. So theres something wrong with the autosave function

**Comment by NSTrains** [comment]
problem solved, it was OpenLauncher that was causing the freezing issue
