### ISSUE TITLE
Ability to see Character Limit When Typing

### ISSUE THREAD

**Issue by Derpercoaster** [OpenLoco/OpenLoco#1608]
**Describe the solution you'd like**
Every typing interface in the game has a built-in character limit, but this limit is not displayed anywhere. There should be a character limit under any typing bar so you know how much space you have left. This would be especially useful in the scenario editor when typing the sceenario description.

**Additional context**
i'd provide edited screenshots to show what I mean, but I can't think of how to make one with the tools I have.

**Comment by AaronVanGeffen** [comment]
This has since been implemented.
