### ISSUE TITLE
Opening the narrow gauge Build Trains window freezes the game

### ISSUE THREAD

**Issue by strongbowe1** [OpenLoco/OpenLoco#1613]
Windows 10
OpenLoco 22.08

Going to the narrow gauge Build trains window always freezes the game.

To reproduce, open the Build Trains menu, go to narrow gauge tab, game freezes.

Attached screenshot of the last thing I see when the game freezes.
![Untitled-1](https://user-images.githubusercontent.com/37986589/186847510-35b5a28b-9cca-4c58-a09f-4e2300152c2a.png)

And the crashdump.
[678906a4-0fee-4a1c-a738-e6f93cdaf582(OpenLoco, v22.08 (614515c on master)).zip](https://github.com/OpenLoco/OpenLoco/files/9430754/678906a4-0fee-4a1c-a738-e6f93cdaf582.OpenLoco.v22.08.614515c.on.master.zip)

**Comment by duncanspumpkin** [comment]
Note you need the show disabled trains cheat enabled. Its crashing in `drawStringLeftWrapped`

**Comment by duncanspumpkin** [comment]
Seems the buffer used for `drawStringLeftWrapped` is too short.

**Comment by strongbowe1** [comment]
It's crashing regardless of whether the locked trains cheat is enabled, as well as being able to build locked vehicles. Always same outcome on my system.

**Comment by duncanspumpkin** [comment]
Yes sorry I worked that out as well. Issue is caused by trains with lots of details in the details window I just didn't have any except in trains which were disabled.
