### ISSUE TITLE
"Exception: Bad vehicle structure"

### ISSUE THREAD

**Issue by DragonlordK1ng** [OpenLoco/OpenLoco#1614]
**Version information:**
 - Platform: Win10
 - Version: 22.08
 - Build/commit: f08479f

**Describe the bug**
The game froze for a few seconds to then get a popup reading "Exception: Bad vehicle structure" When I closed the popup, the game crashed

I'm attaching a screenshot, the crash dump and the autosave generated right before the popup showed up.

![unknown](https://user-images.githubusercontent.com/85203567/187012404-8d8950f2-9b3b-4ec7-9c98-d0a6d6b13c37.png)

https://www.mediafire.com/file/mbqub1isoq4yi1q/crashinfo.rar

**Comment by LeftofZen** [comment]
I can't repro this on my PC at all, running Win11.

On the minidump, I get this stack frame exception
![image](https://user-images.githubusercontent.com/7483209/187013167-87fdb2f6-3d7d-46ca-b4a3-2f8165d7c740.png)
