### ISSUE TITLE
Crash when hovering over Merchant Ship and Cargo Ship in the buy menu

### ISSUE THREAD

**Issue by Drury27** [OpenLoco/OpenLoco#1619]
**Version information:**
 - Platform: Windows 10
 - Version: 22.08
 - Build/commit: 614515c

**Describe the bug**
Consistently reproducible on any fresh map, absent in 22.06.

[aa11e8c2-f894-40a5-92a3-966d2f7ba5cf(OpenLoco, v22.08 (614515c on master)).zip](https://github.com/OpenLoco/OpenLoco/files/9440867/aa11e8c2-f894-40a5-92a3-966d2f7ba5cf.OpenLoco.v22.08.614515c.on.master.zip)

**Comment by LeftofZen** [comment]
confirmed, crashes on 22.08 but works on 22.06.1

**Comment by LeftofZen** [comment]
crashes in drawStringLeftWrapped, I think the faulty PR is this
https://github.com/OpenLoco/OpenLoco/pull/1566

**Comment by LeftofZen** [comment]
something is corrupting the stack after [this line](https://github.com/OpenLoco/OpenLoco/blob/3db793e44c96d8f072439b34e17d2948dc205e8d/src/OpenLoco/Window.cpp#L1398), I don't really know how to debug these things so will probably need your help @duncanspumpkin

**Comment by duncanspumpkin** [comment]
Did you check master it sounds like https://github.com/OpenLoco/OpenLoco/issues/1613

**Comment by LeftofZen** [comment]
Annoying I was on a branch from about 3 days ago, and that fix was committed 2 days ago :| I tried master and it appears fixed

**Comment by Shaggygoblin** [comment]
similar problem, actually identical, lead me here.
open an included scenario, open build ships, mouse over any area in that window and freeze.

interestingly, custom scenario, start year 1885(?) clipper only and am able to play through till everything else unlocks with time.
fwiw.

**Comment by LeftofZen** [comment]
It's already been fixed in master, so the next release, probably 22.09 will contain the fix. For now I recommend just sticking on 22.06.1 if it's really causing issues.

**Comment by Shaggygoblin** [comment]
i was including that bit of info for consideration:
starting year pre-1900 (1885) and playing through has no crash, but starting at later years where there's the clipper a tanker and cargo ship in the list it crashes.
small details like that can sometimes be helpful.

Looking forward to future releases!
