### ISSUE TITLE
Crash when i want to place a train

### ISSUE THREAD

**Issue by MrConner1** [OpenLoco/OpenLoco#1622]
**Version information:**
 - Platform: Windows 10
 - Version: [e.g. 22.08 Latest

**Describe the bug**
I start the game and i want to buy an train then openloco crashes the only thing i installed extra in locomtion are the dutch trains from christrains you can them find here: https://christrains.com/downloads/christrains_for_locomotion_v1.5.exe 

a crash has occured and a dump was created at 
[ea0c1daa-ac6b-4439-bdcf-91f88146e8ac(OpenLoco, v22.08 (614515c on master)).dmp.zip](https://github.com/OpenLoco/OpenLoco/files/9482475/ea0c1daa-ac6b-4439-bdcf-91f88146e8ac.OpenLoco.v22.08.614515c.on.master.dmp.zip)
[autosave_2022-09-03_13-26-02.zip](https://github.com/OpenLoco/OpenLoco/files/9482476/autosave_2022-09-03_13-26-02.zip)
![example](https://user-images.githubusercontent.com/112759508/188268934-13d0595f-958a-4fc0-b3d9-d3078c90ff9b.jpg)

**Comment by LeftofZen** [comment]
Do you get the same error on version 22.06.1?

**Comment by MrConner1** [comment]
I will try

**Comment by MrConner1** [comment]
I have treid it, it seems to work no crash with the previous version 22.06.1,

**Comment by LeftofZen** [comment]
Ok great, I am pretty sure this is an issue with drawing text that we've found in 22.08 and many other users have found as well. I'd recommend staying on 22.06.1 until we release 22.09 (hopefully soon), which will fix the issue for good.

**Comment by MrConner1** [comment]
Ok thanks :)

**Comment by duncanspumpkin** [comment]
Can you now try again in 22.09

**Comment by MrConner1** [comment]
I tried it out, Game crash at startup
[368e7510-05de-4405-a7f5-ca5ec7d36b25(OpenLoco, v22.09 (00b883a on master)).dmp.zip](https://github.com/OpenLoco/OpenLoco/files/9484412/368e7510-05de-4405-a7f5-ca5ec7d36b25.OpenLoco.v22.09.00b883a.on.master.dmp.zip)

**Comment by LeftofZen** [comment]
Strange you need admin rights since you shouldn't need them, but maybe there's something funky going on in your install where some files are marked as admin only.

**Comment by MrConner1** [comment]
But further no problem, Playing now at the moment already for 2 hours without one glitch. Super !
