### ISSUE TITLE
Owner Name on new game crashes in some case

### ISSUE THREAD

**Issue by superchadST345** [OpenLoco/OpenLoco#1649]
**Version information:**
 - Platform: Windows 10
 - Version: 22.09

**Describe the bug**
When starting a new game, in some cases a first name last name with a space can crash the game. what is odd is this doesn't always happen, if you leave the default unamed and add random charachters it works fine

and when changing the name later it also works fine.

**To Reproduce**
Steps to reproduce the behaviour:
1. start a new game
2. type in a firstname name with 8 charachters (qwertyui)
3. type in a space
4. type in a last name with 6 charachters (asdfgh)
5. click ok

**Expected behaviour**
The game should set that as the owner name

**Comment by LeftofZen** [comment]
Recently (in the last week!) the change owner name command has been implemented and many crashes associated with the owner name (and strings in general) have been fixed, with more PRs open. Would you be able to test this out on latest master? I would bet it's been fixed already, it just hasn't been released (will be in 22.10)
