### ISSUE TITLE
Acquire all company assets cheat causes some acquired Trains and Trams to crash

### ISSUE THREAD

**Issue by superchadST345** [OpenLoco/OpenLoco#1650]
**Version information:**
 - Platform: Windows 10
 - Version: 22.09

**Describe the bug**
When using the cheat "acquire company assets" will cause some of the acquired trains and trams to crash

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to cheats
2. Click on company cheats
3. Scroll down to desired company
4. click acquire all company assets
5. some of the trains and trams acquired will suddenly crash

**Expected behaviour**
All tracks, buildings, and vehicles should be aquired in there current status

**Comment by LeftofZen** [comment]
Probably (but not certainly) related to #1248

**Comment by superchadST345** [comment]
It appears that when you acquire all company assets it acquires ALL track of ALL companies, thus why the trains and trams crash, they are suddenly on another companies track, if you acquire one of those companies then you get all of it's crashed trains.

Trucks, Busses, Road stations, and Airports are not affected, unsure about ports, and unsure what would happen if a airport and train station shared the same station, would it split the station, acquire the airport as well, or crash the game.

**Comment by superchadST345** [comment]
This is a short example of what I am proposing to fix the issue, i do not know if roadElement.owner and trackElement.owner are valid, but we should check to make sure that the road and track elements actually belong to the target company to avoid accidently acquiring all elements


`// First phase: change ownership of all tile elements that currently belong to the target company.
            for (auto& element : TileManager::getElements())
            {
                auto* roadElement = element.as<RoadElement>();
                if (roadElement != nullptr)
                {
                    if (roadElement.owner != targetCompanyId)
                        continue;

                    roadElement->setOwner(ourCompanyId);
                    
                    continue;
                }

                auto* trackElement = element.as<TrackElement>();
                if (trackElement != nullptr)
                {
                    if (trackElement.owner != targetCompanyId)
                        continue;
                    
                    trackElement->setOwner(ourCompanyId);
                    continue;
                }
            }`

**Comment by LeftofZen** [comment]
Nice find, this sounds reasonable to me at a glance and without having seen the code. Feel free to make a PR for it!

**Comment by duncanspumpkin** [comment]
Yes you are quite right it isn't checking the owner.

**Comment by superchadST345** [comment]
i just don't know for sure if trackElement.owner is valid

**Comment by duncanspumpkin** [comment]
> i just don't know for sure if trackElement.owner is valid

Yes it is. All track elements and road elements have an owner. Road elements can have a neutral owner as well but it doesn't matter for this.
