### ISSUE TITLE
Industry Production Status

### ISSUE THREAD

**Issue by glenjimen** [OpenLoco/OpenLoco#1652]
**Describe the solution you'd like**
The Industry overview window shows three columns: Name, Status & % Transported.  When planning routes, one of the main deciding factors I use is the Last Month's Production.  Can this value be added to the Industry Overview window, in a fourth column?  

Ideally, when you sort the window by Status, as it is in the screenshot, the secondary sort criteria would be this new "Previous Month's Production" column in descending order, instead of now where it uses the Industry name in alphabetical order.

**Describe alternatives you've considered**
None

**Additional context**
![loco-industry-status](https://user-images.githubusercontent.com/51429904/192073788-48d3880d-2265-482d-ac53-0bae7a233e0e.png)

**Comment by LeftofZen** [comment]
Sounds like a nice feature to me
