### ISSUE TITLE
drawpixelinfo/dpi naming is confusing

### ISSUE THREAD

**Issue by marijnvdwerf** [OpenLoco/OpenLoco#166]
`drawpixelinfo_t` is the class used for wrapping a pointer to a pixelbuffer together with a width and height, and as such is mostly used in rendering. Unfortunately, it gets abbreviated to `dpi`, which is more commonly used for referring to 'dots per inch', or pixel density.

Having the 'dpi' stuff in our codebase – especially in the graphical part – is inconvenient and non-helpful naming.

What about using something like 'canvas' or 'bitmap'?

**Comment by AaronVanGeffen** [comment]
Renaming it to 'canvas' sounds good to me.

**Comment by marijnvdwerf** [comment]
‘Surface’ might be an appropriate term as well

**Comment by AaronVanGeffen** [comment]
We already use 'surface' to refer to ground tiles, though.

**Comment by IntelOrca** [comment]
I think `Camera` is the name used in TT.

**Comment by ZehMatt** [comment]
What about RenderTarget?

**Comment by marijnvdwerf** [comment]
`Camera` sounds it would be more appropriate as a replacement for the viewport or viewport configuration structs.

As for RenderTarget, I can't think of objections, but if somehow feels more... technical? 

If we look into web development, 'canvas' and 'context' are the terms used. Android uses `canvas` to pass around to drawing code. iOS uses a context, which isn't passed around, but `you can get a reference to the graphics context using the UIGraphicsGetCurrentContext() function`.

So familiarity-wise, either context or canvas get my vote.

**Comment by AaronVanGeffen** [comment]
Perhaps now would be a good time to pick up this discussion again?

**Comment by IntelOrca** [comment]
My preference is, GraphicsContext,

```c++
drawStuff(GraphicsContext& g)
{
    g.drawBox(x, y, width, height);
    g.drawImage(img, x, y);
}
```

**Comment by ZehMatt** [comment]
I would still separate the Drawing/Graphics-Context and RenderTarget/Canvas.

So one can do something like
```
RenderContext ctx = renderer.getContext();

// By default the context is assigned to the frame buffer
// It can be still set manually if needed to.
ctx.pushRenderTarget(renderer.getFrameBuffer());

// Draw scene into buffer via context, view specifies position/rotation/dimensions, options specify if things should be invisible and other gimmicks.
DrawWorld(ctx, view, options);

ctx.popRenderTarget();
```
Given example would draw the entire scene into the main render target/frame buffer. The push/pop is just setting the active render target and remembers the previous texture, this operation is basically glBindTexture underneath.

This should also help decouple UI, if a window wants to draw some part of the map it just renders into a separate RenderTarget and that part is just drawn into the main render target. Example:

```
RenderContext ctx = renderer.getContext();

// Generate a new texture of width by height, flags specify the texture settings such as transparency, colors etc.
RenderTarget rt(width, height, flags);

// Set as active target.
ctx.pushRenderTarget(rt);

DrawWorld(ctx, window->viewport, ...);

// Restore to main.
ctx.popRenderTarget();

// Draw the buffer into the main render target.
ctx.DrawTexture(pos, rt);
```

This also means we can now specify the order of things drawn.
```
RenderWorld
-> Surface
-> Entities, etc.
RenderWindows
-> Visible UI components
RenderHUD
-> Messages/Errors
-> FPS
PostProcess
-> Colors, Lights, etc.
```

**Comment by AaronVanGeffen** [comment]
RenderTarget/Canvas sounds good to me. @ZehMatt makes a convincing argument. :)

**Comment by duncanspumpkin** [comment]
I was going through and doing some coding style enforcement and we still have not renamed this. What is the consensus, vote by using the reactions:

1. RenderTarget, 🎉
2. Canvas,👀
3. Context, 🚀

**Comment by duncanspumpkin** [comment]
I've changed my vote so that the tie is broken. Context wins.
