### ISSUE TITLE
Music does not play automatically

### ISSUE THREAD

**Issue by Pokemanic33** [OpenLoco/OpenLoco#1670]
**Version information:**
 - Platform: Windows 10
 - Version: 22.10
 - Build/commit: 68882c9

**Describe the bug**
Music does not play automatically on starting a scenario or unpausing.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start a scenario, or load a save. Music is not playing, regardless of previous settings.
2. Start playing music from the settings window.
3. Pause the game.
4. Unpause.

**Expected behaviour**
As in previous versions, music should play on game start and restart when the game is unpaused.

**Comment by LeftofZen** [comment]
@Pokemanic33 I was just browsing issues and saw this, I think this may have been fixed in #1684

**Comment by LeftofZen** [comment]
fixed in #1684
