### ISSUE TITLE
Crash - creating new scenario with pre-existing scenario landscape

### ISSUE THREAD

**Issue by jmz1115** [OpenLoco/OpenLoco#1676]
**Version information:**
 - Platform: Windows 10
 - Version: 22.10
 - Build/commit: 68882c9

**Describe the bug**
When you create a new scenario by loading a previous landscape, then save it with the same name as a _completed_ scenario, the game hangs and sometimes crashes when you attempt to start a new game from the "New Game" menu.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to "Create Scenario"
2. "Load Landscape"
3. Pick any landscape (but especially a landscape that is part of a completed scenario)
4. Save as a new scenario (does not matter what you name it, it will show up with the same name as the completed scenario and there will be 2 of them)
5. Attempt to play the scenario - attempt to hover over the scenario, game will become unresponsive

ALTERNATIVELY - I am not sure which of these caused the initial issue
1. Go to "Create Scenario"
2. "Load Landscape"
3. Folder up to load a scenario into the landscape editor, rather than a landscape (especially a completed scenario)
4. Save as a new scenario (does not matter what you name it, it will show up with the same name as the completed scenario and there will be 2 of them)
5. Attempt to play the scenario - attempt to hover over the scenario, game will become unresponsive

**Expected behaviour**
Be able to hover over and select new scenario

**Additional context**
I tried to find the folder where custom saved scenarios are to delete them, but I can't find it in either Roaming - openloco - save OR in programfilesx86 - atari - locomotion. If you can point me to where that is, then I can try that.

EDIT - okay now I can't create any scenario from a saved landscape no matter what. I think by creating a custom scenario by loading an old scenario, it corrupted whatever file system is used to make new scenarios.

**Comment by duncanspumpkin** [comment]
Something going very wrong when doing this as the memory is getting trashed.
