### ISSUE TITLE
Allow searching/filtering objects in object selection window

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenLoco/OpenLoco#1681]
Like vanilla Locomotion, OpenLoco currently does not allow for searching/filtering objects in its object selection window. All installed objects are just listed alphabetically:
<img width="1624" alt="Screenshot 2022-10-16 at 02 22 55" src="https://user-images.githubusercontent.com/604665/195999797-99d479cb-928a-4ce0-9123-d73ebc54572e.png">

OpenRCT2 adds a search bar to the window, allowing to filter the list per the input query. I propose we implement a similar solution in OpenLoco:
<img width="1624" alt="Screenshot 2022-10-16 at 02 27 22" src="https://user-images.githubusercontent.com/604665/195999869-6abd542c-ca21-4c39-9321-8306b8141c00.png">

**Comment by BL97** [comment]
this would be very useful thank you
