### ISSUE TITLE
ObjectManager::(un)loadScenarioText: misnomer?

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenLoco/OpenLoco#1683]
Two functions in the ObjectManager namespace, `loadScenarioText` and `unloadScenarioText` were identified pretty early in the RE process. Given they show up outside of scenario text context, I believe these to be misnomers. We should probably assign a new name to them.

**Comment by duncanspumpkin** [comment]
Yes these are temporary load/unloads. They are used to check some object details without fully loading them into the game state
