### ISSUE TITLE
allow locomotion to use subfolders and be informed of duplicate .dat files

### ISSUE THREAD

**Issue by BL97** [OpenLoco/OpenLoco#1687]
locomotion should be able to see files in subfolders of the objdata folder to allow for better organisation of .dat files from packs etc plus detect duplicate .dat files

this would allow the user to have better organisation of vehicles and other dat files and allow them to compare vehicles of the same file name easier so that they may decide which one to keep or discard or so that they may edit the file name to fix the conflict, this would greatly optimise modding for anyone who partakes

**Comment by duncanspumpkin** [comment]
The filename doesn't actually get checked when working out if there is a collision you could rename everything already to avoid collisions. But yes it would be good to make it so that folders work. Will require more implementation though before we can do that.

**Comment by LeftofZen** [comment]
@duncanspumpkin I looked through the object manager and this seems doable now?
https://github.com/OpenLoco/OpenLoco/blob/23e4017a6ff1a9a694a55ab9c9e6c3d031eddb68/src/OpenLoco/src/Objects/ObjectManager.cpp#L656

You'd just replace `Environment::getPath` call on that line ^ with a method that enumerates all the paths of the subdirectories?
