### ISSUE TITLE
allow the user to view the .dat file name in object selection menu

### ISSUE THREAD

**Issue by BL97** [OpenLoco/OpenLoco#1688]
show the .dat file name within the information field of a vehicle when highlights so know what .dat file it is assigned to

many vehicles have different .dat file names but are the same, some even are the same and have different .dat file names. this solution would streamline the deletion of duplicate .dat files by the user for they'd be able to easier see what .dat file the vehicle belongs to

**Comment by LeftofZen** [comment]
I don't believe we currently store the file name inside the objects that come from it, so we'd need to either a) add that as a property of all objects, or b) create a standalone lookup table of some sort that is populated when objects are loaded, ie `std::unordered_map<LoadedObjectHandle, std::string>` or similar, and query that when we call `drawDescription()` on the object

**Comment by AaronVanGeffen** [comment]
This has since been implemented.
