### ISSUE TITLE
full list of missing vehicles

### ISSUE THREAD

**Issue by BL97** [OpenLoco/OpenLoco#1691]
often when downloading a scenario or loading up and old one you are told that a .dat file is missing, however you are only told about 1 of the missing files regardless of how many there is, an .xml document containing the list of missing files should be produced to help the user better troubleshoot the issue

**Comment by AaronVanGeffen** [comment]
Currently, the game console will list all missing objects. However, I'd like us to eventually move to show a window like this one in OpenRCT2:

![](https://user-images.githubusercontent.com/604665/38830879-ef1a2178-41bd-11e8-8459-918bf1f8e717.png)

**Comment by LeftofZen** [comment]
I believe we have this feature now, should we close this issue @AaronVanGeffen?
