### ISSUE TITLE
unset the Locomotion directory from the config if g1.dat could not be loaded

### ISSUE THREAD

**Issue by LeftofZen** [OpenLoco/OpenLoco#1698]
**Describe the solution you'd like**
unset the Locomotion directory from the config if g1.dat could not be loaded

**Describe alternatives you've considered**
- leaving functionality as is

**Additional context**

**Comment by AaronVanGeffen** [comment]
I've filed a PR to address the confusing prompts. However, I've chosen not to unset the path as configured, as it was pointed out that a user may have just stored their game on a removable device.
