### ISSUE TITLE
Saved scenarios freeze game momentarily when viewing from New Game window

### ISSUE THREAD

**Issue by SteamsDev** [OpenLoco/OpenLoco#1702]
- Platform: Windows 10 version 21H2
 - Version: 22.10

This may just be the device I'm using, but I've found that the newest version of OpenLoco has a weird bug when saving scenarios. If they're viewed in the New Game window, it tends to freeze the game momentarily before moving a few frames and then freezing again. It seems to continue until I move the cursor off the map to view another that wasn't saved in this version of OpenLoco.

Steps to reproduce the behaviour:
1. Create a scenario in OpenLoco version 22.10 that has at least 50% terrain above sea level
2. Open the New Game window and find the scenario
3. Hover over it with the cursor

If done right, it should freeze the game for roughly 15-30 seconds before continuing. If it failed, try adding more terrain and/or setting a higher map height in the map.

Note: this doesn't apply to scenarios saved on earlier versions of OpenLoco (to my knowledge). I tested this already.

It may have to do with the preview image of the scenario, if it helps.

Attached is a map I know has this bug. It was saved in version 22.10.
[Oil Oasis II.zip](https://github.com/OpenLoco/OpenLoco/files/9892581/Oil.Oasis.II.zip)

**Comment by duncanspumpkin** [comment]
It sounds suspiciously like the game is doing a full size screenshot instead of the normal small preview screenshot.

**Comment by AaronVanGeffen** [comment]
Thanks, this is an interesting report. I agree with @duncanspumpkin that it sounds suspiciously like our new 'giant screenshot' feature may be the cause.

What puzzles me is that the scenario select window ('new game') isn't generating any screenshots; it draws a preview directly from the scenario file. Unlike save games, this scenario preview typically shows a terrain map rather than a screenshot. We'll have to investigate this some more.

**Comment by AaronVanGeffen** [comment]
Speculation aside, I'm having difficulty reproducing this bug. The scenario shows up in the scenario list, and renders at a solid 50-55fps for me. Am I misunderstanding the issue?

![Yew Island](https://user-images.githubusercontent.com/604665/198865969-05c2ac9c-c87e-46dc-aaa6-e87eaa3fadc7.png)

**Comment by SteamsDev** [comment]
Huh... that wasn't the map I thought it was. Perhaps the actual map was saved in a different location. I'll try to find the map(s) that I made and report back if I find them.

**Comment by SteamsDev** [comment]
Found them. It seems saved scenarios are stored in "%USERPROFILE%\AppData\Local\VirtualStore\Program Files (x86)\Atari\Locomotion\Scenarios." Took me a search of my entire hard drive to find them.

Anyway, these two maps should have the bug.
[Desktop.zip](https://github.com/OpenLoco/OpenLoco/files/9897402/Desktop.zip)

**Comment by jmz1115** [comment]
I have had this exact same issue when creating a scenario by loading a pre-existing landscape. I first noticed it when I created a scenario using a scenario landscape that I had already beaten.
