### ISSUE TITLE
Passengers drawn on top of trains at stations

### ISSUE THREAD

**Issue by strongbowe1** [OpenLoco/OpenLoco#1717]
- Platform: Windows 10
 - Version: 22.10
 - Build/commit: 68882c9

Passengers are drawn on top of trains at the far side platform of stations in OpenLoco. This does not happen in original Locomotion.

Steps to reproduce the behaviour:
1. Build a train station next to a large city to have it populated quickly by lots of passengers.
2. Put a train into the station, it will have passengers incorrectly drawn on top.

See screenshot and savegame from original Swiss Alps scenario.

![Passengers](https://user-images.githubusercontent.com/37986589/201323721-40324b3b-d058-48d4-a12d-dc06485a8aab.png)
[Passengers.zip](https://github.com/OpenLoco/OpenLoco/files/9989518/Passengers.zip)

**Comment by AaronVanGeffen** [comment]
Thanks for raising this issue. See also #1483
