### ISSUE TITLE
Misc. Building Crash - Sandbox Mode

### ISSUE THREAD

**Issue by glenjimen** [OpenLoco/OpenLoco#1730]
**Version information:**
 - Platform: Windows 10
 - Version: 22.10
 - Build/commit: 68882c9

**Describe the bug**
When I've enabled Sandbox mode in-game, and mouse-over the misc. buildings window, openLoco will occasionally crash.   I can open the City/Town info window, but when I swap over to the Misc. Buildings tab, crashes.  It seems to occur right when I mouse-over the build menu so it expands to show multiple rows, instead of minimizing to only one row.  This typically happens when I happen to have many misc. buildings on the screen.  I've been converting some older mods that were stations, into individual buildings, so my misc. building window has about 40 building choices in it.

**To Reproduce**
Start a new game.
Enable sandbox mode.
Open the window to construct new buildings.
Go to the Misc. Building Tab.
Mouse over the window so it expands to show more than one row.

**Expected behaviour**
OpenLoco would continue to let the player select a misc. building and place on the map.

**Additional context**
Dump File : https://drive.google.com/drive/folders/1h1a3yCYxvWhtA--now4OIKLw1vk35UVc?usp=sharing

**Comment by glenjimen** [comment]
May be related.
A 2x2 building with bit_1 set to true will cause a crash in the landscape editor when generating a new map.  Original and Improved map generator have the same error.  1x1 buildings can have bit_1 set true without issue.  
bit_0 sets the building to be 2x2 (true) or 1x1 (false).
So, 2x2 buildings cannot be in the Misc. Building folder.  Maybe loco is trying to randomly place these misc. buildings when generating a new map?

**Comment by duncanspumpkin** [comment]
Can you provide enough misc buildings for me to be able to do it? I've only got 4 from vanilla.

**Comment by glenjimen** [comment]
I posted some misc. buildings on Discord, under General on 11/27.  (Don't know how to link to it here).  I don't recall exactly how many there are, but you should have enough to fill out the misc buildings window.

**Comment by glenjimen** [comment]
Same error occurred again.  This time the console printed out errors.  Very strange because most if not all of these were not in the objData folder, and of course not in the scenario I was playing. 

OpenLoco, v22.12 (e0c7b9c2 on master)
Failed to load: SNDFRGH2
Failed to load: SNDSD45E
Failed to load: SNDFRGHT
Failed to load: SNDUSAIR
Failed to load: SNDSD40H
Failed to load: SNDUSB01
Failed to load: WDCHPS
Failed to load: SIGDWARF
Failed to load: SIGUSGO1
Failed to load: SIGCUS1
Failed to load: FLYOVER
Failed to load: INVISIBL
Failed to load: DEPOT00
Failed to load: DEPOT40
Failed to load: DEPOT80
Failed to load: TRSTAINV
Failed to load: COALLOAD
Failed to load: IRONLOAD
Failed to load: RDSTAT13
Failed to load: CARTLOAD
Failed to load: AMITRAMC
Failed to load: TRAM1wgn
Failed to load: TRAM4WGN
Failed to load: TRAM3WGN
Failed to load: FRGFCBF2
Failed to load: FRGFCBF1
Failed to load: FRGFBHF2
Failed to load: FRGFBHF1
Failed to load: USC42413
Failed to load: USC63M13
Failed to load: FRLFCFR1
Failed to load: SPSD4501
Failed to load: USLSB03
Failed to load: USC63M10
Failed to load: USC63M11
Failed to load: USPCCSEP
Failed to load: USPCCSRA
Failed to load: USHC306
Failed to load: USHC321
Failed to load: USPCCTNT
Failed to load: XBCCNB
Failed to load: XBCCP
Failed to load: XBCPC
Failed to load: XSF40BC
Failed to load: USHC308
Failed to load: USD712
Failed to load: USD912
Failed to load: USD901
Failed to load: USD902
Failed to load: XBCCV
Failed to load: WCGBN01
Failed to load: WCGSP01
Failed to load: USD914
Failed to load: USD931
Failed to load: USGP3811
Failed to load: USGP8206
Failed to load: USGP8202
Failed to load: USGP8213
Failed to load: USGP8210
Failed to load: USGP8W13
Failed to load: USGP9202
Failed to load: USGP6038
Failed to load: USGP6031
Failed to load: USGP906
Failed to load: USGP914
Failed to load: USGP910
Failed to load: USGP911
Failed to load: USGFBH01
Failed to load: USGDS011
Failed to load: USGDS012
Failed to load: USGBC506
Failed to load: USGBC514
Failed to load: USGBC517
Failed to load: USGBC566
Failed to load: USGBC538
Failed to load: USGFCB01
Failed to load: USGFC15
Failed to load: US-TTX-1
Failed to load: US-TTX-2
Failed to load: USWH2B06
Failed to load: USWH2B07
Failed to load: USWH3B45
Failed to load: USWHC473
Failed to load: USWHC410
Failed to load: USWHC471
Failed to load: USWHC472
Failed to load: USHR4213
Failed to load: USHR6113
Failed to load: USLBC525
Failed to load: USLBC539
Failed to load: USLBC520
Failed to load: USLB01
Failed to load: USLS01
Failed to load: USLS02
Failed to load: USLSB01
Failed to load: USM42012
Failed to load: USM42013
Failed to load: USC63613
Failed to load: USPBC537
Failed to load: USPBC511
Failed to load: USPBH506
Failed to load: USPBH537
Failed to load: USPBH539
Failed to load: USPBC518
Failed to load: USRDC112
Failed to load: USRDC114
Failed to load: USRDC158
Failed to load: USRDC312
Failed to load: USRDC314
Failed to load: USRDC358
Failed to load: USRS312
Failed to load: USRS338
Failed to load: USSD4038
Failed to load: USSD4212
Failed to load: USSD4202
Failed to load: USSD4201
Failed to load: USSD4214
Failed to load: USSD4238
Failed to load: USSD4208
Failed to load: USSD4F11
Failed to load: USSD6F13
Failed to load: USSD6M38
Failed to load: USSD906
Failed to load: USSD9011
Failed to load: USSW1214
Failed to load: USSW1238
Failed to load: USSCC31
Failed to load: USSFC21
Failed to load: USSFC31
Failed to load: UST4850
Failed to load: UST4849
Failed to load: UST4851
Failed to load: UST4852
Failed to load: UST5653
Failed to load: UST5606
Failed to load: UST5654
Failed to load: UST5655
Failed to load: USWC06
Failed to load: USWC14
Failed to load: USWC29
Failed to load: FLIPPER1
Failed to load: PAPRMIL2
Failed to load: SAWMLL2
Failed to load: LUMBCAMP
Failed to load: COMP-WP
Tick interrupted
Tick interrupted

**Comment by duncanspumpkin** [comment]
i still cant reproduce this. I've tried now with the additional buildings you provided but still no dice.
