### ISSUE TITLE
[ALSOFT] (EE) Failed to check format support: 0x80070057

### ISSUE THREAD

**Issue by strongbowe1** [OpenLoco/OpenLoco#1732]
- Platform: Windows 10
 - Version: 22.11
 - Build/commit: cf6e04ab

Getting this message right on every game startup, not sure what it means.

OpenLoco, 22.11 (cf6e04ab on master)
**[ALSOFT] (EE) Failed to check format support: 0x80070057**

**Comment by AaronVanGeffen** [comment]
Does the game start normally after displaying this message?

**Comment by strongbowe1** [comment]
Yes, the game works correctly. So it's nothing serious, just wanted to know what it means since I've been getting this error for some time now.
