### ISSUE TITLE
Editing default scenarios...

### ISSUE THREAD

**Issue by Crashcast-E** [OpenLoco/OpenLoco#175]
Hello.
So I want to take the map of the Midwestern United States and enable vehicle mods and such for it. is there a way to load it in scenario editor to edit what vehicles, airports, and such are available?

**Comment by IntelOrca** [comment]
If you enable debug tools in the options window you can then edit the objects within the game. You do not need to use the scenario editor.

**Comment by IntelOrca** [comment]
In OpenRCT2 we allowed the object manager to be opened in normal play. I expect it wouldn't be too hard to add a dropdown item for with OpenLoco although it used to be unreliable initially in OpenRCT2.

**Comment by AaronVanGeffen** [comment]
We should be able to start reimplementing the top toolbar soon. Once we have that going, we should be able to start adding useful shortcuts like these as well.
