### ISSUE TITLE
Why no win64 build?

### ISSUE THREAD

**Issue by Paelor** [OpenLoco/OpenLoco#1756]
Why no win64 build in releases? Win64 builds exist for: CorsixTH, EndlessSky, OpenApoc, OpenRCT2, OpenTTD and many others, but I don't understand why OpenLoco is only available as a win32 build.

**Comment by janisozaur** [comment]
Because we depend on and call to original native x86 code. We will provide amd64 builds when projects is mature enough and we can modify size of fields in internal structures.

**Comment by AaronVanGeffen** [comment]
As @janisozaur, it's basically because we haven't fully reimplemented the game in C++ yet. We estimate that we are about 50% done. Before it's 100% done, we can only build 32-bit x86 platform. After, we expect to build for many more platforms indeed.
