### ISSUE TITLE
Title music does not stop when unchecked in options window

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenLoco/OpenLoco#1763]
**Version information:**
 - Platform: Linux
 - Version: 22.12+
 - Build/commit: a26f8204

**Describe the bug**
Title music does not stop when unchecked in options window. The music does start playing when the option is checked (and no music is playing yet), but not the other way around.

**Comment by dschoemehl** [comment]
Pull request #1774 shoudl fix this. Sorry for the confusion with the different branches and commits.
