### ISSUE TITLE
Missing string id: 2237 error

### ISSUE THREAD

**Issue by MadeInDutch** [OpenLoco/OpenLoco#1858]
![image](https://user-images.githubusercontent.com/67276601/219976255-f30c3bdd-d5fa-43de-a96f-2d332254e684.png)

One of the options, as well as the date, is replaced by "missing string id: 2237". Also when I scroll across the map, the bracket in front of "missing string id" duplicates and stays on the screen.

Seems like a simple fix, but I wouldn't know.

**Comment by MadeInDutch** [comment]
Small correction: the option says "Missing string id: 2264".

**Comment by AaronVanGeffen** [comment]
Your language files are outdated. Please make sure to extract the full `data` folder from the release archive (zip).

**Comment by MadeInDutch** [comment]
I did and it still didn't change.

**Comment by AaronVanGeffen** [comment]
I don't know what else to tell you. The strings in question have been in OpenLoco since October 2022 at least. Please ensure you've overwritten the language files (.yml) in the data directory.

**Comment by MadeInDutch** [comment]
I don't know why that doesn't work. I've tried extracting multiple times and it still doesn't change it. I'm using the very latest version, so it should work, but it doesn't.

**Comment by duncanspumpkin** [comment]
How did you install the game? What platform (I'm assuming its windows)?

**Comment by MadeInDutch** [comment]
Yeah, Windows 10. I just got the .zip file from this page.

**Comment by duncanspumpkin** [comment]
so you've just taken the release `OpenLoco-v23.02-win32.zip` extracted the whole .zip into a folder. Could you confirm that all the files are date modified 19/02/2023:
![image](https://user-images.githubusercontent.com/1277401/220053112-47ce8101-1bb2-47a1-b339-32dcf560c96b.png)
And same for the data directory:

![image](https://user-images.githubusercontent.com/1277401/220053206-21ee1910-f5e5-4b8c-a674-e9dacbc85086.png)

**Comment by MadeInDutch** [comment]
![image](https://user-images.githubusercontent.com/67276601/220080828-da70aa48-04ce-4da2-8a42-61ecbd37adf9.png)
![image](https://user-images.githubusercontent.com/67276601/220080912-ba09ac2f-4d57-4b38-a5b7-173eed234082.png)

**Comment by duncanspumpkin** [comment]
Are you using en-gb or en-us?

**Comment by MadeInDutch** [comment]
I'm using UK English

**Comment by LeftofZen** [comment]
@MadeInDutch is this still an issue for you on the lastest version, 23.05?

**Comment by LeftofZen** [comment]
Do you have a discord account? I'd be happy to try and fix the issue with you, as we're pretty sure this is something local to your PC and not with loco or open loco itself

**Comment by MadeInDutch** [comment]
BenchFox#8823

**Comment by MadeInDutch** [comment]
I upgraded OpenLoco and I still have this issue.
![image](https://github.com/OpenLoco/OpenLoco/assets/67276601/b47da842-f4a3-44fd-860a-7b84ab272e6b)
The white stuff on the map is part of the text bleeding onto the map.

When will this get solved?

**Comment by MadeInDutch** [comment]
Yes
