### ISSUE TITLE
Feature Request: Cheat Menu

### ISSUE THREAD

**Issue by Xenophic** [OpenLoco/OpenLoco#186]
Something i feel would help a lot for both testing and game play purposes, could we have an ingame cheats menu similar to that in OpenRTC2? At minimum i'd like an option to cheat in money, building large tests of ideas takes a lot of time.

https://github.com/OpenRCT2/OpenRCT2/wiki/Cheats-Window

**Comment by Sebazzz** [comment]
For those who arrive from a search on Cheats, the original cheats from Locomotion [are implemented](https://github.com/OpenLoco/OpenLoco/blob/6988223e06fcfed3b7ca76c6354abe29ca295368/src/openloco/Input/Keyboard.cpp#L59-L63). Just hold `INSERT` and type the corresponding character string.
