### ISSUE TITLE
Failed to load older save games

### ISSUE THREAD

**Issue by NSTrains** [OpenLoco/OpenLoco#1930]
**Version information:**
 - Platform: Windows 10
 - Version: 23.04
 - Build/commit: a2d1f3a

**Describe the bug**
Any older save game will fail to load, and error says object is missing, but its already in Objdata

**To Reproduce**
Steps to reproduce the behaviour:
1. Start Openloco
2. Load any older save game
3. OpenLoco wil fail to load the save game and the error will say missing object and console too

**Expected behaviour**
The save game will load without any problem

**Comment by NSTrains** [comment]
its all my save games except for one I just made
[Cajon.zip](https://github.com/OpenLoco/OpenLoco/files/11337902/Cajon.zip)

**Comment by duncanspumpkin** [comment]
Issue caused by missing objects
