### ISSUE TITLE
Windows flash crash 

### ISSUE THREAD

**Issue by rclsham** [OpenLoco/OpenLoco#1935]
**Version information:**
 - Platform: Win 11
 - Version: 23.04.1
 - Build/commit: c9d9ef35

**Describe the bug**
Exception: yaml-cpp: error at line 1, column 3: unknown escape character:

**Comment by AaronVanGeffen** [comment]
Could you try deleting your game config file, `openloco.yml`? It currently does not have great error recovery.

**Comment by rclsham** [comment]
that solved the problem, thanks!
