### ISSUE TITLE
"Failed to read data from stream"

### ISSUE THREAD

**Issue by NSTrains** [OpenLoco/OpenLoco#1936]
**Version information:**
 - Platform: Windows 10
 - Version: 23.04.1
 - Build/commit: c9d9ef3

**Describe the bug**
Game fails to launch with error "Failed to read data from stream"

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch OpenLoco
2. Game will attempt to launch
3. Game fails to launch with error "Failed to read data from stream"

**Expected behaviour**
Game launches into main menu without error

![Capture](https://user-images.githubusercontent.com/53015176/235531829-d1ea546f-b6f1-4d29-ac93-fa3c4416be53.PNG)

**Comment by AaronVanGeffen** [comment]
The error message isn't particularly helpful, but originates in OpenLoco's S5 reader, which takes care of reading SV5 and SC5 files. This suggests one of the scenarios it's trying to read is corrupt to such an extent that our code cannot recover.

As previously suggested on Discord, try narrowing down the problem by temporarily moving non-vanilla files out of your Locomotion install. I suggest starting with custom scenarios.

**Comment by NSTrains** [comment]
Its not any of those because I moved the all save games, scenarios, landscapes out of the right folders and still the error exists

**Comment by AaronVanGeffen** [comment]
Then, please try temporarily moving the scenario index (scores.dat) out of the OpenLoco config directory (on Windows, this is `%APPDATA%\OpenLoco`).

If that doesn't work, I'm out of ideas. Maybe @duncanspumpkin has some insight.

**Comment by NSTrains** [comment]
Tried that and the error did not go away

**Comment by NSTrains** [comment]
Closing. Game fully working
