### ISSUE TITLE
vehicle fails to select in scenario editor without generating saved terrain when less than 224 vehicles

### ISSUE THREAD

**Issue by NSTrains** [OpenLoco/OpenLoco#1939]
**Version information:**
 - Platform: Windows 10
 - Version: 23.04.1
 - Build/commit: c9dc9f3

**Describe the bug**
I am unable to select vehicles in scenario editor without loading a saved terrain when there less then 224 vehicles selected

**To Reproduce**
Steps to reproduce the behaviour:
1. Start OpenLoco
2. Click on scenario editor
3. try to select a vehicle
4. you will see it fails to select with the error

**Expected behaviour**
vehicle will be selected and the vehicle count will increase by 1 

**Screenshots**
![Unnamed](https://user-images.githubusercontent.com/53015176/236354256-550f77c5-b449-4adb-9c58-fb739cc51c95.png)

**Comment by LeftofZen** [comment]
Just tested this on release 23.04, no issues on my end, so we need some more detailed repro steps.

You are right that this is strange though and that that error message shouldn't show because 54 is definitely < 224.

**Comment by duncanspumpkin** [comment]
It could be that the dependent objects that the vehicle brings in has exceeded its limits. The error messages are rather unhelpful in this regard it will display this same message for too many of any object. For reference vehicles can have the following dependent objects: tracks/roads, sounds, track/roadExtras, steam. So you need to check each of these to make sure you haven't exceeded the limits for them.

**Comment by NSTrains** [comment]
ok ill look at that
