### ISSUE TITLE
"Clone vehicle" does not clone cargo retrofit selection

### ISSUE THREAD

**Issue by LeftofZen** [OpenLoco/OpenLoco#1953]
**Version information:**
 - Platform: Win11
 - Version: 23.04.1
 - Build/commit: release

**Describe the bug**
Clone vehicle does not clone the refitted cargo selection for the vehicle.

**To Reproduce**
Steps to reproduce the behaviour:
I did this with planes:
1. Create plane, retrofit/refit its cargo to something other than the default. Eg a plane to carry mail.
2. Clone vehicle
3. Cloned vehicle doesn't have the refitted cargo type clones, it reverts back to default

**Expected behaviour**
Cloned vehicle copies retrofitted cargo selection

**Screenshots**

**Additional context**

**Comment by LeftofZen** [comment]
Had a quick peek into the code, "Refit vehicle" is game command 64 and its not reverse-engineered, and I don't see any related variables in VehicleHead so I presume its one of the unknown vars that holds this info.

**Comment by AaronVanGeffen** [comment]
We'll probably find out which vehicle member variables to set after implementing the refit game command, `0x0042F6DB`.
