### ISSUE TITLE
Title screen crashes after about a minute

### ISSUE THREAD

**Issue by LeftofZen** [OpenLoco/OpenLoco#1968]
**Version information:**
 - Platform: Win11
 - Version: 23.05
 - Build/commit: master

**Describe the bug**
Title screen intro sequence crashes when loading this map (below in screenshots)
Caused by the changes in #1899, https://github.com/OpenLoco/OpenLoco/commit/602aa6810a33354bc455c3c3ac60d2b01da504d9

**To Reproduce**
Steps to reproduce the behaviour:
1. Start 23.05
2. Wait until title sequence tries to load this map

**Expected behaviour**
No Crash

**Screenshots**
![image](https://github.com/OpenLoco/OpenLoco/assets/7483209/8652106a-2ff4-4e72-b872-a3753d7708fd)
![image](https://github.com/OpenLoco/OpenLoco/assets/7483209/686031ef-e43e-41b2-ad38-10656252f22a)

**Additional context**
Caused by https://github.com/OpenLoco/OpenLoco/commit/602aa6810a33354bc455c3c3ac60d2b01da504d9

**Comment by LeftofZen** [comment]
FWIW I don't think this is actually related to this scene in the map, its related to something happening at that time in the title sequence. If you load the title sequence as a save game (and disable the "this is a title sequence" exception) and then fast forward the game until 11th Jan 1973, you'll be able to repro this as well.

**Comment by LeftofZen** [comment]
Kinda strange but if you comment these lines out in master, no crash

https://github.com/OpenLoco/OpenLoco/blob/9d00666615f1fcf7a2acc800de9223ea67c97c1d/src/OpenLoco/src/Map/TileManager.cpp#LL1319C13-L1321C23

**Comment by AaronVanGeffen** [comment]
I imagine it to be related to an AI company performing a particular action? Both Duncan and myself must have tested it with AIthink disabled.

**Comment by LeftofZen** [comment]
It's definitely not AI-related as I can reliably repro it with no AI on, and by commenting/uncommenting the update tree call linked above
