### ISSUE TITLE
Ability to reverse the Route orders

### ISSUE THREAD

**Issue by YetiWiz** [OpenLoco/OpenLoco#1972]
**Describe the solution you'd like**
Add a button in the Vehicle Window - Route Tab which reverses the list of orders for that vehicle.

**Additional context**
![image](https://github.com/OpenLoco/OpenLoco/assets/36667284/05aa37f4-ee15-402e-b5af-a40cf1a1dfbe)

**Comment by AaronVanGeffen** [comment]
I think this could be implemented fairly efficiently as a new game command. Will look into it.

**Comment by AaronVanGeffen** [comment]
Implemented in #1973
