### ISSUE TITLE
crash in a special game save and don't know what happen

### ISSUE THREAD

**Issue by dzw13579** [OpenLoco/OpenLoco#1983]
**Version information:**
 - Platform: win10
 - Version: 23.05
 - Build/commit: 9d006666

**Describe the bug**
I have no idea how the bug triggered, I just load a game, move around in the map, later it will became no respoding then exit from game.

**To Reproduce**
Steps to reproduce the behaviour:
1. load a game save file that  I play;
2. do anything you want, or just wait maybe a minute;
3. It crash....

**Additional context**
this is the save file easily to crash, may help to solve problem
is there any log file I can send to here? I can't find it. maybe someone show me the location? thanks!
[autosave_2023-06-08_00-14-51.SV5.zip](https://github.com/OpenLoco/OpenLoco/files/11712524/autosave_2023-06-08_00-14-51.SV5.zip)

**Comment by AaronVanGeffen** [comment]
Sounds like a bug we have already fixed. We've shared the fix on Discord already, if you'd like to check it out. Otherwise, it'll be fixed in the next release, too.

**Comment by dzw13579** [comment]
> Sounds like a bug we have already fixed. We've shared the fix on Discord already, if you'd like to check it out. Otherwise, it'll be fixed in the next release, too.

I can't find the correct group, can you tell me which is it？Thank you!

**Comment by AaronVanGeffen** [comment]
> I can't find the correct group, can you tell me which is it？Thank you!

https://discord.gg/vEuNRHD, `#issues` channel. [Link to message](https://discord.com/channels/689445672390361176/701513891821387836/1115906596753657856)
