### ISSUE TITLE
23.06 will not launch

### ISSUE THREAD

**Issue by NSTrains** [OpenLoco/OpenLoco#1987]
**Version information:**
 - Platform: Windows 10
 - Version: 23.06
 - Build/commit: a2207a4

**Describe the bug**
Game will not launch with no error and nothing on the console

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on OpenLoco.exe
2. Game will crash before checking objects with no error and nothing on the console

**Expected behaviour**
Game will launch like normal

I haven't touched anything since I just downloaded it and this is what happens

**Comment by NSTrains** [comment]
accidently closed it, problem still here

**Comment by NSTrains** [comment]
I don't have that

**Comment by AaronVanGeffen** [comment]
You should, but it may be in a different place than you expect. On Windows, it will be stored in the `%APPDATA%\OpenLoco` folder (`C:\Users\your_name\AppData\Roaming\OpenLoco`)

**Comment by NSTrains** [comment]
Oh, I didn't know it was in there, thanks its working now
