### ISSUE TITLE
Crashes without starting

### ISSUE THREAD

**Issue by superchadST345** [OpenLoco/OpenLoco#1999]
**Version information:**
 - Platform: Windows 11
 - Version: 23.06 and 23.06.1

**Describe the bug**
The game crashes on startup with no intor screen or music, does not affect 23.05

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the Exe
2. game crashes

**Expected behaviour**
The game should load properly as on previous versions

**Screenshots**
![image](https://github.com/OpenLoco/OpenLoco/assets/6529196/1009e6cc-2cd3-44bc-9b56-30e4ac9fd17b)

**Additional context**
everything works fine on 23.05

**Comment by AaronVanGeffen** [comment]
Could you try renaming the openloco.yml file (from %APPDATA%\OpenLoco), and see if that makes a difference? If it does, please attach the old config file so we can see what went wrong.

**Comment by superchadST345** [comment]
[openlocoold.txt](https://github.com/OpenLoco/OpenLoco/files/11808106/openlocoold.txt)
[current.txt](https://github.com/OpenLoco/OpenLoco/files/11808107/current.txt)

it starts now, resolution setting appears to be greyed out.

![image](https://github.com/OpenLoco/OpenLoco/assets/6529196/298a9242-4638-4b49-a302-4abd32130953)

**Comment by AaronVanGeffen** [comment]
Curious. The changes aren't touching the areas I was expecting. Perhaps something to do with the uncap FPS option? Does re-enabling that make it crash again?

```diff
--- openlocoold.txt	2023-06-21 22:30:11
+++ current.txt	2023-06-21 22:29:39
@@ -1,8 +1,8 @@
 display:
   mode: window
   window_resolution:
-    width: 1919
-    height: 2075
+    width: 2485
+    height: 1683
   fullscreen_resolution:
     width: 0
     height: 0
@@ -12,19 +12,19 @@
   enabled: false
 allow_multiple_instances: false
 loco_install_path: D:\Steam\steamapps\common\Locomotion
-last_save_path: C:\Users\User\AppData\Roaming\OpenLoco\save\
-language: en-US
-breakdowns_disabled: true
+last_save_path: ""
+language: en-GB
+breakdowns_disabled: false
 trainsReverseAtSignals: true
-cheats_menu_enabled: true
+cheats_menu_enabled: false
 companyAIDisabled: false
 townGrowthDisabled: false
-scale_factor: 2
+scale_factor: 1
 zoom_to_cursor: true
 autosave_frequency: 1
 autosave_amount: 12
 showFPS: true
-uncapFPS: false
+uncapFPS: true
 displayLockedVehicles: false
 buildLockedVehicles: false
 invertRightMouseViewPan: false
```

**Comment by ZehMatt** [comment]
The crash seems to be happening on trying to clear the render target right after initialization, I'll have to investigate to whats happening here.

**Comment by AaronVanGeffen** [comment]
Thanks for the bug report. Will be fixed in the next release!
