### ISSUE TITLE
Raise window/viewport limit

### ISSUE THREAD

**Issue by jgottula** [OpenLoco/OpenLoco#2]
Particularly when running at higher resolutions, it's extremely common and annoying to have existing windows close when new windows are temporarily opened.

The original limits are: 12 windows, 10 viewports.

Fortunately it's very easy to increase these limits, even in a hacky manner, because of how the `new_window_pointer`/`new_viewport_pointer` stuff works. (It's actually kind of clever and nice, in its own way.) Only pointer references have to be messed with; there are no magic constants scattered around everywhere to be hunted down and adjusted.

----

I managed to make a working raise-window-and-viewport-limit mod in a statically-hack-the-EXE-file manner, by doing the following:
1. Finding `window_list`, `new_window_pointer`, `viewport_list`, and `new_viewport_pointer` in Loco.exe based on the corresponding reverse engineering already done on RCT2.exe:
```
window_list          @ 0x011370AC
new_window_pointer   @ 0x0113D754
viewport_list        @ 0x0113D758
new_viewport_pointer @ 0x0113D820
```
2. Statically hacking Loco.exe to add an additional data section at the end of the EXE with a bunch of free space (I created `.data2` going from 0x01320000 to 0x01400000) and fixing up the EXE's headers and physical size accordingly.
3. Creating new locations for the four labels mentioned earlier in the new data section, laid out so that there's enough room for 100x `loco_window` structs between `window_list` and `new_window_pointer`, and 100x `loco_viewport` structs between `viewport_list` and `new_viewport_pointer`:
```
ext_window_list          @ 0x01320000
ext_new_window_pointer   @ 0x01355778
ext_viewport_list        @ 0x0135577C
ext_new_viewport_pointer @ 0x01355F4C
```
4. Using a hex editor to update all of the instruction arguments referring to the 4 relevant locations so that they now point to the new locations instead.
  - `AC 70 13 01` --> `00 00 32 01` (44 replacements)
  - `54 D7 13 01` --> `78 57 35 01` (57 replacements)
  - `58 D7 13 01` --> `7C 57 35 01` (4 replacements)
  - `20 D8 13 01` --> `4C 5F 35 01` (15 replacements)

And it works.

----

I'll probably make a branch and PR soon, implementing these limit overrides in this project, in a "doesn't involve statically hacking the EXE file with a hex editor" manner.

Maybe I'll even *(gasp)* use `malloc`/`operator new` for the memory, like a sane person, instead of permanently reserving it as a big chunk of the data section. (I mean, I have a certain respect/awe/incredulity for Sawyer's insistence on doing *everything* directly in assembly language, but some of this stuff is just done in such a stone-age manner...)

**Comment by jgottula** [comment]
Screenshots of the working static EXE mod:

![screenshot28](https://user-images.githubusercontent.com/822207/35116914-c3f693c6-fc41-11e7-96fe-303f5b201277.png)

![screenshot29](https://user-images.githubusercontent.com/822207/35116916-c5a6a0c6-fc41-11e7-8bef-8dfa632cac6a.png)

**Comment by jgottula** [comment]
@IntelOrca Alright, so, I want some feedback on how precisely I ought to implement this.

My preferred way (given the early stage of the project) would be to do it as a startup-time patch: allocate a new, larger space for `window_list`, `viewport_list`, `new_window_pointer`, and `new_viewport_pointer` on the heap, and then go through all of the places in the original game `.text` section that reference those addresses and overwrite them so that they point to the newly allocated locations instead. (Effectively the same methodology I used for my static EXE mod.)

It seems to me that that's by far the most straightforward way to do it, given that there's a grand total of 120 address references that need to be overridden (the *vast majority* of which are in not-yet-reimplemented functions, of course). The main alternative that I can think of would be to reverse engineer and reimplement *all* of the few dozen functions that contain references to any of those four addresses; and then at that point just trivially change the limitation in C++ land. But that seems like much more of a later-stage-of-project way to go about it, obviously.

So is startup-time patching of the manner I'm proposing an acceptable thing to do? And if so, where should I actually put my patching code? Shove it into `openloco::interop::register_hooks`, or put it in a new file/function? I do see that there are already a couple of code patches (not technically hooks *per se*) in `register_hooks`...

(Oh yeah and I do realize that I'd also need to adjust a couple of things in `windowmgr.cpp`, specifically `_windows` and `_windows_end`, which currently just point to the original `window_list` and `new_window_pointer` addresses.)

**Comment by jgottula** [comment]
Oh, and incidentally, I did high single-digit hours of actual gameplay yesterday using my EXE mod, and it was rock-solid stable; no crashiness whatsoever. 😃

**Comment by IntelOrca** [comment]
I can't see an alternative than to replace the addresses in all loco functions which I admit isn't particularly nice. We did not try to increase the window limit in OpenRCT2 until we had implemented all the window management functions.

**Comment by AaronVanGeffen** [comment]
As far as I'm aware, window management has been completely implemented. Are we ready to increase the limit for the next version? (cc @marijnvdwerf)
