### ISSUE TITLE
Crash dumps no longer being generated

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenLoco/OpenLoco#2004]
Since the recent CMake project restructuring, `USE_BREAKPAD` is no longer defined, resulting in crash dumps no longer being generated.

**Comment by Derpercoaster** [comment]
Which versions are affected by this? Is it just all versions?

**Comment by AaronVanGeffen** [comment]
My guess would be that the regression was introduced #1686, making v22.11 the first version affected.
