### ISSUE TITLE
Right-clicking when display scaling is set to a fractional percent causes random scrolling of view

### ISSUE THREAD

**Issue by Derpercoaster** [OpenLoco/OpenLoco#2005]
**Version information:**
 - Platform: Windows 10
 - Version: 23.06.1
 - Build/commit: Unknown

**Describe the bug**
Holding right-click causes the view to scroll in a random direction, mostly up or up-left, even if the mouse is not moved. This only happens when the display scale is set to any fractional percent.

**To Reproduce**
1. Open any scenario, or the scenario editor
2. Set the view scale to any fractional percent
3. Hold the right mouse button down
4. The view will start scrolling on its own

**Expected behaviour**
View scrolling should not occur unless the mouse moves while right-click is held. Presumably, fractional view sizes aren't entirely stable yet, and the game thinks the mouse is slightly to the side of where it actually is, which is what causes the bug.

**Additional context**
Right-clicking to edit objects, such as track or roads, is nearly impossible, as moving the view always prevents right-click editing. The direction the view scrolls also becomes inverted when right-click dragging is inverted in the options menu.

**Comment by AaronVanGeffen** [comment]
Thanks for filing an issue. This was a known issue, but it looks like it hadn't been logged to our issue tracker yet.

**Comment by ZehMatt** [comment]
I've looked into this a bit and I haven't figured it out yet, there is also a line pointing to the issue #151:
```cpp
                    // Fix #151: use relative drag from one frame to the next rather than
                    //           using the relative position from the message loop
                    dragOffset = getNextDragOffset();
```

**Comment by Derpercoaster** [comment]
Would it potentially be useful to see how OpenRCT2 does it, since they are so similar? Locomotion was originally built on a nearly identical engine to RCT2 after all.

**Comment by ZehMatt** [comment]
> Would it potentially be useful to see how OpenRCT2 does it, since they are so similar? Locomotion was originally built on a nearly identical engine to RCT2 after all.

OpenRCT2 is nothing like this code base, I will figure it out eventually.
