### ISSUE TITLE
Crash painting terrain in scenario editor at edge of map.

### ISSUE THREAD

**Issue by Bouncebag** [OpenLoco/OpenLoco#2011]
**Version information:**
 - Windows 10, latest build of Openloco. Original cd version of Locomotion used for files at installation

**Describe the bug**
Using largest brush in adjust land option, map tiles changing from dry grass to normal grass, hold down mouse button and drag tool across landscape then to map edge, crashes when dragged aggressively over map edge.

This was in scenario editor mode, on a generated map using dry grass far from mountains and grass everywhere (sand near water, random spots of brown rock)
The painting of grass on the map worked as expected until reaching the map edge.

I get occasional crashes with other behaviour near the map edge but I haven't been able to reproduce those. Only this one.

**Expected behaviour**
Paint tiles to normal grass from dry grass at edge of map, not crash at edge of map.

**Comment by Derpercoaster** [comment]
You need to indicate what version of OpenLoco you are using. The "latest version" is constantly being updated, and could refer to a lot of things (is it a develop version or a release, or some other thing, for instance).

**Comment by AaronVanGeffen** [comment]
The exact build information is in the lower left corner of the title screen, as well as the console window that pops up with the game.

**Comment by Bouncebag** [comment]
V26.03.01
17th June 2023

Thanks :)
