### ISSUE TITLE
Crash in shiftOrdersRight (potentially shiftOrdersLeft)

### ISSUE THREAD

**Issue by ZehMatt** [OpenLoco/OpenLoco#2016]
**Version information:**
 - Platform: Windows 10
 - Version: 23.06.1
 - Build/commit: 3f5013f9

**Describe the bug**
There is a crash in the function shiftOrdersRight and probably shiftOrdersLeft.

**To Reproduce**
Steps to reproduce the behaviour:
1. Load the save [Great Britain _ Ireland 1930.zip](https://github.com/OpenLoco/OpenLoco/files/11918470/Great.Britain._.Ireland.1930.zip)
2. Wait a little bit until it crashes.

**Comment by AaronVanGeffen** [comment]
This is with AI companies enabled, I'm guessing?

**Comment by ZehMatt** [comment]
> This is with AI companies enabled, I'm guessing?

I think so, I haven't messed with the options.
