### ISSUE TITLE
Industry-Ground Tile Graphic Error

### ISSUE THREAD

**Issue by glenjimen** [OpenLoco/OpenLoco#2028]
**Version information:**
 - Platform: Windows 10
 - Version: v23.06.1
 - Build/commit: 86444106

**Describe the bug**
Industries display with ground-tiles showing thru some of the buildings.  The main industry I've experimented with is the original Steel Mill, but other industries have had the same issue intermittently.  If you place them with the scenario editor and start a new game, the industries can be built anywhere without any graphical error, but when founded in-game, they show this error if built above the snow-line, above 10 height units.  This happens regardless of the climate & snow-line selected.  

**To Reproduce**
Steps to reproduce the behaviour:
Start a new game, like Boulder Breakers.
Use cheats for money, and raise large sections of land to heights of 9, 10 & 11 units.
Found a new steel mill on each section of raised land and fast-forward until construction finishes.
The mill 9 units high should display correctly, 10 shows a less pronounced error, 11 shows a more extreme error. 

**Expected behaviour**
The industries should all appear correctly without ground tiles showing thru.

**Screenshots**
Front Steel Mill was placed in the scenario editor, rear was founded in-game.  Land height is about 25 units.
![IndustryGraphicsError](https://github.com/OpenLoco/OpenLoco/assets/51429904/3b6df1f5-a6d1-4239-a4b7-68e2bcf827e5)

Stair step land height on Boulder Breakers, height of 9,10,11 units.
![boulderBreakersStairSteps](https://github.com/OpenLoco/OpenLoco/assets/51429904/cbcbe0d1-dbfc-41d7-8928-117e03a42144)

**Additional context**
I think when generating new random terrain with towns and industries, these steel mills are always below the snow line.

**Comment by LeftofZen** [comment]
does this happen in vanilla?

**Comment by duncanspumpkin** [comment]
Unfortunately any save with this happening is now bugged. I can't easily fix the existing save but for future ones we can prevent it happening again.

**Comment by glenjimen** [comment]
> does this happen in vanilla?

No, in vanilla the industry displays correctly.
