### ISSUE TITLE
Reorganise game commands

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenLoco/OpenLoco#2069]
Following up on the discussion in #2066, I propose we reorganise the game command files into folders. My initial suggestion for the folders is listed below.

Please feel free to suggest any improvements. The unknown commands are as of yet 

| Command | Id | Proposed category | Comment |
| ------- | -- | ----------------- | ------- |
| vehicleRearrange | 0 | Vehicles |
| vehiclePlace | 1 | Vehicles |
| vehiclePickup | 2 | Vehicles |
| vehicleReverse | 3 | Vehicles |
| vehiclePassSignal | 4 | Vehicles |
| vehicleCreate | 5 | Vehicles |
| vehicleSell | 6 | Vehicles |
| createTrack | 7 | Track |
| removeTrack | 8 | Track |
| changeLoan | 9 | Company |
| vehicleRename | 10 | Vehicles |
| changeStationName | 11 | General |
| vehicleChangeRunningMode | 12 | Vehicles |
| createSignal | 13 | Track |
| removeSignal | 14 | Track |
| createTrainStation | 15 | Track |
| removeTrackStation | 16 | Track |
| createTrackMod | 17 | Track |
| removeTrackMod | 18 | Track |
| changeCompanyColourScheme | 19 | Company |
| pauseGame | 20 | General |
| loadSaveQuitGame | 21 | General
| removeTree | 22 | Terraform |
| createTree | 23 | Terraform |
| changeLandMaterial | 24 | Terraform |
| raiseLand | 25 | Terraform |
| lowerLand | 26 | Terraform |
| lowerRaiseLandMountain | 27 | Terraform |
| raiseWater | 28 | Terraform |
| lowerWater | 29 | Terraform |
| changeCompanyName | 30 | Company |
| changeCompanyOwnerName | 31 | Company |
| createWall | 32 | Terraform |
| removeWall | 33 | Terraform |
| gc_unk_34 | 34 | Terraform | NB: is recolourWall, currently unused
| vehicleOrderInsert | 35 | Vehicles |
| vehicleOrderDelete | 36 | Vehicles |
| vehicleOrderSkip | 37 | Vehicles |
| createRoad | 38 | Road |
| removeRoad | 39 | Road |
| createRoadMod | 40 | Road |
| removeRoadMod | 41 | Road |
| createRoadStation | 42 | Road |
| removeRoadStation | 43 | Road |
| createBuilding | 44 | Buildings |
| removeBuilding | 45 | Buildings |
| renameTown | 46 | Town |
| createIndustry | 47 | Industries |
| removeIndustry | 48 | Industries |
| createTown | 49 | Town |
| removeTown | 50 | Town |
| gc_unk_51 | 51 | ??? |
| gc_unk_52 | 52 | ??? |
| gc_unk_53 | 53 | ??? |
| buildCompanyHeadquarters | 54 | Buildings |
| removeCompanyHeadquarters | 55 | Buildings |
| createAirport | 56 | Airports |
| removeAirport | 57 | Airports |
| vehiclePlaceAir | 58 | Vehicles |
| vehiclePickupAir | 59 | Vehicles |
| createPort | 60 | Docks |
| removePort | 61 | Docks |
| vehiclePlaceWater | 62 | Vehicles |
| vehiclePickupWater | 63 | Vehicles |
| vehicleRefit | 64 | Vehicles |
| changeCompanyFace | 65 | Company |
| clearLand | 66 | Terraform |
| loadMultiplayerMap | 67 | General |
| gc_unk_68 | 68 | ??? |
| gc_unk_69 | 69 | ??? |
| gc_unk_70 | 70 | ??? |
| sendChatMessage | 71 | General |
| multiplayerSave | 72 | General |
| updateOwnerStatus | 73 | Company |
| vehicleSpeedControl | 74 | Vehicles |
| vehicleOrderUp | 75 | Vehicles |
| vehicleOrderDown | 76 | Vehicles |
| vehicleApplyShuntCheat | 77 | Cheats |
| applyFreeCashCheat | 78 | Cheats |
| renameIndustry | 79 | Industries |
| vehicleClone | 80 | Vehicles |
| cheat | 81 | Cheats |
| setGameSpeed | 82 | General |
| vehicleOrderReverse | 83 | Vehicles |

**Comment by ZehMatt** [comment]
Looks good to me, cheats I would maybe have its own Category

**Comment by duncanspumpkin** [comment]
gc_unk_52 is ai. I assume a few of the other ones around it are ai related as well.

**Comment by AaronVanGeffen** [comment]
> gc_unk_52 is ai. I assume a few of the other ones around it are ai related as well.

Having CompanyAI as another category would be fine with me. I'm thinking we can file those once structs get implemented for them.

**Comment by duncanspumpkin** [comment]
I've implemented this on #2066 one thing i notice is that we have plural for some directories and not for others. Do we want to standardise that?

**Comment by AaronVanGeffen** [comment]
Categories to be done:

- [ ] Airports
- [ ] Buildings
- [ ] Cheats
- [ ] Company
- [ ] Docks
- [ ] General
- [ ] Industries
- [ ] Road
- [ ] Terraform
- [ ] Town
- [ ] Track
- [ ] Vehicles
- [ ] ???

**Comment by duncanspumpkin** [comment]
> Perhaps we should split out the order commands from the 'vehicles' category as well, given their number. Any thoughts?

i don't think we need it that split up. We don't want 100's of folders.
