### ISSUE TITLE
Generated maps have wrong edge

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenLoco/OpenLoco#2080]
**Version information:**
 - Platform: macOS
 - Version: 23.07+
 - Build/commit: 12eafca4

![Unnamed](https://github.com/OpenLoco/OpenLoco/assets/604665/a66a05f8-b957-4c2f-b9aa-155e72ecb6da)

~I'm thinking this may be a regression from #2024?~ Nope, this has been in for much longer!

**Comment by LeftofZen** [comment]
nice one, this is something I saw with the heightmap terrain and wasn't sure if it was expected or not
