### ISSUE TITLE
Train paths

### ISSUE THREAD

**Issue by Trainstarr** [OpenLoco/OpenLoco#2095]
**Version information:**
 - Platform: Windows 10
 - Version:  23.08

**Describe the bug**
When I make a new Route for the trains to take the new ones that I made with .08 will not follow it only the ones that were made in .07 work

**Comment by AaronVanGeffen** [comment]
Ah, sorry to hear this regression got in. I'm thinking this could be caused by #2063, since it explicitly deals with routing. @LeftofZen, could you check if a revert if that PR/commit fixes the problem? It's probably worth getting a .1 release out for the fix, even if it means reverting for now...

**Comment by LeftofZen** [comment]
reverted that change, still buggy/didn't fix the issue

**Comment by LeftofZen** [comment]
i tested older versions - this issue exists in 23.07 as well, but not 23.06.1

**Comment by ZehMatt** [comment]
> Definitely some kind of issue with the routing table in 23.08; trains are not having their waypoint index advanced somehow
> 
>  OpenLoco.2023-08-18.01-47-38.mp4

Could you provide that save file?

**Comment by Trainstarr** [comment]
Here is the save that I'm having the problem with It works sometimes but not others https://drive.google.com/file/d/1KbJN_QBNeCVCHXsZpF4N7TJ3aIpiFP2I/view

**Comment by LeftofZen** [comment]
[waypoint_routing.zip](https://github.com/OpenLoco/OpenLoco/files/12384933/waypoint_routing.zip)
this was my save, its just a bit of track and I was deleting the routing orders and randomly placing a couple of waypoints to test whether the issue existed or not
