### ISSUE TITLE
[Update] 09/18/2023 - Tunnel Road Bugs

### ISSUE THREAD

**Issue by asbaktemporary** [OpenLoco/OpenLoco#2101]
**Version information:**
 - Platform: Windows 11
 - Version: OpenLoco v23.03
 - Build/commit: fff56d7c

**Describe the bug**
I often use company asset acquisitions. Every time I do it, I always encounter application crashes. I also tried in various maps, and the result is the same. Some vehicles also stopped status after acquisitions, when I want to replace the vehicle with the one I bought, the rail, the road I'm going to use, doesn't work to use, the application crashes.

**Expected behaviour**
Ideally, when a company has been acquired, I as the new owner should be able to do anything, but I can't, the application crashes immediately.

**Screenshots**
![image](https://github.com/OpenLoco/OpenLoco/assets/98380952/f3087f9d-a177-4309-a236-47f6192b6a04)

**Comment by asbaktemporary** [comment]
**Update**

- Platform: Windows 11
- Version: OpenLoco v23.08
- Build/Commit: d6cfed63

**Screenshots**
![image](https://github.com/OpenLoco/OpenLoco/assets/98380952/a637f2bb-d479-48b8-ab35-3874d7c9df47)

**Describe the bug**
Same issue as my old versions, getting crash/not responding after making several company acquisitions.

**Comment by asbaktemporary** [comment]
Another crash is happen, this is happen after I turn on Sandbox mode and trying to create Industry

![image](https://github.com/OpenLoco/OpenLoco/assets/98380952/fd7bdc5b-a0d1-43e6-8496-67a71d0ffc4e)

**Comment by duncanspumpkin** [comment]
> Another crash is happen, this is happen after I turn on Sandbox mode and trying to create Industry
> 
> ![image](https://user-images.githubusercontent.com/98380952/263904586-fd7bdc5b-a0d1-43e6-8496-67a71d0ffc4e.png)
> 
> DMP files: [f96fb496-7189-4c2a-954f-6cfcfbbb3016(OpenLoco, v23.08 (d6cfed63 on master)).zip](https://github.com/OpenLoco/OpenLoco/files/12460474/f96fb496-7189-4c2a-954f-6cfcfbbb3016.OpenLoco.v23.08.d6cfed63.on.master.zip)

I take it this crash happened after you owned an ai industry? The takeover function isn't very reliable at this time unfortunately.

**Comment by asbaktemporary** [comment]
@duncanspumpkin thank you for explanations, hopefully this will be solved soon.

**Comment by asbaktemporary** [comment]
I found another Issue, since I don't want to create another issue post, so I updated it here.

Basically, I want to create a new maps, but when I want to uncheck several Industry I can't, even I want to change country style maps it can't be unchecked.

![image](https://github.com/OpenLoco/OpenLoco/assets/98380952/1648f396-2c72-4cdd-b7ac-c8717d701528)
[8bbfdb2c-3c4f-443f-9e7e-de94f7d12594(OpenLoco, v23.08 (d6cfed63 on master))-new.zip](https://github.com/OpenLoco/OpenLoco/files/12565630/8bbfdb2c-3c4f-443f-9e7e-de94f7d12594.OpenLoco.v23.08.d6cfed63.on.master.-new.zip)

DMPfile attached.

**Comment by asbaktemporary** [comment]
**Update**

    Platform: Windows 11
    Version: OpenLoco v23.08
    Build/Commit: d6cfed63

Describe the bug
I found a bug on the tunnel road, for the path created by AI, in the tunnel there are no holes in the road.

![image](https://github.com/OpenLoco/OpenLoco/assets/98380952/8ecb1f10-3332-4977-bde6-fcc2604f17a2)

**Comment by AaronVanGeffen** [comment]
> I found another Issue, since I don't want to create another issue post, so I updated it here.

Thanks, but these issues have no relation to each other. This makes it harder for us to keep track of them.

Please file separate issues for each of these. Thanks.
