### ISSUE TITLE
Company face in object selection window is wrong size

### ISSUE THREAD

**Issue by LeftofZen** [OpenLoco/OpenLoco#2114]
**Version information:**
 - Platform: Win11
 - Version: e.g. 23.08.1
 - Build/commit: 23.08.1

**Describe the bug**
Company face in object selection window is drawn to the wrong size and doesn't fill the available space

**To Reproduce**
Steps to reproduce the behaviour:
1. Load any game/scenario (not the scenerio editor)
2. Open Object Selection window
3. Go to the Company Owners tab, mosueover any company to preview

**Expected behaviour**
Company face is drawn to correct size, as in the Company window

**Screenshots**
![image](https://github.com/OpenLoco/OpenLoco/assets/7483209/2d7a6202-b542-49a1-b5c1-c9e45461017f)

**Additional context**

**Comment by duncanspumpkin** [comment]
Heh, that is odd. The company face selection from the object selection is only visible from the in game object selection and not the scenario editor so i think it likely that CS just never bothered to implement this/check if it worked.

**Comment by dhruvchandak30** [comment]
@duncanspumpkin @LeftofZen   I would like to work on this issue!

**Comment by LeftofZen** [comment]
> @duncanspumpkin @LeftofZen I would like to work on this issue!

By all means, go for it :)

**Comment by dhruvchandak30** [comment]
I have set up the whole environment but got stuck at the last step.
![WhatsApp Image 2023-10-01 at 13 14 10_5087841e](https://github.com/grafana/grafana/assets/116879117/53c9ef8b-78d5-4bb3-b874-f6e06e213967)
It is asking me the directory of the original game files.
![WhatsApp Image 2023-10-01 at 13 14 48_5e10e518](https://github.com/grafana/grafana/assets/116879117/516a6e1e-1d69-4a89-93c9-680f274a2fe3)
But the game can be download only on windows
and It can only be compiled on Linux
![WhatsApp Image 2023-10-01 at 13 13 11_5f7a5bc8](https://github.com/grafana/grafana/assets/116879117/03b70839-71e5-453b-8b09-0e7d385d113d)
So how should I proceed further?

**Comment by duncanspumpkin** [comment]
You download the game on Windows and copy the files over or you download the gog installer version and extract the files. There's also a way to convince the steam version to download the files on Linux but it's a bit more complex.

**Comment by dhruvchandak30** [comment]
@duncanspumpkin  Do I need to purchase the asset files?

**Comment by duncanspumpkin** [comment]
> @duncanspumpkin Do I need to purchase the asset files?

Yes.
