### ISSUE TITLE
INT32_1DP is actually INT32_2DP

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenLoco/OpenLoco#2119]
**Version information:**
 - Platform:  Windows 10
 - Version: all

**Describe the bug**
INT32_1DP in the localisation code is incorrectly named it should be INT32_2DP. To fix will need to update all of the localisation files and adjust the constant in the code (LanguageFiles.cpp)

**Comment by NEJulnes** [comment]
Does this also mean changing various instances of "{COLOUR BLACK}{INT32_1DP}" in the .yml files in data/language?

**Comment by duncanspumpkin** [comment]
> Does this also mean changing various instances of "{COLOUR BLACK}{INT32_1DP}" in the .yml files in data/language?

Yup

**Comment by NEJulnes** [comment]
#2125 Here are my branch's fixes.
