### ISSUE TITLE
New scenario hangs on first tick if custom name set

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenLoco/OpenLoco#2153]
**Version information:**
 - Platform: macOS (via Wine)
 - Version: 23.09+
 - Build/commit: b700424b77cf2d868bb95de7aae77047f3584beb

**Describe the bug**
Starting a new scenario hangs the game on the first tick. We see the viewport and UI rendered, but the game freezes immediately.

Loading save files works fine still.

This also seems to happen on v23.09 for me. I'll investigate more later, but I'd appreciate someone else having a look as well.

**Comment by AaronVanGeffen** [comment]
Caused by fd7ad9258cdaaa855389d34c1f8fcf3634045a5d (#2104).

v23.08 was fine, v23.09 was not. Bisect log:
```
git bisect start
# status: waiting for both good and bad commits
# bad: [b6dd5cdf91496692fe7fce6459739969fc922987] Update version numbers for 23.09
git bisect bad b6dd5cdf91496692fe7fce6459739969fc922987
# status: waiting for good commit(s), bad commit known
# good: [d6cfed6304350149e4ffc09dce97bfcaa973689c] Update version numbers to 23.08
git bisect good d6cfed6304350149e4ffc09dce97bfcaa973689c
# bad: [5eab78d6b3adeb2401679e81f88f5e0f17b3c3c1] Misc static analysis fixes and typos (#2115)
git bisect bad 5eab78d6b3adeb2401679e81f88f5e0f17b3c3c1
# good: [0b9634c323c0e7f7ec0d5fb3b211ab55fbc99fe3] Use game state structure for  trafficHandedness global (#2105)
git bisect good 0b9634c323c0e7f7ec0d5fb3b211ab55fbc99fe3
# good: [ea52d7cc4a41f4cbd979f463c30228ad11732dc2] Implement scroll view thumb update (#2018)
git bisect good ea52d7cc4a41f4cbd979f463c30228ad11732dc2
# bad: [fd7ad9258cdaaa855389d34c1f8fcf3634045a5d] Load Company Face From CompanyName (#2104)
git bisect bad fd7ad9258cdaaa855389d34c1f8fcf3634045a5d
# good: [f538076483f21e7cc27eea21cc847b9fd7b5d34d] Add group boxes to company options tab (#2109)
git bisect good f538076483f21e7cc27eea21cc847b9fd7b5d34d
# first bad commit: [fd7ad9258cdaaa855389d34c1f8fcf3634045a5d] Load Company Face From CompanyName (#2104)
```

**Comment by AaronVanGeffen** [comment]
Issue doesn't occur if the "Use custom company name" is disabled... So that's my workaround for now.

@duncanspumpkin, could you investigate?

**Comment by duncanspumpkin** [comment]
I don't know why it would hang but i've found a mistake in the load company face code introduced by a refactor @ZehMatt made.

**Comment by duncanspumpkin** [comment]
Could be compilers optimising on the mistake causing the hang.
