### ISSUE TITLE
Bug when creating more than one train at once.

### ISSUE THREAD

**Issue by FenderBender2** [OpenLoco/OpenLoco#2162]
**Version information:**
 - Platform: Windows 10
 - Version: 23.10
 - Build/commit: d980351f

**Describe the bug**
I create a new train, place it on the track, assign it destinations, start it and then close the new train's window. I click to create another new train, and I get an error message 'Can't add xxxx to Train yy... Must be stopped first'.

If the first train is stopped, creating a new loco adds this to the end of the first train even though it's window is closed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Build Trains.
2. Click on a new loco.
3. Add some rolling stock.
4. Drop train on the track.
5. Start the train.
6. Close the train window.
7. In the Build Trains window, click on another loco.
8. Error displayed.

**Expected behaviour**
It should start creating a new train after the first train's window has been closed.

**Screenshots**
![image](https://github.com/OpenLoco/OpenLoco/assets/121941598/8e7746d0-c8d7-415c-8b2e-c38a733464b4)

**Comment by duncanspumpkin** [comment]
This will have been caused by https://github.com/OpenLoco/OpenLoco/pull/2148 this was one of the parts of the periodic update.

**Comment by AaronVanGeffen** [comment]
Yep, I was thinking the same thing. I'll look into fixing it.

**Comment by FenderBender2** [comment]
This may be related. I have been creating multiple new trains and in trying to avoid the above issue I found another. Sometimes when creating new trains in sequence, I click to create a new loco but the Train window does not appear, even thought I can see the value of my purchase floating on the screen. When I check my list of trains, the new loco is there with 'No Position'.

**Comment by FenderBender2** [comment]
A workaround I've found for this is to click on one of the tabs in the Build Train/tram etc. window. This seems to reset the 'focus' of the build window:
- If you have the Train Details tab open, the focus is set to this vehicle.
- If not, selecting a component will create a new vehicle.

**Comment by AaronVanGeffen** [comment]
I've proposed a fix in #2240. Could you download a test build from [this page](https://github.com/OpenLoco/OpenLoco/actions/runs/7401178572) ('Artifacts' at the bottom) and check if the bug has indeed been fixed?

**Comment by FenderBender2** [comment]
Thanks Aaron for the pre-release. I've done a test and it looks good to me. I was able to create a new loco, drop it on the tracks and then immediatley create another train. I tried this several times. 👍
