### ISSUE TITLE
Trains turn in station when exit blocked despite pathing instructions

### ISSUE THREAD

**Issue by FenderBender2** [OpenLoco/OpenLoco#2171]
**Version information:**
 - Platform: Windows 10
 - Version: 23.10
 - Build/commit: d980351f
 
**Describe the bug**
I have a very busy 2 track station at a coal mine (Newton Mines in this example). I have a number of trains servicing this station, and each is pathed identically through a number of waypoints. When waiting at this station the trains are pointing 'away' from the destination station at a steel works. If a fully loaded train wants to leave the station and head for waypoint 2 (see screenshot) but finds the path out of the station blocked, it will turn around and try to move out of the station in the wrong direction. This is causing serious hold-ups for following trains.

**To Reproduce**
Steps to reproduce the behaviour:
1. See the layout in the screenshot and attached video.

**Expected behaviour**
Trains heading for waypoint 2 should wait at the platform until the signal clears.

**Screenshots**
![image](https://github.com/OpenLoco/OpenLoco/assets/121941598/9beaa01b-141e-409f-b41c-a32eee049aff)

https://github.com/OpenLoco/OpenLoco/assets/121941598/7a28f450-798f-4ad4-a777-844814f8fcb4

**Comment by LeftofZen** [comment]
You can turn off train reversing in the game options. Does this fix your problem?

**Comment by FenderBender2** [comment]
Yes it does, thanks. 👍

**Comment by LeftofZen** [comment]
Ok great to hear :)
