### ISSUE TITLE
Random crashes v23.10 Windows 10

### ISSUE THREAD

**Issue by FenderBender2** [OpenLoco/OpenLoco#2176]
**Version information:**
 - Platform: Windows 10
 - Version: 23.10
 - Build/commit: d980351f

**Describe the bug**
I get random crashes with the above versions. Sometimes a dump file is produced, sometimes not. I have attached two recent dump files. These _seem_ to be created when I am building new trains, especially when its a few in one go.

P.S. The game crashed while I was executing the steps to reproduce. Dump file uploaded.

**To Reproduce**
Steps to reproduce the behaviour (possibly):
1. Load a saved scenario.
2. Click on an existing train to open the Train dialog box.
3. Open the Build Trains dialog.
4. Select a loco and add some rolling stock.
5. Open the Route tab in the existing train.
6. Open the Route tab in the new Train.
7. Click on the **End of route list** tag on the existing train to copy the whole route to the new train.
8. Drop the new train on the tracks.
9. Repeat until crash. Or perhaps just leave all the dialogs open and wait...

**Expected behaviour**
Game does not crash.

**Screenshots**
N/A

**Dump files**
[6ef45c98-a60f-4490-888d-97b7d6ede92a(OpenLoco, v23.10 (d980351f on master)).dmp](https://github.com/OpenLoco/OpenLoco/files/13256617/6ef45c98-a60f-4490-888d-97b7d6ede92a.OpenLoco.v23.10.d980351f.on.master.dmp)

[144124ae-9c32-4c8b-9912-49e26e14a1db(OpenLoco, v23.10 (d980351f on master)).dmp](https://github.com/OpenLoco/OpenLoco/files/13256619/144124ae-9c32-4c8b-9912-49e26e14a1db.OpenLoco.v23.10.d980351f.on.master.dmp)

**Comment by duncanspumpkin** [comment]
Ahh this might finally be the reproduction steps for a curious crash caused by the routing numbers

**Comment by duncanspumpkin** [comment]
Confirmed that this is https://github.com/OpenLoco/OpenLoco/issues/2111

**Comment by AaronVanGeffen** [comment]
Given we can now reproduce the bug, do you feel #2127 is still an appropriate fix for the issue?

**Comment by duncanspumpkin** [comment]
> Given we can now reproduce the bug, do you feel #2127 is still an appropriate fix for the issue?

I've tried to follow the reproduction steps and i still can't trigger it on my machine. I only tried for ~15minutes following the above steps. I've confirmed its the same bug by looking at the dump file. I think we should merge #2127 for now.

**Comment by FenderBender2** [comment]
It crashes on me all the time. I am using a save game that was created by the vanilla version some time ago, if that has anything to do with it. Its crashing on me constantly,especially, but not limited to, when I am going through a round of upgrading locos. I have to go back to the vamilla version to do the upgrades, then return to OpenLoco when done.

**Comment by duncanspumpkin** [comment]
> I am using a save game that was created by the vanilla version some time ago, if that has anything to do with it. Its crashing on me constantly, especially, but not limited to, when I am going through a round of upgrading locos. I have to go back to the vanilla version to do the upgrades, then return to OpenLoco when done.

The crash will happen when the order page is open. Its to do with the little order numbers that are displayed on the viewport. Would you be able to record a video of exactly what you do when it crashes. Its probably one edge case of setting the orders that I am not following.

**Comment by FenderBender2** [comment]
Typically, I'm having trouble getting it to crash when I'm recording. But to be honest, it can crash at any time that I open the orders tab. Sometimes it has happened when open the tab for the first time after starting the game.

I'll keep trying.

**Comment by FenderBender2** [comment]
I can't find a reliable way to get it to crash. It even went as I as scrolling the view out on one occasion. There were no other windows open in the game and I am running in FullScreen mode.

**Comment by FenderBender2** [comment]
I finally got one!

https://github.com/OpenLoco/OpenLoco/assets/121941598/0d7a54b4-ea3b-49d6-8588-590c7c641906

This one didn't create a dump file.

**Comment by duncanspumpkin** [comment]
Okay i finally understand what the issue is! The ai is inserting/deleting an order and that is invalidating the drawing cache thingy.
