### ISSUE TITLE
Music does not re-start when game unpaused

### ISSUE THREAD

**Issue by FenderBender2** [OpenLoco/OpenLoco#2180]
**Version information:**
- Platform: Windows 10
- Version: 23.10
- Build/commit: d980351f

**Describe the bug**
Music stops on pause and does not start on unpause.

**To Reproduce**
Steps to reproduce the behaviour:
1. Ensure music is playing.
2. Pause the game
3. Unpause the game
4. Music does not re-start. The **Play Music** option is unchecked in the menu.

**Expected behaviour**
Music should re-start with unpausing.

**Screenshots**
Video:  https://github.com/OpenLoco/OpenLoco/assets/121941598/4ddcf95f-4212-4d50-ae9e-cb6d60e24059

**Comment by Streckraupp** [comment]
Been using version 24.01.1 and still having this same issue.

**Comment by ilmoro93** [comment]
I have tested the behaviour on Locomotion and I have seen that the _Play music_ option on the ear menu works differently:
- in Locomotion, when game is paused, the option is still selected
- in OpenLoco it is controlled by a struct member `LocoConfig.musicPlaying` and when the game is paused it is forced to be unselected. This is why the music does not restart on game resume.
