### ISSUE TITLE
Be able to build resource industries in game 

### ISSUE THREAD

**Issue by superchadST345** [OpenLoco/OpenLoco#2192]
I would like to suggest being able to build build resource industries in game such as mines, farms, etc, even if a through a cheat, could probably also allow removing industries as well.

**Comment by AaronVanGeffen** [comment]
This is possible when sandbox mode is enabled. You can find this option in the cheats menu (which you may need to enable in Options, first).

**Comment by superchadST345** [comment]
I don't see that anywhere

**Comment by superchadST345** [comment]
nevermind, found it.
