### ISSUE TITLE
"Hide" visual filters malfunctioning

### ISSUE THREAD

**Issue by abrezovsky** [OpenLoco/OpenLoco#2215]
**Version information:**
 - Platform: Windows 11 22H2
 - Version: 23.11
 - Build/commit: 3f1d349a

**Describe the bug**
"Hide foreground tracks and roads" and "Hide foreground scenery & buildings" only apply to the bottom half of the screen.
When both are selected, "Hide foreground scenery & buildings" is applied and tracks and roads are still visible.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start any scenario
2. Enable either/both "Hide" visual filter(s)

**Expected behaviour**
Hide visual filters should apply to the entire screen. And when both are enabled, both should work properly.

**Screenshots**
![Screenshot 2023-12-07 223425](https://github.com/OpenLoco/OpenLoco/assets/3466262/3c854aa5-3c49-4136-b9d6-8233942ebed4)
![Screenshot 2023-12-07 223403](https://github.com/OpenLoco/OpenLoco/assets/3466262/44e298da-aad2-4041-a0a6-45c302afc2eb)

**Additional context**
Appears to be a bug in the base game as well.

**Comment by duncanspumpkin** [comment]
The half screen part is because this is hide "foreground". We match vanilla for this. The both enabled issue does sound like a bug though.

**Comment by abrezovsky** [comment]
I guess that wording makes more sense now. I still have to ask, why? 
Is there an engine limitation preventing it from applying to the entire screen?
I'm not aware of any filters in RCT that behave like this...

**Comment by AaronVanGeffen** [comment]
We can only speculate as to why it was done originally — perhaps to make it appear more 3D? Personally, I don't like it either. I'd like to change it to be more like (Open)RCT2, but we haven't reimplemented enough of the drawing functions to tackle this yet.

**Comment by abrezovsky** [comment]
Well, I appreciate the quick response, and realize that this is still under development.
