### ISSUE TITLE
Request: macOS app public built (not an issue, sorry)

### ISSUE THREAD

**Issue by iAmRenzo** [OpenLoco/OpenLoco#223]
I am sorry to open an issue, because it isn't really an issue.

I tried to built a macOS app of the source code but it won't work, it is to _difficult_ for me. Is there anyway to put a public built macOS app on the page for people to download?

**Comment by AaronVanGeffen** [comment]
Yeah, it is difficult, with the way dependencies are handled at the moment. We're looking into changing dependency management on macOS, which should also allow us to make builds more easily. Please stay tuned! :)

**Comment by AaronVanGeffen** [comment]
Closing this, as [v19.03](https://github.com/OpenLoco/OpenLoco/releases/tag/v19.03) has since been released with a macOS build. :)
