### ISSUE TITLE
Larger Area for Landscape and Water tool

### ISSUE THREAD

**Issue by superchadST345** [OpenLoco/OpenLoco#2234]
I would love to see a larger area to be supported for the landscaping and water tools, larger in both directions, this would allow for much quicker and easier terrain adjustments both in game (sandbox mode) and scenario editor.

**Comment by AaronVanGeffen** [comment]
This is being implemented by #2228.

**Comment by superchadST345** [comment]
thanks, wasn't aware of this being implemented
