### ISSUE TITLE
Game crashes if loading save game from main menu, but not from new game

### ISSUE THREAD

**Issue by superchadST345** [OpenLoco/OpenLoco#2252]
**Version information:**
 - Windows 11
 - 24.01

**Describe the bug**
If I open OpenLoco and try to load a game from the main menu the game crashes with no error, if I start a new game, and load the game from the new game it loads fine

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the game
2. Click on load game
3. click on game to load
4. crashes with no error log
5. reopen game
6. start new game
7. go to load game
8. loads as expected

**Expected behaviour**
I should be able to load the game from the main menu and not have to create a game first.

**Comment by AaronVanGeffen** [comment]
I'm not able to reproduce this, unfortunately. Does this happen with 23.12 as well?

**Comment by superchadST345** [comment]
No, this only happens with 24.01, I just replaced the game files as well, not very helpful that it doesn't produce a crash log

**Comment by superchadST345** [comment]
Actually got this in Event Viewer

Error
Faulting application name: openloco.exe, version: 4.2.170.0, time stamp: 0x00000000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.2861, time stamp: 0x9e57f18c
Exception code: 0xe06d7363
Fault offset: 0x00149392
Faulting process id: 0x0x9038
Faulting application start time: 0x0x1DA474D4B5B2F37
Faulting application path: C:\Program Files (x86)\OpenLoco\openloco.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 180d4e5c-31c2-4be0-b555-202ad85762dd
Faulting package full name: 
Faulting package-relative application ID: 

Information
Fault bucket 1727084534025518764, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: openloco.exe
P2: 4.2.170.0
P3: 00000000
P4: KERNELBASE.dll
P5: 10.0.22621.2861
P6: 9e57f18c
P7: e06d7363
P8: 00149392
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.488701a4-6a95-48cc-a41a-64bd4dc56e79.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.df23880b-b16e-4f3d-9c18-db6a65a093ac.tmp.WERInternalMetadata.xml
WPR_initiated_DiagTrackMiniLogger_OneTrace_User_Logger_20240113_1_EC_0_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.001f9fd3-c6c7-4939-b2ff-ac491567f4c1.tmp.etl
WPR_initiated_DiagTrackMiniLogger_WPR System Collector_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.684c49ae-b386-4701-939a-9d0998b332ad.tmp.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.f6ffde0e-75cb-464b-b739-55d35fd7685d.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.b2c820c3-978a-4364-a7c1-2293e299be8d.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.5214ece1-b04d-4aff-9611-483db54c1672.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_openloco.exe_dcc990918039107947148e671d2addf95ba6d43_488b9117_58df717c-562a-4919-a64e-6e3c15fc6e1d

Analysis symbol: 
Rechecking for solution: 0
Report Id: 180d4e5c-31c2-4be0-b555-202ad85762dd
Report Status: 268435456
Hashed bucket: 7a387f81032f346f57f7d63bb3a97eac
Cab Guid: 0

**Comment by LeftofZen** [comment]
commit 5deb0ed is the culprit. reverting it makes everything work again

**Comment by FenderBender2** [comment]
Thanks for the swift update. 👍
