### ISSUE TITLE
Zooming to cursor is buggy on bigger maps

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenLoco/OpenLoco#226]
**OS:**  Linux
**Version:**  18.02+
**Commit/Build:**  9c6ff196c6eddbd4d542a2708b2959df766dea92

The new zooming to cursor functionality, adapted from a similar feature I did for OpenRCT2, appears to be broken for bigger coordinates. Investigation is needed to determine why this is happening. Perhaps it is a simple overflow.

**Steps to reproduce:**
1. Generate a Weatherworld map
2. Zoom in and out

**Comment by IntelOrca** [comment]
Locomotion does support bigger maps but not that much bigger. 384x384 I believe, this does mean you should not be using uint8 for map positions.

**Comment by AaronVanGeffen** [comment]
Yeah, we are using `uint16_t`s.
