### ISSUE TITLE
Scroll wheel not working in load/save window

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenLoco/OpenLoco#2287]
**Version information:**
 - Platform: macOS (Wine)
 - Version: 24.01.1+
 - Build/commit: -

**Describe the bug**
Scroll wheel functionality is not working in the load/save window. It is working fine in other windows. Not sure how long this has been broken.

**Comment by superchadST345** [comment]
it's been broken since 23.12, it works in 23.11
