### ISSUE TITLE
Hovercraft seems to like to get stuck spinning in circles

### ISSUE THREAD

**Issue by superchadST345** [OpenLoco/OpenLoco#2302]
**Version information:**
 - Platform: Windows 11
 - Version: 24.02

**Describe the bug**
For some reason it seems that the Hovercraft is very likely to have issues path finding, it often ends up going in circles, other ships don't seem to exhibit this behaviour, and in some routes (such as ones where there is a direct line to the next dock, the hovercraft seems to work properly. stopping and starting will temporarily fix the problem but it coems back

**To Reproduce**
Steps to reproduce the behaviour:
1. build 2 docks that are not a direct line
2. create hovercraft and set them up on the route
3. wait
4. eventually the hovercraft will spin in circles

**Expected behaviour**
The hovercraft should work like the other ships

**Screenshots**
![image](https://github.com/OpenLoco/OpenLoco/assets/6529196/8416fb64-cf3a-4054-9d99-c4e4006f7857)

**Additional context**
I can provide my save game if necessary to help troubleshoot this, i have a pretty much direct route that has hovercrafts that works fine, but on the route where there is a 90 degree turn, they don't work right despite multiple other ships working fine, i have replaced the hovercraft on most just to get the route to work.

**Comment by AaronVanGeffen** [comment]
Isn't this just #2191?

**Comment by superchadST345** [comment]
@AaronVanGeffen I don't know if it's related, in this game the only ships affected in this area are hovercrafts, most hovercrafts where replaced as they work better, in the other issue stopping and starting those ships does not temporarily fix the problem, but it does with the hovercraft.

**Comment by AaronVanGeffen** [comment]
I think the difference between ships is only visual, so I'm going to assume it's the same bug.
