### ISSUE TITLE
Build fails: error: no matching function for call to 'alignTo', etc.

### ISSUE THREAD

**Issue by yurivict** [OpenLoco/OpenLoco#2303]
**Version information:**
 - Platform: FreeBSD 14.0
 - Version: 24.02

**Describe the bug**
```
/usr/ports/games/openloco/work/OpenLoco-24.02/src/Core/src/MemoryStream.cpp:126:40: error: no matching function for call to 'alignTo'
            const auto finalCapacity = alignTo(static_cast<std::size_t>(newCapacity * kGrowthFactor), kPageSize);
                                       ^~~~~~~
/usr/ports/games/openloco/work/OpenLoco-24.02/src/Core/src/MemoryStream.cpp:106:24: note: candidate template ignored: deduced conflicting types for parameter 'T' ('std::size_t' (aka 'unsigned long') vs. 'unsigned int')
    static constexpr T alignTo(T val, T align) noexcept
                       ^
1 error generated.
```

```
/usr/ports/games/openloco/work/OpenLoco-24.02/src/Interop/src/Interop.cpp:310:27: error: cast to 'void *' from smaller integer type 'uint32_t' (aka 'unsigned int') [-Werror,-Wint-to-void-pointer-cast]
        std::memcpy(data, (void*)address, size);
                          ^~~~~~~~~~~~~~
/usr/ports/games/openloco/work/OpenLoco-24.02/src/Interop/src/Interop.cpp:334:21: error: cast to 'void *' from smaller integer type 'uint32_t' (aka 'unsigned int') [-Werror,-Wint-to-void-pointer-cast]
        std::memcpy((void*)address, data, size);
                    ^~~~~~~~~~~~~~
2 errors generated.
```

**Additional context**
clang-14

**Comment by AaronVanGeffen** [comment]
Neither of these sound unsurmountable, however, I am surprised both the errors. Particularly, the `cast to 'void *' from smaller integer type 'uint32_t' (aka 'unsigned int')` error suggests `void*` is larger than 32 bits, i.e. 64 bits. That shouldn't happen on a 32-bit target.

Are you compiling OpenLoco as a 64-bits binary, by any chance? This is currently unsupported, due to us still interfacing with the vanilla game binary while reimplementation is ongoing.

**Comment by yurivict** [comment]
Yes, I am building on amd64 - a 64-bit system.

**Comment by AaronVanGeffen** [comment]
Right, that explains that. This is not supported. You can build OpenLoco as a 32-bit binary, provided FreeBSD provides 32-bit versions of its dependencies. Is that an option for you?

A native 64-bit build won't be supported in the immediate future, as it depends on the entire game having been reimplemented.

**Comment by yurivict** [comment]
32-bit dependencies would be cross-platform, and are not immediately supported.

We'd wait for the 64-bit systems to be supported.

**Comment by AaronVanGeffen** [comment]
Alright, then I'm closing this, as we cannot support 64-bit systems natively at present.
