### ISSUE TITLE
I can build track that already exists at stations

### ISSUE THREAD

**Issue by FenderBender2** [OpenLoco/OpenLoco#2309]
**Version information:**
 - Platform: Windows 10
 - Version: 24.02
 - Build/commit: 5665224b on master

**Describe the bug**
I can build new (straight) track where it already exists. It seems to happen near/in stations. I've tested as far back as 23.05.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a short piece of new straight track.
2. Add a station to it, but leave the first section of track without a station piece
3. Right click on the empty piece of track, with new track to be built through the station.
4. Build more track.

**Expected behaviour**
You should not be able to build track where it already exists.

**Screenshots**

![track](https://github.com/OpenLoco/OpenLoco/assets/121941598/16b96104-b2de-499b-b311-4a98241e4283)

https://github.com/OpenLoco/OpenLoco/assets/121941598/0bd988a9-df52-4846-b495-b7ac930e7b72

**Comment by FenderBender2** [comment]
I'll upload a video shortly.

**Comment by FenderBender2** [comment]
Video added.

**Comment by FenderBender2** [comment]
Is this related? Houses being build in my stations!

![House](https://github.com/OpenLoco/OpenLoco/assets/121941598/e43b4ba0-46e2-4f4d-a07b-43f9d76b29bc)

**Comment by AaronVanGeffen** [comment]
Yes, new station elements don't have a clearance height set. In other words, they have no height to conflict with. 

There will be .1 hotfix soon, probably tomorrow. That won't fix existing elements, unfortunately.

**Comment by FenderBender2** [comment]
Thanks guys.

**Comment by FenderBender2** [comment]
Sorry, I know the ticket is closed but I just thought I'd share this as I find it hilarious. 😄 

![town2](https://github.com/OpenLoco/OpenLoco/assets/121941598/06be5b70-88e6-40c0-9091-3cf4f66290c6)
