### ISSUE TITLE
(Minor) News box is behaving strangely

### ISSUE THREAD

**Issue by FenderBender2** [OpenLoco/OpenLoco#2316]
**Version information:**
 - Platform: Windows 10
 - Version: 24.02.1
 - Build/commit: 8e40251e

**Describe the bug**
The pop-up news box has developed a couple of bugs. One is that a small strip of the box is not rendered, leaving a 'window' on the landscape behind.

Also, when new vehicles are announced, the 3D images spin erratically or not at all, and the image gets corrupted.

**To Reproduce**
1. Wait for a pop-up news box to appear announcing new vehicles.

**Expected behaviour**
Previous versions seemed to work ok.

**Screenshots**

![spinner](https://github.com/OpenLoco/OpenLoco/assets/121941598/a3e75944-6778-48c3-8f4c-98968cd8562f)

**Comment by AaronVanGeffen** [comment]
Thanks for taking the time to file an issue.  Sounds like what we call an invalidation problem. Will have to see what's wrong.
