### ISSUE TITLE
Vehicles do not rotate in annoucement for their invention

### ISSUE THREAD

**Issue by LeftofZen** [OpenLoco/OpenLoco#2321]
**Version information:**
 - Platform: Win11
 - Version: e.g. 24.02.1
 - Build/commit: master

**Describe the bug**
When a vehicle is 'invented', an announcement happens in-game. In this announcement, the vehicle is supposed to have an animated rotation, just like the vehicle creation window. However the vehicle does not currently rotate.

**To Reproduce**
Steps to reproduce the behaviour:
1. Wait for a vehicle to be invented (I did this by turning on the vehicle cheat to display locked vehicles, look at the invention year for a locked vehicle, and then set the date to Dec 31 of the previous year via the date cheat, then play the game)
2. Look at the announcement pane.

**Expected behaviour**
Vehicle rotates in announcement pane

**Screenshots**
https://youtu.be/ScPgj-AUeEg

**Additional context**
I noticed that *sometimes*, the vehicle *does* rotate, but only partially. You can also rapidly 'mouse-over' the window to force an invalidation, and the vehicle does rotate as seen in the linked video. This leads me to believe its an invalidation issue (is the announcement pane simply not calling invalidate() at the end of each frame?) and not a 'update' issue.

**Comment by AaronVanGeffen** [comment]
Probably related to #2316
