### ISSUE TITLE
Rework any void* string function arguments

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenLoco/OpenLoco#2342]
There are a number of string functions that take a `void*` for their final `args` argument. These should take a `const FormatArguments&` instead, e.g.:

https://github.com/OpenLoco/OpenLoco/blob/f1abcfc5d94199c0eeb62eaaf8dd2c8d21f5d1cd/src/OpenLoco/src/Drawing/SoftwareDrawingContext.h#L24-L31 

Please note not just the signatures need changing. The calling functions will need to be adjusted as well.

**Comment by AaronVanGeffen** [comment]
I think I'll tackle this in #2348 as well.

**Comment by AaronVanGeffen** [comment]
This is being handled in #2464
