### ISSUE TITLE
Set date cheat is broken

### ISSUE THREAD

**Issue by LeftofZen** [OpenLoco/OpenLoco#2350]
**Version information:**
 - Platform: Windows 11
 - Version: master
 - Build/commit: 9fc7cc44c769e76d8287af426abc9169b94e20d5

**Describe the bug**
24.02.1 has no issue so it much have been broken very recently.

When cheat window "Set date" is called:
![image](https://github.com/OpenLoco/OpenLoco/assets/7483209/efe753b7-7c1d-4fad-b9d5-4d7c745fed82)

When game command is processed:
![image](https://github.com/OpenLoco/OpenLoco/assets/7483209/e123c383-9aa1-4abd-8e11-991c4ddbe8a2)

**To Reproduce**
Steps to reproduce the behaviour:
1. Use the set date cheat to switch to any year

**Expected behaviour**
Cheat sets correct date

**Screenshots**
see above

**Additional context**
Potentially caused by #2319

**Comment by AaronVanGeffen** [comment]
Thanks for logging an issue. I read into it while testing as well, but found it was already broken on a previous release build. Could you confirm?

**Comment by LeftofZen** [comment]
- works in `b078918152a135696af179c59cc6cc3ad484ea33`
- fails in `81b9afe77ef7a6351b0178b2cf4f6623a3137598` (which is #2319)
- 
the issue is in the previous code, regs.bl is set first, THEN regs.ebx is set. this essentially clobbers bl but ensures the params are correct. in the new code, regs.bl is set AFTER, which clobbers the year which is in ebx. Why are we even setting both bl and ebx, knowing that one will clobber the other?

**Comment by duncanspumpkin** [comment]
bl should never be used for any command arguments it is always the flags. It should have used edx not ebx.
