### ISSUE TITLE
Unable to create stations 16 tiles long in certain circumstances

### ISSUE THREAD

**Issue by FenderBender2** [OpenLoco/OpenLoco#2372]
**Version information:**
 - Platform: Windows 10
 - Version: 24.03
 - Build/commit: f0863a0c

**Describe the bug**
I'm getting a lot of 'Station too spread out' messages building vanilla-size stations (16x5 tiles), particularly when a new station is stacked on other stations.

I note from the changelog that the station sizing has been addressed in this release.

**To Reproduce**

1. In my example, I create a station in the normal manner.
2. I then build another station over the first.
3. I get the station too spread out error when I try to place the 16th tile.

**Expected behaviour**
Allow standard size stations to be built.

**Screenshots**
**24.03**
![station1](https://github.com/OpenLoco/OpenLoco/assets/121941598/98cc79e1-3556-4d4b-81eb-6104fd74f2c2)

**24.02.1**
![station2](https://github.com/OpenLoco/OpenLoco/assets/121941598/37f8a721-d992-44e8-bd17-928119900685)

**Comment by FenderBender2** [comment]
This appears to be the only way to create a station using maximum tiles with one platform 16 tiles long.  

![image](https://github.com/OpenLoco/OpenLoco/assets/121941598/cea8c2fd-de54-4fee-bc19-b126bfe366d5)

**Comment by AaronVanGeffen** [comment]
Sounds like the radial check isn't quite correct (StationManager::exceedsStationSize). Will have to investigate.

**Comment by FenderBender2** [comment]
Thanks. 👍

**Comment by alpeshpatel09** [comment]
Hi @AaronVanGeffen 

Please provide steps to the following : You could workaround the bug by disabling the station limits.

Thank you.

**Comment by AaronVanGeffen** [comment]
The station length limit can be disabled in the options window. The last tab (misc options) contains this option, amongst others.
