### ISSUE TITLE
Disabled height markers re-appear when clicking Slope-Up or Slope-Down buttons in track building window.

### ISSUE THREAD

**Issue by aultuser** [OpenLoco/OpenLoco#2374]
**Version information:**
 - Platform: Windows 7
 - Version: v24.02.1
 - Build/commit: 8e40251

**Describe the bug**
- Height markers re-appear when clicking Slope-Up or Slope-Down buttons in track building window.

**To Reproduce**
- Turn off ground height markers using the top menu.
- Click on the end of a railroad track to begin building the next piece.
- Immediately after clicking the Slope-Up or Slope-Down icon buttons in the building window, the height markers all re-appear on the map.

**Expected behaviour**
- After disabling ground height markers, the markers should remain disabled unless re-enabled by the user.

**Additional context**
- The issue seemed to appear, after the inclusion of the new feature for separate menu items related to disabling / enabling various height markers independently.

- Additionally, an aspect which may point to the issue, is that the intended / correct track-height markers, are not activated when selecting the Slope-Up or Slope-Down buttons, but instead the ground-height markers turn on.  Perhaps the ground-height markers are activating by mistake, instead of the track-height markers.

**Comment by LeftofZen** [comment]
@AaronVanGeffen sounds like this https://github.com/OpenLoco/OpenLoco/pull/2231 may have introduced this bug?

**Comment by AaronVanGeffen** [comment]
I think you're right. It also means `ViewportVisibility::heightMarksOnLand` is wrong, and should be named `ViewportVisibility::heightMarksOnTrack` instead.
