### ISSUE TITLE
Text box cursor indicator stuck to left side

### ISSUE THREAD

**Issue by w0lfman2164** [OpenLoco/OpenLoco#2379]
**Version information:**
 - Platform: Windows 10
 - Version: 24.03
 - Build/commit: f0863a0c

**Describe the bug**
In all (have yet to find one where this doesn't happen) text boxes, the cursor indicator is rendered at the far left despite the actual position of the indicator.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any text box i
2. Type, edit, or move the cursor
3. See error

**Expected behaviour**
Cursor indicator should render in the position where the cursor is.

**Screenshots**

https://github.com/OpenLoco/OpenLoco/assets/165536747/14a8144a-8e63-43bd-a8bb-9d1f20f97d47

**Additional context**
Doesn't effect functionality, simply visual.

**Comment by AaronVanGeffen** [comment]
Thanks for reporting. This is likely a regression from my recent drawString refactor.
