### ISSUE TITLE
Rail vehicles have constant sound + trams with train bogey sound

### ISSUE THREAD

**Issue by Zcooger** [OpenLoco/OpenLoco#239]
Slow down sounds are bugged. Once it happened that the tram has the sound of a diesel locomotive. Video examples attached.

**OS:**  Windows 7 Pro x64
**Version:**  18.02-422
**Commit/Build:**  6f8fde1
**Screenshots / Video:**
[issue_239.zip](https://github.com/OpenRCT2/OpenLoco/files/2453306/issue_239.zip)

**Comment by dylansan** [comment]
I would like to add more details to this:

**OS:**  Windows 7
**Version:**  19.03

Vehicles in OpenLoco are not respecting their sound variables which determine the sampling rate of their sounds. They should be changing pitch when accelerating/decelerating, but instead they keep a constant pitch/sampling rate.

**Is the issue reproducible in Locomotion (vanilla)?**
No. In vanilla, the speed/pitch of vehicle sounds change during acceleration, or under load, according to the different values described [here](https://www.tt-wiki.net/wiki/Variable:driving_noise). For example, a locomotive with a startsndtype of 2, and different values for sampling rate under no-load, load, and full load, will change pitch as it accelerates. This is especially easy to hear if the startsnd is something rhythmic, like a steam engine (such as the one available [here](https://www.tt-forums.net/viewtopic.php?f=40&t=48694&hilit=sound)). Not only does the pitch change, but the speed of the "chug" does too. In OpenLoco, there doesn't seem to be any change at all, except for volume, which seems to work as expected.

**Comment by AaronVanGeffen** [comment]
I believe this has been resolved. @Zcooger, could you confirm?
