### ISSUE TITLE
Issue building AUR/Arch package for missing DEVELOPMENTLOG.md

### ISSUE THREAD

**Issue by FabioLolix** [OpenLoco/OpenLoco#2391]
**Version information:**
 - Platform: Arch Linux
 - Version: 24.03, 24.02.1, last commit
 - Build/commit: N/A

**Describe the bug**

Hello, I'm the maintainer of the openloco AUR pkgbuild, between v23.12 and v24.02.1 DEVELOPMENTLOG.md have been deleted and is no longer possible to build the package

```
-- Installing: /home/fabio/Dev/Github/PKGBUILD-AUR_fix/o/openloco/pkg/openloco/usr/share/doc/openloco/CHANGELOG.md
CMake Error at build/cmake_install.cmake:71 (file):
  file INSTALL cannot find
  "/home/fabio/Dev/Github/PKGBUILD-AUR_fix/o/openloco/src/OpenLoco-24.03/DEVELOPMENTLOG.md":
  No such file or directory.


==> ERROR: A failure occurred in package().
```

There is also this warning (LTO is disabled):

```
[ 10%] Linking CXX executable CoreTests
/usr/bin/ld: CMakeFiles/CoreTests.dir/tests/FileStreamTests.cpp.o: in function `getTempFilePath()':
FileStreamTests.cpp:(.text+0xe9): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
[ 10%] Built target CoreTests
[ 10%] Linking CXX static library libDiagnostics.a
```

**To Reproduce**
Steps to reproduce the behaviour:

* Install Arch Linux (or a close derivate)
* install `base-devel` package `sudo pacman -Syu base-devel git --needed`
* grab updated pkgbuild not on AUR `git clone https://github.com/FabioLolix/PKGBUILD-AUR_fix`
* `cd PKGBUILD-AUR_fix/o/openloco`
* `makepkg -s`

**Expected behaviour**

**Screenshots**

**Additional context**

**Comment by AaronVanGeffen** [comment]
Thanks for the report. The file was deliberately deleted this February, but it seems a reference to it was overlooked. I've filed a proposal to remove it in #2392.
