### ISSUE TITLE
Sound clipping while constructing with Shift key

### ISSUE THREAD

**Issue by Zcooger** [OpenLoco/OpenLoco#240]
Building, demolition and error sound effects are played multiple times at once. It causes sound clipping and may affect performance. Video examples attached.

**OS:**  Windows 7 Pro x64
**Version:**  18.02-422
**Commit/Build:**  6f8fde1
**Screenshots / Video:**
[issue_240.zip](https://github.com/OpenRCT2/OpenLoco/files/2453309/issue_240.zip)

**Comment by AaronVanGeffen** [comment]
Has this been resolved in the mean time?
