### ISSUE TITLE
Improper screen mode switching on Windows

### ISSUE THREAD

**Issue by Zcooger** [OpenLoco/OpenLoco#241]
Full screen resolution depends on the diagonal of the window. Selection box does not work at all. Checkbox options may have too wide hitbox. Video examples attached.

OS: Windows 7 Pro x64
Version: 18.02-422
Commit/Build: 6f8fde1
Screenshots / Video:
[issue_241.zip](https://github.com/OpenRCT2/OpenLoco/files/2453317/issue_241.zip)

**Comment by AaronVanGeffen** [comment]
I believe this has been resolved since fullscreen support was added back in v19.03. Closing this.
