### ISSUE TITLE
Scenario editor: Can't change name of existing scenario

### ISSUE THREAD

**Issue by Sebazzz** [OpenLoco/OpenLoco#2441]
**Version information:**
 - Platform: Windows 11
 - Version: 24.04+ (master) @ b1293bd6a6954488737801b93cc9205a9844436e
 - Build/commit: b1293bd6a6954488737801b93cc9205a9844436e

**Describe the bug**
Scenario name can be changed, but doesn't actually save.

**To Reproduce**
Steps to reproduce the behaviour:
1. Make a scenario
2. Attempt to change the name

![2024-04-13_18-30-31](https://github.com/OpenLoco/OpenLoco/assets/1426097/5ce50a60-2849-4acf-bb53-2cb5af52134d)

Notice how the name isn't actually updated, and when saving it eventually ends up with whatever the original name was.

**Screenshots**
![image](https://github.com/OpenLoco/OpenLoco/assets/1426097/7bdcc97a-fab6-48c4-b77d-a6f49ae64575)

**Additional context**
I haven't looked into the cause yet.

**Comment by AaronVanGeffen** [comment]
This might just be due to inadvertently copying the S5::Options struct rather than taking a ref.

**Comment by AaronVanGeffen** [comment]
Text input is actually working properly for me locally, but I think I see what's wrong. You opened an existing scenario to edit, correct? The built-in scenarios have a so-called scenario text object attached to them to help localise the texts. These objects will override anything you input manually.

A solution to this could be to unlink the scenario text object once any manual input is given.

**Comment by Sebazzz** [comment]
I didn't recall doing that, but I retested and indeed it seems to be related to selecting an existing scenario description (not necessarily editing an existing scenario):

![image](https://github.com/OpenLoco/OpenLoco/assets/1426097/482f98db-80b0-4a8b-89e3-e6f1b4a00ce8)
