### ISSUE TITLE
Removal of structures

### ISSUE THREAD

**Issue by alpeshpatel09** [OpenLoco/OpenLoco#2463]
**Version information:**
 - Platform: Windows 11
 - Version: 24.04
 - Build/commit: [e.g. f08479f]

**Describe the bug**

Unable to remove structures such as Pylons

**Expected behaviour**

**Screenshots**

**Additional context**

**Comment by LeftofZen** [comment]
I thought you couldn't remove those structures in vanilla, and there's a flag in the building object to mark destructible/non destructible objects; can you check if this is the case?

**Comment by alpeshpatel09** [comment]
Hi LeftofZen

Please can you advise where I can check the flag as unsure of what file/s I need to check or screen.

Thank you

**Comment by LeftofZen** [comment]
> Hi LeftofZen
> 
> Please can you advise where I can check the flag as unsure of what file/s I need to check or screen.
> 
> Thank you

Ah sorry I just wanted you to confirm the behaviour in-game. You can see the flag in the object editor:
![image](https://github.com/OpenLoco/OpenLoco/assets/7483209/26085634-039d-458a-97fe-e268dc18daf7)

**Comment by LeftofZen** [comment]
Thinking about this, we could certainly add a very basic cheat that lets the user ignore the "Indestructible" flag

**Comment by AaronVanGeffen** [comment]
We wouldn't even need a new one. With the removeBuilding game command implemented, we could just make it take the 'sandbox mode' flag into account.

**Comment by LeftofZen** [comment]
Oh yeah good point, that's definitely a better way to do it

**Comment by alpeshpatel09** [comment]
Thank you for the updates - good idea to use the current sandbox mode.
