### ISSUE TITLE
Crash on load up of Scenario with missing Objects

### ISSUE THREAD

**Issue by glenjimen** [OpenLoco/OpenLoco#2472]
**Version information:**
 - Platform: Win10
 - Version: 24.05
 - Build/commit: ee73442b

**Describe the bug**
If you try to load a new or saved game and do not have all the required objects in your objdata folder, the game will crash.  In previous versions it would display a message window "Error Loading Objects".  The new loading bar is approximately 1/2 way across when the game freezes and crashes. 

**To Reproduce**
Steps to reproduce the behaviour:
Load a game that requires mods, with a vanilla objdata folder.

**Expected behaviour**
Loading stops and the "Error Loading Objects" window appears, listing what objects you are missing.

**Screenshots**
The loading bar shows : installing USPCCSRA.DAT, and I do have that one in my objdata folder.
![locoErrorMissingObject](https://github.com/OpenLoco/OpenLoco/assets/51429904/0139938a-98d7-4147-8ab8-dc51646c3656)

**Additional context**
Crash Dump:
https://drive.google.com/file/d/1Pc-AhQ196YjIma1eGkGallZNbalroInB/view?usp=sharing

**Comment by AaronVanGeffen** [comment]
This should be fixed in v24.05.1. Could you confirm?

**Comment by glenjimen** [comment]
Yes, I just tested this, and the crash is fixed.  The blue "Error Loading Objects" window pops up and shows the objects correctly.  

The only difference is that the console window no longer prints the missing objects.  Usually it shows in red "Failed to Load: OBJECTNAME"  This was handy to copy & paste the missing objects to a text file for reference later.  

That difference aside, yes the crash is solved!  Thank you!

**Comment by glenjimen** [comment]
Never-mind, the console still outputs the missing objects.  I ran it from the combo RCT2 / Loco launcher, and that's when the missing objects didn't print.
