### ISSUE TITLE
Don't show loading bar every Month

### ISSUE THREAD

**Issue by glenjimen** [OpenLoco/OpenLoco#2473]
**Describe the solution you'd like**
I mentioned this on discord, so I'll make a quick request here too.  Feel free to ignore this one ;-)  
Having the bar appear suddenly center-screen every month is a bit jarring, and not vanilla behavior.  The loading time is very quick, so I would prefer the loading bar not be visible in this instance. 

**Describe alternatives you've considered**
Leave it as is.  It's not really a problem.   If it's helpful for development, please do leave it.

**Additional context**
The time I played LAN multiplayer and both players did not have identical objData folders, that loading bar did appear every month.  Halfway thru we synced objdata folders, and that made the loading bar stop showing every month.

**Comment by AaronVanGeffen** [comment]
This is the autosave kicking in. I agree it would be better to hide it though.
