### ISSUE TITLE
Can't move minimap with right mouse button

### ISSUE THREAD

**Issue by kiwitreekor** [OpenLoco/OpenLoco#249]
**OS:**  Windows 10
**Version:**  18.02-438
**Commit/Build:**  4e0e561

Can't move minimap with right mouse button. 

**Steps to reproduce:**
1. Open minimap.
2. Drag the minimap with right mouse button.

**Is the issue reproducible in Locomotion (vanilla)?**
No.

**Comment by Zcooger** [comment]
The same on 6f8fde1, windows 7.

**Comment by kiwitreekor** [comment]
It's fixed now, in 21.03.
