### ISSUE TITLE
Copy all destinations from one vehicle to another

### ISSUE THREAD

**Issue by alpeshpatel09** [OpenLoco/OpenLoco#2497]
**Describe the solution you'd like**
Currently a vehicle can be cloned, however if a new vehicle is created then orders need to be added.  Can a button be introduced to copy all orders instead of having to click through each one to add it?

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by LeftofZen** [comment]
Vanilla has a copy-paste orders mechanic already. Granted it's not intuitive in the slightest, but it does exist and is exactly what you want:

1. Select the train window of the vehicle with empty orders (ie the destination for the copy/paste). In this case, have the right train/window selected.
![image](https://github.com/OpenLoco/OpenLoco/assets/7483209/0d3086ac-aa4b-4b41-8383-33b93f2cba87)
2. Click the `End of route list` line in vehicle whose orders you want to copy from (ie the source for the copy/paste)
![image](https://github.com/OpenLoco/OpenLoco/assets/7483209/4f4aa3ad-be5d-4e72-a4fa-d40386ff1903)
3. Voila, the orders are copied:
![image](https://github.com/OpenLoco/OpenLoco/assets/7483209/2dd89c68-e4d7-4898-9f7b-480650728eff)
