### ISSUE TITLE
Opening an older saved game in 24.06 crashes the game

### ISSUE THREAD

**Issue by FenderBender2** [OpenLoco/OpenLoco#2520]
**Version information:**
 - Platform: Windows 10
 - Version: 24.06
 - Build/commit: 2a8156bd

**Describe the bug**
Opening a save game crashes with "_Exception 'Malformed vehicle. Incorrect subType!', thrown at 'as' - src\OpenLoco\src\Vehicles/Vehicle.h:217_"

**To Reproduce**
Steps to reproduce the behaviour:
1. Start verson 24.06 of the game.
2. Load a game saved by a previous version of the game (only tested with 24.05.1)
3. Error appears in a dialog box and also in the runtime window.

**Expected behaviour**
No crash on load

**Screenshots**
![image](https://github.com/OpenLoco/OpenLoco/assets/121941598/00b90d39-082f-4d2f-9409-0c5f8034f4f8)

**Workaround**
Create a new game first, then load a game from the in game menu

**Comment by FenderBender2** [comment]
This is now happening on new game saves in a newly created scenario. Is this happeneing to any on else?

**Comment by LeftofZen** [comment]
I've gotten this exactly once, and it wasn't reproducible on the same map/savegame, its a strange one

**Comment by duncanspumpkin** [comment]
I have also had this happen once. I can't reliably reproduce it though

**Comment by FenderBender2** [comment]
I've done a bit of a test and I think its because I'm using a custom scenario. I created this one in 2020 and I've used it through the time I've had OpenLoco.

[Pete Challenge #3.zip](https://github.com/user-attachments/files/16323361/Pete.Challenge.3.zip)

**Comment by LeftofZen** [comment]
@FenderBender2 I have no issues loading that scenario up in 24.06. The error you are getting is from a bad vehicle structure - there are no vehicles in the scenario; can you upload a savegame please?

**Comment by FenderBender2** [comment]
Hi @LeftofZen. The issue is when I start the scenario, create a train or two then save the game. On re-loading the game it throws the error.

[Pete Challenge #3-6.zip](https://github.com/user-attachments/files/16325354/Pete.Challenge.3-6.zip)

**Comment by LeftofZen** [comment]
hmm i get no issues with loading it up in 24.06 or in the debugger on master, or on starting the new scenario, making trains, saving, then reloading.

i'm on win11 - it *may* be a win10 thing but it seems unlikely. 

this is not gonna be a fun one to figure out :( and it may involve first making better error messages and logging changes to vehicle state to try to trace how its getting corrupt on the off-chances when it does happen

**Comment by duncanspumpkin** [comment]
When i had it crash i swear it was loading a save that had no vehicles. I almost think it might be something to do with the gamestate that is unloading and not the gamestate that is loading.

**Comment by duncanspumpkin** [comment]
So this was a fun one to work out. You need to load the save from the title screen but when the title screen has audio playing vehicles. You also need to be loading a save that has vehicles but vehicles that are a different length to the ones in the title screen. And if you satisfy those requirements, CRASH!

**Comment by FenderBender2** [comment]
@duncanspumpkin, thanks for tracking that one down and making me realise I'm not going mad.
