### ISSUE TITLE
Minor visual bugs in 23.12+ with bogeys and train/track draw order

### ISSUE THREAD

**Issue by LeftofZen** [OpenLoco/OpenLoco#2540]
**Version information:**
 - Platform: Win11
 - Version: 23.12+
 - Build/commit: haven't checked further

**Describe the bug**
[Video here](https://youtu.be/JbX_YD3qWFo)
Bug 1: Bogeys are not rendering on every 2nd frame for some of the trains, making them appear to flash. You will need to slow down the youtube video to 0.25x speed to see this, but in-game in real time its quite obvious.
Bug 2: On the start of the large curve, the curve track is drawn over the train. Can be see around 10s into the video on the 2 trains on the far left of the screen.

**To Reproduce**
Just set up the map/trains like in the video.

**Expected behaviour**
Train and bogeys renders correctly as per 23.11-

**Screenshots**
See videos!

**Additional context**
Seems to be around the time a lot of track drawing functions were implemented.

**Comment by duncanspumpkin** [comment]
Bug2 i think can be marked as done as it was #2655.

**Comment by LeftofZen** [comment]
Fixed in #2658
