### ISSUE TITLE
Tunnels have no entrance at the end of curved sections,

### ISSUE THREAD

**Issue by FenderBender2** [OpenLoco/OpenLoco#2574]
**Version information:**
 - Platform: Windows 10
 - Version: 24.07
 - Build/commit: d5608cc2

**Describe the bug**
Tunnel entrances are not drawn when the entrance is against a curve on the inside of the tunnel

**To Reproduce**
Steps to reproduce the behaviour:
Create a section of underground track where the exit of the tunnel is at the end of a curve.

**Expected behaviour**
Draw the tunnel entrance.

**Screenshots**
![image](https://github.com/user-attachments/assets/cfed6f12-605b-4bfd-9504-16f98e4bfcf9)

![image](https://github.com/user-attachments/assets/4576ff27-1aa0-4098-a813-818a7c298cfc)

**Comment by duncanspumpkin** [comment]
Is this vanilla behaviour or exclusive to openloco

**Comment by FenderBender2** [comment]
Openloco it seems. This is vanilla:

![image](https://github.com/user-attachments/assets/fb63084a-0530-48dd-8f05-0ba0adf73b4a)

**Comment by FenderBender2** [comment]
BTW, I let me know if I need to raise an issue for this, but when I ran my scenario in vanilla, a raft of new industries started to be built. Is the algorithm for new construction in OpenLoco different to vanilla?

![image](https://github.com/user-attachments/assets/1d5bb894-7a49-4838-9623-d7e931e59d9e)

**Comment by duncanspumpkin** [comment]
It shouldn't be different but the seed will diverge so you can't expect identical results. I was pretty sure I had worked out all the issues with industry creation though. So its very hard to be sure if its a mistake or not.
