### ISSUE TITLE
Height marks on land are incorrect

### ISSUE THREAD

**Issue by FenderBender2** [OpenLoco/OpenLoco#2575]
**Version information:**
 - Platform: Windows 10
 - Version: 24.07
 - Build/commit: d5608cc2

**Describe the bug**
Land height marks are wrong.

**To Reproduce**
Steps to reproduce the behaviour:
1. Switch on Height Marks On Land.
2. See screenshot

**Expected behaviour**
Height marks should be correct

**Screenshots**
![image](https://github.com/user-attachments/assets/f562d44b-970b-4e0e-94ec-ea0d9e16e56c)

**Comment by duncanspumpkin** [comment]
This is already addressed and will be in the next release
