### ISSUE TITLE
Turning off new message SFX reverts after exiting scenario

### ISSUE THREAD

**Issue by Derpercoaster** [OpenLoco/OpenLoco#2576]
**Version information:**
 - Platform: Windows 10
 - Version: 24.07
 - Build/commit: d5608cc2

**Describe the bug**
There is an option to turn off the SFX when new messages appear. However, if you do turn it off, the change reverts itself after you leave the scenario you're playing and start a new one.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start any scenario
2. Turn off message SFX in message menu
3. Leave scenario
4. Return to scenario. The option will have turned itself back on.

**Expected behaviour**
Changing an option should not self-revert for any reason.

**Comment by AaronVanGeffen** [comment]
From MessageWindow.cpp:
```cpp
case widx::playSoundEffects:
{
    Config::get().audio.playNewsSounds ^= 1;
    WindowManager::invalidateWidget(WindowType::messages, self.number, widgetIndex);
    break;
}
```

The config is updated, but not saved. This means the option will indeed revert when the config is reloaded, unless the config has been saved via other means in the mean time.
