### ISSUE TITLE
Certain industries get razed by a ghost

### ISSUE THREAD

**Issue by LeftofZen** [OpenLoco/OpenLoco#2592]
**Version information:**
 - Platform: Win11, Proton Linux
 - Version: 24.08
 - Build/commit: release

**Describe the bug**
Very specific industries get destroyed by moving a ghost industry over/near them.

**To Reproduce**

1. Start new game, select scenario (I'll use Swiss Alps - 100 Year Challenge for the example, so far NA (Midwest) 100 Year works too),
2. If on the Swiss Alps scenario, go to"Olten Vineyard"
3. Open Industries page, click Fund New Industries tab
4. Move cursor onto main viewport, observe as Olten Vineyard poofs out of existence. 

**Expected behaviour**
Industry does not get nuked

**Screenshots**

**Additional context**
- Reported by Discord user `ashley_0295` aka `Ashley`
- Also works for "Winnipeg Farm" on Midwest 100 Year, haven't identified any more.
- Caused by https://github.com/OpenLoco/OpenLoco/commit/55c0a4351759ec3cf274d7a53e3cddd1db8fdcac
- Reverting the industry ghost loco_global changes in IndustryList.cpp fixes the issue, ie we need to undo this change:
![image](https://github.com/user-attachments/assets/dab417aa-80cd-4eae-b86e-028833251a8b)

**Comment by duncanspumpkin** [comment]
Likely means that something needs to be hooked/implemented as it's using globals we have removed.

**Comment by duncanspumpkin** [comment]
Ahh i see the issue. It removed a global it shouldn't have just yet.
