### ISSUE TITLE
Crash when using Sandbox Mode to place Coal Mine

### ISSUE THREAD

**Issue by SteveEmfore** [OpenLoco/OpenLoco#2611]
**Version information:**
 - Platform: [e.g. Windows 11]
 - Version: [e.g. 24.08]
 - Build/commit: [e.g. f08479f]

**Describe the bug**
I was manually placing a coal mine on Boulder Breakers and had the "ghost industry" bug, I deleted the ghost industry and then a few seconds later it crashed.

**To Reproduce**
Place coal mine, press backspace to generate ghost industry. Go to Industries and press delete on the ghost industry.

**Expected behaviour**

**Screenshots**
![image](https://github.com/user-attachments/assets/843a8a73-ea04-4770-a4fc-67d7d0b021db)

**Additional context**
Added .DMP file and .SV5 file not long before crash.
[Uploading e6a330d1-43ea-4a2b-864d-56ab0554dc9e(OpenLoco, v24.08 (40e9b7bf on master)).dmp…]()
[Uploading Boulder Breakers pre crash.SV5…]()

**Comment by SteveEmfore** [comment]
It seems I wasn't allowed to upload the .SV5

**Comment by SteveEmfore** [comment]
Addition: Here's the save.
[Boulder Breakers pre crash.zip](https://github.com/user-attachments/files/16797846/Boulder.Breakers.pre.crash.zip)

**Comment by AaronVanGeffen** [comment]
Likely to be the same issue as #2592.

**Comment by duncanspumpkin** [comment]
Yes this is the same issue.
