### ISSUE TITLE
Game crashes when trying to modify train

### ISSUE THREAD

**Issue by gdiniz95** [OpenLoco/OpenLoco#2628]
**Version information:**
 - Platform: Windows 11
 - Version: 24.09.1
 - Build/commit: (i don't know how to check this)

**Describe the bug**
When I try to modify a train (especially when I'm removing all cars and adding new ones) the game crashes and closes

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any train
2. Try to modify the train by deleting all current cars and adding new ones.
3. Game freezes and crashes

**Additional context**
Save file uploaded.
[East.zip](https://github.com/user-attachments/files/17004017/East.zip)

**Comment by shusaura85** [comment]
I got the same crash. Here are some dump files for it.  
Both dump files were created in a new game (no other trains or vehicles present), same scenario (Medium/ Race to Read).

[c1644881-fd20-4caf-83d8-43147f7765fc(OpenLoco, v24.09.1 (4fe5ae37 on master)).zip](https://github.com/user-attachments/files/17101591/c1644881-fd20-4caf-83d8-43147f7765fc.OpenLoco.v24.09.1.4fe5ae37.on.master.zip)
[50a1e4e0-c8cf-435f-b1f1-36cf20fade2f(OpenLoco, v24.09.1 (4fe5ae37 on master)).zip](https://github.com/user-attachments/files/17101592/50a1e4e0-c8cf-435f-b1f1-36cf20fade2f.OpenLoco.v24.09.1.4fe5ae37.on.master.zip)

**Comment by duncanspumpkin** [comment]
ahh i see the issue. When you delete all cars it can crash at the end of each day as it tries to update he reliability.

**Comment by followsail** [comment]
Exactly the same problem, its repeatable too.  This happens on 24.09.1

regards
