### ISSUE TITLE
OpenLoco - Hovering over the train icon in the window gives invalid CD Key error. 

### ISSUE THREAD

**Issue by SoraTheReaper** [OpenLoco/OpenLoco#263]
OS: Windows 10 Pro (Version 1803 - OS Build 17134.48)
Version: 18.02
Commit/Build: d2237ea

**Steps to reproduce:**
1. Open up the vehicle window. 
2. Hover over the train icon. 
3. It will either say "View" or give an "Invalid CD Key" error. 

**Is the issue reproducible in Locomotion (vanilla)?**
I'm not sure, I don't play Vanilla. Any vanilla vehicles I have have modded stats and are indestructible. 

**Screenshots / Video:**
See attached screenshot. 
![locomotionscreenshot5](https://user-images.githubusercontent.com/37215359/52533287-c2eb6480-2cff-11e9-851c-529bf20a8ad2.jpeg)

**Save game:**
[Western Ohio Fun - 1900 Redone! (Heritage Set included!) -.txt](https://github.com/OpenRCT2/OpenLoco/files/2848814/Western.Ohio.Fun.-.1900.Redone.Heritage.Set.included.-.txt)

**Comment by AaronVanGeffen** [comment]
We released v21.02 today. If the problem persists on that version, please file a new issue with detailed steps to reproduce. Thanks.
