### ISSUE TITLE
Options/Miscellaneous window cut off

### ISSUE THREAD

**Issue by SoraTheReaper** [OpenLoco/OpenLoco#264]
OS: Windows 10 Pro (Version 1803 - OS build 17134.48)
Version: 18.02-472
Commit/Build: 18.02-472 (71611fc on master)

Misc. Menu is cut off along the bottom, with letter missing parts of them. 

**Steps to reproduce:**
1. Go into Option Menu in the main menu at the top right. 
2. Navigate to the Options - Miscellaneous Menu.
3. Look at the bottom of the menu. 

**Is the issue reproducible in Locomotion (vanilla)?**
No, this is only in the current version of OpenLoco.

Screenshots/Video:
![misc menu](https://user-images.githubusercontent.com/37215359/52533675-4b203880-2d05-11e9-9905-8400868c538d.jpeg)

Save game:
N/A. It's a menu glitch.

**Comment by AaronVanGeffen** [comment]
The option is hidden depending on the value set in `112A17E`, which appears to be set in `load_object_index`. I'm guessing the checkbox is hidden if no custom objects were found.

I'm leaning towards not just increasing the tab's height, but also always showing the checkbox instead. Thoughts?

**Comment by loveletslive7** [comment]
> 
> 
> The option is hidden depending on the value set in `112A17E`, which appears to be set in `load_object_index`. I'm guessing the checkbox is hidden if no custom objects were found.

I am looking at fixing this, along with the issue #388 

Question: I can see the IF statement checking for a value set on `112A17E`, but I can't see where that value would ever be set.. But it must be set by something because the checkbox does appear.
You mentioned `load_object_index`, but I also see no declaration of that function... could you shed any light on where you believe the value is coming from?

**Comment by duncanspumpkin** [comment]
@loveletslive7 you likely can't find that function because we haven't implemented it yet. It is still in the original game executable.

**Comment by AaronVanGeffen** [comment]
The function probably hasn’t been reimplemented in C++ yet. The name `112A17E` refers to a memory address used by the original game routines.

**Comment by seifer7** [comment]
I've fixed this. I will be submitting a pull request soon.
It'll also include fixes for issue #388  , and #396

**Comment by AaronVanGeffen** [comment]
Sounds great. Generally, I'd prefer a separate PR for each fix. However, if they're small fixes, contained in their own commits, that's okay as well.

**Comment by seifer7** [comment]
They are small but i can do them as three PRs if that's preferred. This is my first time contributing to a project.

**Comment by AaronVanGeffen** [comment]
If it's not too much work on your end, then yes, I would prefer that. Thanks.
