### ISSUE TITLE
Diagonal track rendering issues

### ISSUE THREAD

**Issue by LeftofZen** [OpenLoco/OpenLoco#2655]
These are confirmed to be openloco issues - vanilla renders them correctly. Most of these seem to be issues with diagonal track:
1. Diagonal/large-curve track rendered over vehicles:
![Image](https://github.com/user-attachments/assets/b770518f-2de3-4997-8308-af7acae95652)
1. Signals not rendered/rendered over by track
![Image](https://github.com/user-attachments/assets/141e59af-e4fe-43e6-b8c3-0b94a3952dab)
1. Diagonal track again rendered over vehicles
![Image](https://github.com/user-attachments/assets/bb1bcd92-4eaa-4ffb-82d6-a2df216372ec)
1. The bottom loco's front bogey is not rendered
![Image](https://github.com/user-attachments/assets/16cc2b64-accb-43eb-ab52-86c62bfa39de)

**Comment by LeftofZen** [comment]
May be similar/same as the issue in #2540

**Comment by duncanspumpkin** [comment]
Could you create a save that has each of the issues shown on the first tick. What we can do is isolate the drawing to only the one problem tile and once we do that we can see all the bounding boxes and review where we think it has gone wrong

**Comment by LeftofZen** [comment]
The signal one and the station cargo one are not time sensitive - they can be seen at all times. Do I need to do anything special for those? I can upload the save with all these issues when I get home.

**Comment by LeftofZen** [comment]
[Valleys.zip](https://github.com/user-attachments/files/17354776/Valleys.zip)

**Comment by LeftofZen** [comment]
- The diagonal track issues (images 1, 2, 3) start in 23.12, issue not present in 23.11
- The cargo/station sprite ordering issue starts in 22.05, issue not present in 22.04

**Comment by duncanspumpkin** [comment]
That suggests #2216 or #2218

**Comment by duncanspumpkin** [comment]
For the cargo part of this. Is it any different to #1483? Can we just change this issue into just the track issues then we can close it with #2658.

**Comment by LeftofZen** [comment]
> For the cargo part of this. Is it any different to [#1483](https://github.com/OpenLoco/OpenLoco/issues/1483)? Can we just change this issue into just the track issues then we can close it with [#2658](https://github.com/OpenLoco/OpenLoco/pull/2658).

I don't know if its the same issue or not, but yeah I'm happy to split this issue up. Keep this are disagonal track issue, use the other one for station rendering issue.

**Comment by LeftofZen** [comment]
Fixes #2540
