### ISSUE TITLE
Game crashes semi-randomly when adding vehicles to an empty vehicle

### ISSUE THREAD

**Issue by Wuzzle** [OpenLoco/OpenLoco#2661]
**Version information:**
 - Platform: Windows 10
 - Version: 24.09.1
 - Build/commit: 4fe5ae37

**Describe the bug**
I'll give an example. If you sell a bus via the vehicle details tab and then update it with a newer bus (i.e. Vulcan VSD to Model 36R) then the game crashes, but only sometimes

**To Reproduce**
1. Buy a vehicle
2. Place it in the world
3. Sell the vehicle by dragging the only part to the trash bin in the vehicle details tab
4. Buy a new vehicle
5. Crash

**Expected behaviour**
The new vehicle should be take the spot of the old vehicle without issue

**Crash dump**
[eb1d2589-662d-4483-8d8b-355887729d8c(OpenLoco, v24.09.1 (4fe5ae37 on master)).dmp](https://github.com/user-attachments/files/17386606/eb1d2589-662d-4483-8d8b-355887729d8c.OpenLoco.v24.09.1.4fe5ae37.on.master.dmp)

**Comment by LeftofZen** [comment]
This is a known issue and will be fixed in the next release, which will hopefully be this weekend. In the meantime you can use an older version of OpenLoco

**Comment by Wuzzle** [comment]
Ah okay, what version doesn't have this?
Also, while I was reproducing this bug in my game it got worse, it crashed when I opened the build vehicles window while having the vehicle tab window open

**Comment by LeftofZen** [comment]
The previous version, 24.08, will work. https://github.com/OpenLoco/OpenLoco/releases/tag/v24.08

I don't get a crash as you described there, even on 24.09.1, so I'm not sure what's happening. Does it happen for you on 24.08?

**Comment by Wuzzle** [comment]
Checked again, just deleting via the vehicles tab causes the issue now, it might have something to do with it being on a slope? No idea

**Comment by LeftofZen** [comment]
Is that on 24.08?

**Comment by Wuzzle** [comment]
No, 24.09.1, as before

**Comment by LeftofZen** [comment]
We know its bugged in 24.09.1. Can you try 24.08

**Comment by Wuzzle** [comment]
I did, there's no issue there

**Comment by LeftofZen** [comment]
Ok cool, was just trying to determine if 24.08 also had an issue, thanks for checking
