### ISSUE TITLE
Feature request: Junction/Station Copying

### ISSUE THREAD

**Issue by Wuzzle** [OpenLoco/OpenLoco#2663]
**Describe the solution you'd like**
A button in the track/road building menu that lets you copy segments of tracks/roads as well as station layouts so you can place them down elsewhere. These would ideally be shareable so complex junctions and stations (i.e. dual track railway junctions/stations) could be posted online for others to use.

**Comment by LeftofZen** [comment]
Thanks for making the feature requests, though we would appreciate it if you could first search for existing issues before making new ones that are duplicates.

https://github.com/OpenLoco/OpenLoco/issues/1438
