### ISSUE TITLE
Vehicle clipping compared with original game

### ISSUE THREAD

**Issue by strongbowe1** [OpenLoco/OpenLoco#2678]
**Version information:**
 - Platform: Windows 10
 - Version: 24.10

**Describe the bug**
Some of my custom made objects have a clipping issue in OpenLoco that doesn't exist in the original game.

**To Reproduce**
I can send you the custom object if needed to test.

**Expected behaviour**
The custom made object is rendered correctly without the clipping issue.

![Image](https://github.com/user-attachments/assets/0fceffcb-224e-4bfe-a86b-82a6b044fbbc)

**Comment by LeftofZen** [comment]
Can you upload the custom object here plz. I don't see any issue with vanilla objects on 24.10:
![Image](https://github.com/user-attachments/assets/70e9d4d6-2926-4206-9a1f-1f1f9c06438c)

**Comment by strongbowe1** [comment]
No, vanilla objects are (mostly) fine, even though there is some clipping too on steep sprites in both OpenLoco and Locomotion. I think I posted this issue some time ago.

However I was building a new custom object yesterday and had this strong clipping on it in OpenLoco, while in the original Locomotion it's fine as you can see on the screenshot above from the same savegame.

Attached is the object causing trouble.

[bls_rabe528re_strongbow.zip](https://github.com/user-attachments/files/17473308/bls_rabe528re_strongbow.zip)

**Comment by strongbowe1** [comment]
Also in the Build Trains menu of OpenLoco the bogies of this custom object are drawn incorrectly compared with the original game. See screenshot.![Image](https://github.com/user-attachments/assets/24daaaee-57fa-4fe7-bbc7-1bdd3e4f2418)

**Comment by duncanspumpkin** [comment]
It looks like you have bogies outside the limits of the vehicle the engine was not designed for overlapping of vehicles like that I'm surprised vanilla lets it draw. There are a number of assumptions that this is violating. Need to look at this object more to see what we can do to support it.

**Comment by strongbowe1** [comment]
Yes, Locomotion wasn't probably designed to support jacobs bogies as none of the vanilla objects have bogies outside of the vehicle boundaries and it's also not easy to code in the XML. The TGV uses jacobs bogies in reality, but not in the game.

I have this other older object that was being drawn properly in OpenLoco for some time (and always in the vanilla game), but since a few releases the bogies are drawn not properly in the Build menu. But it's being displayed fine running on the map.

[tez_42095_strongbow.zip](https://github.com/user-attachments/files/17477787/tez_42095_strongbow.zip)

![Image](https://github.com/user-attachments/assets/89f47950-9d2a-4b60-b640-845270c6e9ae)

**Comment by duncanspumpkin** [comment]
For the inline train drawing i implemented it as a drawing of each car at a time. It will need to be all bogies then all bodies for there to be no issues with your setup.

**Comment by strongbowe1** [comment]
I managed to fix the inline train drawing by swapping the bogies between the individual carriages. However the issue from the first post above still remains.

![Image](https://github.com/user-attachments/assets/8fc7d294-352f-44f5-9d23-defeaa7659e4)

**Comment by strongbowe1** [comment]
But it doesn't work in the vehicle details window or the trains list when the vehicle parts are back to back.

![Image](https://github.com/user-attachments/assets/3bfd80ab-3ad3-459b-8b81-93901dd0d7c8)

**Comment by duncanspumpkin** [comment]
https://github.com/OpenLoco/OpenLoco/pull/2683 should fix both of your issues.

**Comment by LeftofZen** [comment]
> it's also not easy to code in the XML

Well there's an issue. Why are you using LocoTool? https://github.com/OpenLoco/ObjectEditor

**Comment by strongbowe1** [comment]
The coding itself is actually not the problem, but rather finding the correct balance between the offset of the 3D render and the front bogie position. If you check the front part of the BLS emu above, you'll see that the rear bogie is at the end of this part while the front bogie is at 1/4 of the way from the front. Setting the bogies asymmetrical in the XML and rendering the front part in the center of the 3D scene will make this front vehicle part overlap the second part of the vehicle in the game for some reason. Locomotion just doesn't like a vehicle with one bogie at the end and the other 1/4 of the way from the front.

So I need to move the front vehicle part a bit further forward in the 3D scene, render it and adjust the front bogie position in the XML so the front part is not hitting the second part. It all sounds a bit complicated, but if you check the render of the front part and it's bogie settings in the XML, you'll probably understand.

While I appreciate the Object Editor, I've been coding XMLs for the past 18 years and it's hard to change the habit now. :)

**Comment by LeftofZen** [comment]
Sorry but we can't provide support for objects made in LocoTool. It has many bugs and is incomplete (it doesn't understand what many object fields are and often sets them incorrectly). It is hard to determine if the issues you're seeing are from your custom object or from the game itself. Duncan has already made some changes in #2683 but further than that, I think your object is the issue.

**Comment by strongbowe1** [comment]
I was actually just trying to explain how Locomotion isn't able to properly interpret and display objects with jacobs bogies where one bogie is at a regular position and one is at the far end of the vehicle part.

Let's take the vanilla game TGV1.dat for instance. It has the front bogie at position 52 and the rear bogie at 24.

![Image](https://github.com/user-attachments/assets/a5ef8944-8faf-4e52-b4f2-f5bd6e6ec332)

This is how it looks like in the game as expected:

![Image](https://github.com/user-attachments/assets/7d0eaa33-25d2-463c-a3df-3009a60e9a3f)

Now, if I wanted to change the TGV1.dat to have a jacobs bogie, I would change the rear bogie position to 0 obviously.

![Image](https://github.com/user-attachments/assets/3248bd5b-de59-4aa4-84c1-94fe7bef7bd3)

What it however does in the game is that it shifts the whole vehicle part backwards, not just in the game map, but also in the inline display.

![Image](https://github.com/user-attachments/assets/1ae9b6ce-b762-40de-a8bc-d0fb6580b015)

So what I did with my BLS emu custom object is shift the relevant part of the vehicle in the 3D scene to be offset and not touch the other vehicle parts. This has nothing to do with LocoTool or the ObjectEditor really - I just wanted to point out a certain flaw in the game that I managed to overcome.

The only problem was that OpenLoco didn't display it properly, while the vanilla game did. Seeing that this should be fixed in the future releases, I'm happy and don't require any further assistance. :)

Thanks for your work and keeping the game alive! ;)

**Comment by LeftofZen** [comment]
Hmm ok I see what you mean. The drawing system in-game is fairly complex, it uses a kind of scene tree (they're called paintstructs in the code) to figure out what parts of the window should be invalidated and redrawn or not, to prevent overdraw, and I believe its also used to tell the game what the mouse pointer is hovering over. This was necessary for old hardware at the time of game release, but given how modern GPUs work (noting though that OpenLoco is still fully CPU-rendered), this style of rendering is absolutely slower and less efficient than just fully re-rendering the scene on the GPU. I hope one day we'll be able to rewrite the rendering to use a more immediate-mode style technique and then then the drawing will both become much simpler, faster, and also this is what will fix many of these 'glitches' with the current rendering

**Comment by duncanspumpkin** [comment]
You'll never really be able to get the draw order correct even with a gpu rendering the whole scene every frame. There simply isn't enough information as there is no depth map. The problem with this object as you know is that the engine assumes nothing is outside of the car halfwidth. What that means is the bounding box will be incorrectly sized and that will cause draw order issues. It hasn't been helped though that i broke the bounding boxes of trains and made them 4 times as big...

**Comment by LeftofZen** [comment]
Yeah of course, not every pixel will be perfect because of no depth at you mention, but it will be much better nonetheless. There are still plenty of rendering issues even with the bounding box fix though, as I detailed on the PR
