### ISSUE TITLE
Game crash when loading Snowy Heights scenario

### ISSUE THREAD

**Issue by LeftofZen** [OpenLoco/OpenLoco#2680]
**Version information:**
 - Platform: Win11
 - Version: 24.10
 - Build/commit: master/release

**Describe the bug**
Game crash when loading `Snowy Heights` scenario

**To Reproduce**
Steps to reproduce the behaviour:
1. Start game
2. Try to start `Snowy Heights` scenario (Expert tab)

**Expected behaviour**
No crash

**Screenshots**
NA

**Additional context**
NA

**Comment by AaronVanGeffen** [comment]
I assume it's crashing while generating a random landscape? Could you generate a backtrace?

**Comment by LeftofZen** [comment]
Yep its crashing in the map/terrain gen. Should be reproducible on your system

[12907f35-0c9a-4b87-af12-a29dc998d08d(OpenLoco, v24.10 (52acc01f on master)).dmp](https://github.com/user-attachments/files/17605458/12907f35-0c9a-4b87-af12-a29dc998d08d.OpenLoco.v24.10.52acc01f.on.master.dmp)

**Comment by LeftofZen** [comment]
Ah of course its the classic C++ trap; the modulo operator doesn't work like you expect for negative numbers, it returns negative values still, ie `-1 % 383` is still -1, not 382 like you'd expect. Easy fix I guess, will submit a PR
