### ISSUE TITLE
Construction/destruction of Narrow Gauge Steep Slope Curves is bugged

### ISSUE THREAD

**Issue by LeeSpork** [OpenLoco/OpenLoco#2690]
**Version information:**
 - Platform: Windows 10
 - Version: 24.10
 - Build/commit: 52acc01f

**Describe the bug**
1. When trying to place a Narrow Gauge Steep Slope Curve:
    1. The preview of the track piece won't disappear until you save & load, and turns your mouse into a ghost-track paintbrush.
    2. ~~If you try to place it, it will fail with the "Raise or lower land first" message, even if the terrain is suitable.~~ #2692
2. When trying to remove a Narrow Gauge Steep Slope Curve, it will fail with the message "Can't build Narrow Gauge Track..."

**To Reproduce**
1. Load a game with narrow gauge rails available, such as "Swiss Alps 1930"
2. Open the narrow gauge track building tool
3. Select "Steep Slope Up" or Down (the 45º ones, not the 22.5º ones) and Left- or "Right-Hand Curve (Small Radius)"
4. Move your mouse cursor across the terrain, and attempt to place it somewhere by clicking on a suitable piece of land.
5. Build a different narrow gauge track piece, or right-click on an existing one, and then build the steep slope curve from it.
6. Attempt to remove it by clicking the bulldozer icon, or by using the 'Remove at current position' keyboard shortcut.

**Expected behaviour**
construction

**Screenshots**
Screenshots show me attempting to remove a Curved Steep Slope track after building one, after leaving behind a bunch of white previews of ones I didn't end up building.
![Image](https://github.com/user-attachments/assets/58aa464a-90ea-400d-8511-d5866a94c02a)
![Image](https://github.com/user-attachments/assets/3f6ade6c-ad58-4843-9ad8-41fa150e6616)

**Additional context**
- Issue does not happen in original Locomotion.
- I'm not sure if this issue is specific to Narrow Gauge or not, as I cannot find any other type of track or road that has Steep Slope Curves available.

**Comment by LeftofZen** [comment]
Goodness me that's an interesting one visually. Are you able to narrow down what version the problem started in?

**Comment by LeeSpork** [comment]
With thanks to OpenLauncher, in-between v24.08 (40e9b7bf on master) and v24.09 (7755191c on master).

I also found out that not being able to place them on flat ground is apparently a separate issue that happened years earlier, so I will open a new issue for that once I narrow that down.

**Comment by duncanspumpkin** [comment]
> With thanks to OpenLauncher, in-between v24.08 ([40e9b7b](https://github.com/OpenLoco/OpenLoco/commit/40e9b7bfe1cebf643989c48dca23a6f3313c7bbc) on master) and v24.09 ([7755191](https://github.com/OpenLoco/OpenLoco/commit/7755191ccb6afc6aadf6c3e579b374e5e32291fd) on master).
> 
> I also found out that not being able to place them on flat ground is apparently a separate issue that happened years earlier, so I will open a new issue for that once I narrow that down.

Yeah the bug was introduced in https://github.com/OpenLoco/OpenLoco/pull/2571
