### ISSUE TITLE
North arrow on the Map window does not reflect which direction North is

### ISSUE THREAD

**Issue by LeeSpork** [OpenLoco/OpenLoco#2718]
**Version information:**
 - Version: 24.10
 - Build/commit: 52acc01f

**Describe the bug**
In the map window, the map tab icon shows a North arrow. In the original Locmotion, this updates to reflect which way North is as you rotate your view, but in OpenLoco, it incorrectly always points upwards.

(Issue does not affect North arrow on the bottom-right toolbar or magnifying glass dropdown.)

**To Reproduce**
1. press M
2. hold right mouse button and use scrollwheel

**Expected behaviour**
North arrow sprite should change to show which way North is.

**Screenshots**
![Image](https://github.com/user-attachments/assets/d79dd02a-193e-4037-825b-83e1364cef14)

**Additional context**
Original Locomotion (Steam) has expected behaviour.

**Comment by duncanspumpkin** [comment]
https://github.com/OpenLoco/OpenLoco/blob/31b6d16f985289d68434994a82d2cc2ada399f9b/src/OpenLoco/src/Ui/Windows/MapWindow.cpp#L1160 is missing the + currentRotation. ![Image](https://github.com/user-attachments/assets/e99ea8b7-2434-421b-b04c-58cb8939d5b7)
