### ISSUE TITLE
Can start vehicle after going bankrupt

### ISSUE THREAD

**Issue by LeeSpork** [OpenLoco/OpenLoco#2728]
**Version information:**
 - Platform: Windows 10
 - Version: 24.10
 - Build/commit: 52acc01f

**To Reproduce**
1. Be operating a bus
2. Go bankrupt
3. Observe the bus become stopped due to you being bankrupt
4. Use the flag button thing in the vehicle window to try start the bus

**Expected behaviour**
There should be an error message like in original Locomotion:
![Image](https://github.com/user-attachments/assets/d6326998-162b-45b2-8652-3fcf92593a75)

**Actual behaviour**
In OpenLoco, the flag turns green and the bus continues its operation.

**Comment by duncanspumpkin** [comment]
Will be fixed as part of #2726
