### ISSUE TITLE
Cannot issue vehicle orders on macOS

### ISSUE THREAD

**Issue by tspangler** [OpenLoco/OpenLoco#273]
**OS:**  macOS Mojave 10.14.3
**Version:**  18.02-479
**Commit/Build:**  a9fcc83

I am unable to issue orders for any type of vehicle. Clicking a station opens the information window for that station, instead of assigning the order. Additionally, when attempting to create a waypoint for a ship, clicking the open sea does nothing.

**Steps to reproduce:**
1. Create a simple route: Build two bus stations, buy a bus, place bus on the road.
2. Open the orders page for the bus.
3. Attempt to click on a station and observe that the information window for the station opens, instead of the correct behavior of creating an order to travel to that station.

**Is the issue reproducible in Locomotion (vanilla)?**
No. I am able to issue orders as usual on Windows using both the vanilla Steam version _and_ the prebuilt OpenLoco 18.02 (`d2237ea`).

**Screenshots / Video:**
Video: https://www.dropbox.com/s/94hhgd511dazcmw/OpenLoco-OrdersIssue.mov?dl=0

**Comment by AaronVanGeffen** [comment]
Bisecting: bc27d48 (three weeks ago) is unaffected.
