### ISSUE TITLE
Warn when selecting an object will automatically select other objects in the Object Selector

### ISSUE THREAD

**Issue by LeeSpork** [OpenLoco/OpenLoco#2767]
### Describe the solution you'd like
Example: if "Railway Track" is unticked, and you select a train that uses it such as "3F 'Jinty'", a dialogue box window will pop up being like **"Selecting this object will also select Railway Track. Are you sure? [Yes] [Cancel]"** (instead of the current behaviour of automatically ticking it without the user's knowledge).

It can have the same design as the existing translucent red 'Save before quitting ?' dialogue box.

Note: this should not apply to the "World Region" tab.

### Why this will be helpful
If a user wants to create a scenario in which they do not want a particular type of object to be available, this will prevent them from unknowingly selecting it by accident.

**Comment by duncanspumpkin** [comment]
This would mean almost every object selection has a warning. There aren't many objects that don't also load another object.

**Comment by LeeSpork** [comment]
Yes, but I believe it will be rare to see the warning anyway. In the vanilla world regions, most of the prerequisite objects of the vanilla objects are already selected, so vanilla players will realistically only see it if they either deselected that prerequisite object themselves earlier, or are selecting a narrow gauge vehicle for the first time.

**Comment by LeftofZen** [comment]
> If a user wants to create a scenario in which they do not want a particular type of object to be available, this will prevent them from unknowingly selecting it by accident.

How often is this scenario though? I think the number of times people erroneously see this warning (or don't care about it) will be much higher than the number of people that want to see it. Those people that do want to see it care enough about object selection that they will double check their selections at the end anyways. 

> Yes, but I believe it will be rare to see the warning anyway.

Almost every vehicle has a sound effect, so selecting a vehicle will almost always trigger this. Then, having conditional behaviour like "if vehicle and not soundeffect" will just lead to user confusion about when the warning will and won't show.

What do you propose for objects that have large numbers of dependent objects? Like Track objects can have 20+ linked objects. Are you showing 20 warnings? Displaying 20 objects in a list in one window?

**Comment by LeeSpork** [comment]
> How often is this scenario though? I think the number of times people erroneously see this warning (or don't care about it) will be much higher than the number of people that want to see it. Those people that do want to see it care enough about object selection that they will double check their selections at the end anyways.

True. After considering it further, this isn't a very good solution for the cases I was thinking of anyway.
