### ISSUE TITLE
"Unable to find game folder" when exe is in the game folder

### ISSUE THREAD

**Issue by fgsfds** [OpenLoco/OpenLoco#2774]
**Version information:**
 - Platform: Windows 11
 - Version: 24.11
 - Build/commit: 767aa94

**Describe the bug**
Getting `Unable to automatically find the Locomotion game folder.` error even though OpenLoco in the the game folder.

**To Reproduce**
Steps to reproduce the behaviour:
1. Unpack OpenLoco-v24.11-Win32.zip into the game folder
2. Launch OpenLoco.exe

**Expected behaviour**
OpenLoco automatically detects the game folder and starts

**Screenshots**
![Image](https://github.com/user-attachments/assets/3ddb502c-7f2e-49fa-bc25-ce036f98530a)

**Comment by LeftofZen** [comment]
This is not a bug. You need to keep your openloco and original-locomotion-install-folder separate

**Comment by fgsfds** [comment]
>You need to keep your openloco-folder and original-locomotion-install-folder separate
Why though? OpenLoco doesn't overwrite original files and keeps its settings in appdata, so it shouldn't cause any problems. 
Just tried that, and it worked fine. Or there are issues I didn't encounter yet?

**Comment by LeftofZen** [comment]
I don't think there is any technical reason, other than it just isn't supported. It may or may not work, but it should always work if they're separate. I guess the question is, why *should* it be supported? Ideally you want to keep content and executables separate, not together. This separation means it is less likely that modifications to content folders (which are extremely common) do not mess with the game binaries itself, which shouldn't be touched.
