### ISSUE TITLE
Bridgeless roads appearing randomly

### ISSUE THREAD

**Issue by FenderBender2** [OpenLoco/OpenLoco#2776]
**Version information:**
 - Platform: Windows 11
 - Version: 24.11
 - Build/commit: 767aa94e

**Describe the bug**
I've noticed a few roads without bridges appearing around my scenarios. These are AI generated roads so I have no idea how to reproduce them.

**Screenshots**
![Image](https://github.com/user-attachments/assets/86f7daa7-6440-40d3-93d3-afd3b047b7f6)

![Image](https://github.com/user-attachments/assets/6ab15e49-2553-4edc-836d-913a87cc601b)

**Comment by FenderBender2** [comment]
Appears OK in Vanilla...

![Image](https://github.com/user-attachments/assets/24139604-d7e0-4dc1-a2f7-ae06bd6f09df)

**Comment by duncanspumpkin** [comment]
Looks like a paint bridge mistake can you upload a save with this happening

**Comment by LeeSpork** [comment]
I was able to reproduce this by building on the roof of a sawmill:
### v24.10
![Image](https://github.com/user-attachments/assets/0bc5367e-e561-4113-989d-219659e03c30)
### v24.11
![Image](https://github.com/user-attachments/assets/2b760f2a-8638-4d99-97c8-83b8d2cc072a)

[save file.zip](https://github.com/user-attachments/files/17963470/save.file.zip)

**Comment by FenderBender2** [comment]
I can see that its ok in 24.10 too. @duncanspumpkin I assume you don't need a save game from me as LeeSpork has provided one above?
