### ISSUE TITLE
Layering issue with bridge supports and houses

### ISSUE THREAD

**Issue by LeeSpork** [OpenLoco/OpenLoco#2777]
**Version information:**
 - Platform: Windows 10
 - Version: 24.11
 - Build/commit: 767aa94e

**Describe the bug**
The back of the bridge archways are being painted(?) in front of houses when they should be behind the houses.

Issue **only happens when the view is rotated certain directions** apparently: at least for the bridge in the screenshots bellow, the issue only happens when the view is rotated North-up or South-up.

**Screenshots**
![Image](https://github.com/user-attachments/assets/9d3415e0-a176-4a7e-8f22-f850b1f81f3a)
![Image](https://github.com/user-attachments/assets/a2768dce-1da8-4f5d-ba7a-598401a0adea)

Issue did not happen in v24.10.

[save file.zip](https://github.com/user-attachments/files/17963470/save.file.zip) (rotate the view and pan North-East a little)

**Comment by LeftofZen** [comment]
support and bridge painting was just implemented so it would surely be related to that

https://github.com/OpenLoco/OpenLoco/pull/2757
https://github.com/OpenLoco/OpenLoco/pull/2744
