### ISSUE TITLE
Change industry name generator to always use town name

### ISSUE THREAD

**Issue by LeeSpork** [OpenLoco/OpenLoco#2785]
In the original Locomotion, the first coal mine near a town named London (for example) would be named "London Coal Mines". The second (and so on) would simply be named "Coal Mines 1", unless there was already a coal mine with that name _anywhere in the world,_ in which case a larger number would be used.

My suggestion is that the second coal mine near a town named London should instead get the name "London Coal Mines 2" when generated in future versions of OpenLoco.

Or more generally, industries should be named "[town name] [industry type] [lowest positive integer needed to avoid a duplicate name, omitted if this number is 1]"

**Additional context**
Implementing this properly would incidentally also count as a fix for #2434. It may also involve finding out what is causing that bug.

**Comment by RedMarcher** [comment]
Unlike the town name generator, this seems much easier to fix comparatively.
Did you see the other issue with town names sometimes generating incorrectly?

**Comment by RedMarcher** [comment]
Yeah, the current code for industry name assignment seems really borked. There seems to be no real way of storing which industries already belong to a town.

I guess the easiest way to implement this is to have the industry name assignment system parse through and detect the largest number of the industry in the same town.

But the current code isn't very readable, so I'm taking a while trying to figure out how much of it I can safely delete without breaking something else.
