### ISSUE TITLE
People at Bus Stops are the same colour (v. minor)

### ISSUE THREAD

**Issue by FenderBender2** [OpenLoco/OpenLoco#2791]
**Version information:**
 - Platform: Windows 11
 - Version: 24.11
 - Build/commit: 767aa94e

**Describe the bug**
People queuing at bus stops appear the same colour, and there are clipping issues. Older versions (e.g. 24.05) do not have the problem.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a bus stop in a busy town.
2. Wait for people to queue.
3. For the clipping issue, wait for a bus to pass in front of the queue.

**Screenshots**
![Image](https://github.com/user-attachments/assets/e34f7be7-6ac6-492c-b5e6-a1afb262004a)

**Comment by duncanspumpkin** [comment]
oh lol https://github.com/OpenLoco/OpenLoco/blob/240fbe4f8d4b381c7dc36abfa14dc679e72b0811/src/OpenLoco/src/Paint/PaintStation.cpp#L112 forgot to increment variation in this loop
