### ISSUE TITLE
Crash upon attempting truck placement at intersection

### ISSUE THREAD

**Issue by AmyntasSynth** [OpenLoco/OpenLoco#2795]
**Version information:**
 - Platform: Windows 11
 - Version: 24.11
 - Build/commit: Unknown - Downloaded from official website on 12.12.2024

**Describe the bug**
_Crashdump_: https://www.mediafire.com/file/9rziqojfe8l52yd/fad1a803-3bf9-450b-abf3-adde96adb03f%2528OpenLoco%252C_v24.11_%2528767aa94e_on_master%2529%2529.dmp/file
_Latest save file before crash (moments before the crash too!)_: https://www.mediafire.com/file/co6r40jpb1w9tb1/autosave_2024-12-15_14-57-28.SV5/file

I was playing the "Race to Read" Scenario.
The crash seemed to occur during truck placement, after buying and placing a good dozen or so in a row.

**To Reproduce**
_It's actually reproducable with the given save file!_
Steps to reproduce the behaviour:
1. Go to Hanburg cargo station
2. Clone one of the existing flatbed trucks or buy a new one - both produce the crash
3. Hover cursor over the intersection - at a specific spot the crash will occur! (See screenshot)

**Expected behaviour**
No Crashing

**Screenshots**
https://ibb.co/TKNj9vy

**Additional context**
Trying to upload files here on Github keeps failing for me, so I'm linking the crashdump, save and screenshot with imgbb and Mediafire.

**Comment by duncanspumpkin** [comment]
For future reference just zip the dump file it compresses very well into a small enough size for github.

**Comment by duncanspumpkin** [comment]
This is https://github.com/OpenLoco/OpenLoco/issues/2262 a vanilla bug in code we haven't implemented yet.
