### ISSUE TITLE
Trying to change company name causes crash.

### ISSUE THREAD

**Issue by SoraTheReaper** [OpenLoco/OpenLoco#294]
**OS:**  Windows 10 Pro
**Version:**  v19.03
**Commit/Build:**  v19.03-5 (50ed932 on master)

I was starting a new game for the modded automod scenario, I was able to change my player name, but when I clicked on the menu to change the company name, my game auto-crashed. 

**Steps to reproduce:**
1. Start new game. 
2. Enter player name. 
3. Click on Company Name (Mine's SoraTheReaper Transport).
4. Watch as game CTD's.

**Is the issue reproducible in Locomotion (vanilla)?**

Yes and no. I have a modded game, but I went to an original scenario (for testing purposes), and I was able to reproduce it. 

**Screenshots / Video:**

There's no screenshots, or video. 

**Save game:**

Save games are unavailable because this is after a new game has been started. 

Notes: If the company name is chosen first, it works as designed. But if the player name is chosen first, (ABCD), the company name changes (ABCD Transport). If one decides to attempt to change the company name after doing the player name, the game CTD's.

**Comment by duncanspumpkin** [comment]
Can you check to see if this still happens in latest release

**Comment by AaronVanGeffen** [comment]
We released v21.02 today. If the problem persists on that version, please file a new issue with detailed steps to reproduce. Thanks.

**Comment by duncanspumpkin** [comment]
Issue caused by not correctly passing the constness of a buffer downwards. There was one function that missused the string as a buffer and trashed the memory.
