### ISSUE TITLE
Challenge progress calculation inaccurate

### ISSUE THREAD

**Issue by tspangler** [OpenLoco/OpenLoco#296]
**OS:**  macOS Mojave 10.14.3
**Version:**  19.03-01 (pre-built)
**Commit/Build:**  `1510a1a`

The "Challenge progress" percentage is inaccurate when loading a saved game.

I can't identify any rhyme or reason to this - it happens on brand-new saves created by OpenLoco _and_ some of my original, 15-year-old vanilla saves.

Here are some calculated progress figures from my saves:
- -9,638%
- -1,258%
- -1,536%
- -9,728%
- -9,710%
- 8,203%
- -19,197%
- -9,667%
- 16,384%

**Steps to reproduce:**
1. Start a new game.
2. Build some stuff. Or don't. It doesn't really matter.
3. Save the game.
4. Open the "Load Game" screen, highlight the save you just created and observe that the _Challenge progress_ number is wildly inaccurate - sometimes it's negative, sometimes it's extremely positive (i.e. 17,152%)

**Is the issue reproducible in Locomotion (vanilla)?**
No.

**Screenshot**
![openloco-challenge-completion-inaccurate-1510a1a](https://user-images.githubusercontent.com/42648/53755138-651fe780-3e7b-11e9-81f1-90171da7a30a.png)

**Save game:**
I can provide a save if you're unable to reproduce; just @ me.

**Comment by marijnvdwerf** [comment]
Can you provide a save file, together with a screenshot of how it shows up in the vanilla game?

**Comment by tspangler** [comment]
### Save
[WeatherworldGitHubIssue.zip](https://github.com/OpenLoco/OpenLoco/files/2928994/WeatherworldGitHubIssue.zip)

### Vanilla screenshot
![weatherworldgithubissue](https://user-images.githubusercontent.com/42648/53776122-aedbf280-3eba-11e9-847d-acc27698f33c.png)

### OpenLoco screenshot
<img width="640" alt="weatherworld-githubissue-openloco" src="https://user-images.githubusercontent.com/42648/53776128-b9968780-3eba-11e9-9bb1-d85d662597fe.png">
