### ISSUE TITLE
menu click sound not played

### ISSUE THREAD

**Issue by hsungha** [OpenLoco/OpenLoco#297]
**OS:**  windows 10
**Version:**  19.03 
**Commit/Build:** 0162d4d

menu click sound is not played

**Steps to reproduce:**
1. when any menu button is clicked
2. does not played click sound

**Is the issue reproducible in Locomotion (vanilla)?**
not reproducible.
also, release 18.02 has not reproducible.

**Screenshots / Video:**
vanilla https://youtu.be/pxLfumxjZx0
18.02 https://youtu.be/0igVkHDosjg
19.03 https://youtu.be/N-cUf-HRmCI
(In the video, the 'real' mouse click sound was recorded overlaid to let me know that I had clicked the mouse.)

**Save game:**
Not applicable

**Comment by AaronVanGeffen** [comment]
On the mouse input side, I've confirmed the sound effect is queued:

https://github.com/OpenLoco/OpenLoco/blob/1d986c9c310565a38f9b00f3baa1d629d6650421/src/openloco/input/mouse_input.cpp#L943

So cause for it not playing must be elsewhere. @IntelOrca, could you have a look?
