### ISSUE TITLE
No cost when planting multiple trees at once

### ISSUE THREAD

**Issue by sunaneko-1324** [OpenLoco/OpenLoco#298]
**OS:**  windows 10
**Version:** 19.03
**Commit/Build:** 0162d4d

No cost when planting multiple trees at once

**Steps to reproduce:**
1. open any game.
2. open plant tree menu.
3. click the buttons to plant multiple trees at once (I do not know the name of this button.)
4. plant trees everywhere.

**Is the issue reproducible in Locomotion (vanilla)?**
not reproducible. (this function is only avaliable in scenario editor prev release 19.03)

**Screenshots / Video:**
https://youtu.be/-F6mvRdppf0

**Save game:**
Not applicable

**Comment by AaronVanGeffen** [comment]
This is expected behaviour until we actually implement these functions ourselves. The existing code for the scenery cluster tool simply doesn't compute the cost.

We will get around to implementing it, eventually, of course. :)

**Comment by shdeva** [comment]
Another note- planting the multi-trees doesn't raise your approval rating with towns the way single trees do.
