### ISSUE TITLE
Screenshots should be saved as PNG

### ISSUE THREAD

**Issue by marijnvdwerf** [OpenLoco/OpenLoco#331]
Currently in-game made screenshots are saved as bmps. These are uncompressed, and thus rather big (with current screen sizes), and we've had various reports that github wouldn't let them be posted in issues. We are close to implementing the screenshot generation (#271), so it should be possible to fix this and use png-based screenshots instead.

- [ ] Have VCPKG produce 32-bit libpng libraries
- [ ] Disassemble screenshot generation
- [ ] Use libpng to make save the bitmap

**Comment by AaronVanGeffen** [comment]
Implemented by #347
