### ISSUE TITLE
Building a signal adds money

### ISSUE THREAD

**Issue by joostjong** [OpenLoco/OpenLoco#349]
**OS:**  macOS 10.14.5
**Version:**  19.03
**Commit/Build:**  0162d4d

When building a signal, a varying amount of money is added in stead of removed. Always about 2 billion. Game is unmodded.

**Steps to reproduce:**
1. Build a stretch of rail
2. Place a signal

**Is the issue reproducible in Locomotion (vanilla)?**
In vanilla Locomotion, the signals have their normal price.

**Screenshots / Video:**
<img width="646" alt="Schermafdruk 2019-05-24 20 04 21" src="https://user-images.githubusercontent.com/51000563/58591867-8a987380-8267-11e9-9cb8-1034905af3d6.png">

**Comment by AaronVanGeffen** [comment]
Seeing something similar with a semaphore:

![Screenshot_20190529_232937](https://user-images.githubusercontent.com/604665/58592840-a56be780-8269-11e9-9e08-5b316074a715.png)

**Comment by marijnvdwerf** [comment]
Just to be sure, it also affects the value of the counter, and isn't just a bug with the floating numbers?

**Comment by AaronVanGeffen** [comment]
Yeah, you get a bunch of money back in the construction category:

![Screenshot_20190530_122332](https://user-images.githubusercontent.com/604665/58626732-c10cd780-82d5-11e9-8f62-4c4ba6460152.png)

This is after building two semaphores.

**Comment by AaronVanGeffen** [comment]
This has been in for a long time:

```
git bisect start
# bad: [2ea9d0f1903bdbead14659b1f16b5dec9eb49003] Update README.md
git bisect bad 2ea9d0f1903bdbead14659b1f16b5dec9eb49003
# bad: [0162d4de13fd9eafd14860ed1e5a6386d3bb49c6] Increase version number to 19.03. (#288)
git bisect bad 0162d4de13fd9eafd14860ed1e5a6386d3bb49c6
# bad: [d2237ea91c0a2869acf27d205ee07b7712ada6ba] Set release date for 18.02 in changelog
git bisect bad d2237ea91c0a2869acf27d205ee07b7712ada6ba
# bad: [48c9d593f0c7d8f28150f27da0a9031115e94acd] Decompile tooltip window
git bisect bad 48c9d593f0c7d8f28150f27da0a9031115e94acd
# bad: [904aceb1c4d12204faa4a72f9acc5b3dcd90ebef] Merge pull request #75 from jgottula/ZehMatt/refactor/interop
git bisect bad 904aceb1c4d12204faa4a72f9acc5b3dcd90ebef
# bad: [0fa0aa545ed395c6c2a22102b8d1c84d12d32f8d] Improve `CreateFile` hook for posix
git bisect bad 0fa0aa545ed395c6c2a22102b8d1c84d12d32f8d
# bad: [443754d38982b6f678e2080026ed98a54712b4dd] Merge pull request #76 from ethanhs/fsfix
git bisect bad 443754d38982b6f678e2080026ed98a54712b4dd
# bad: [8ec490a2f9c6e379560bdc533a4341be395f11c2] Merge pull request #79 from IntelOrca/fix/path-and-checks
git bisect bad 8ec490a2f9c6e379560bdc533a4341be395f11c2
# bad: [8ec490a2f9c6e379560bdc533a4341be395f11c2] Merge pull request #79 from IntelOrca/fix/path-and-checks
git bisect bad 8ec490a2f9c6e379560bdc533a4341be395f11c2
# bad: [00b3303facbc899b5d97ee5cf5394c2eb962bde2] Merge pull request #65 from IntelOrca/implement/update-industry
git bisect bad 00b3303facbc899b5d97ee5cf5394c2eb962bde2
```

I can't go back any further due to Linux compat being too poor beyond 00b3303facbc899b5d97ee5cf5394c2eb962bde2.

**Comment by duncanspumpkin** [comment]
Appears to work fine on windows 
![image](https://user-images.githubusercontent.com/1277401/59143981-dfa35a80-89c8-11e9-9f08-eb5ed5d91c70.png)

Perhaps this is some sort of packing issue that only Mac / Linux suffers from.

**Comment by imakin** [comment]
I compiled the marijnvdwerf's `19-06/game-commands` branch on Mac OSX, building signal bug seems fixed but selling signal still adds money

![bug](https://user-images.githubusercontent.com/6647566/63317686-fad20500-c33d-11e9-9b85-fb7bcc81e94c.jpg)

**Comment by AaronVanGeffen** [comment]
Has since been resolved. The v20.03 release should not have this issue. Thanks :)
