### ISSUE TITLE
Ability to start before 1900

### ISSUE THREAD

**Issue by kr4g3n** [OpenLoco/OpenLoco#361]
Is it possible to add the ability to start before 1900?

There used to be a 3rd part program that would allow you to override the starting year in the scenario builder https://www.tt-forums.net/viewtopic.php?t=14113
![image](https://user-images.githubusercontent.com/40052538/59225560-4625a580-8b8e-11e9-94f1-4bd60878b08d.png)

There is also a discontinued mod Thrillville109's Locomotion Expanded https://www.tt-forums.net/viewtopic.php?t=69959  which added pre 1900 vehicles and at least one scenario starting in 1835.
![image](https://user-images.githubusercontent.com/40052538/59225648-8422c980-8b8e-11e9-9aaa-fb4a8da7c73d.png)

The biggest issue that users encountered using these, were that inflation was hardwired to start at 1900 and some how looped around so if you started in the 1800s, things were mega expensive. If there is a way to code the earliest start date to 1800/25 etc without ludicrous inflation value that would be awesome.

**Comment by AaronVanGeffen** [comment]
We've not implemented any inflation-related code yet, I'm afraid. However, we can certainly adjust the minimum value for the scenario editor without any problems there.

**Comment by kr4g3n** [comment]
I look forward to trying it out.

**Comment by AaronVanGeffen** [comment]
Searching for references to `1900` in the assembly, I only find:

```
Address	Function	Instruction
.text:0043C8C0	reset_all	mov     eax, 76Ch
.text:0043D865	show_scenario_editor	mov     scenario_start_year, 76Ch
.text:0043DE8C	ui::landscape_generation::event_1_on_mouse_up	cmp     ax, 1900
.text:0046E2E2	sub_46E2C0	sub     ecx, 76Ch
```

I believe that we can solve the inflation problem by implementing `sub_46E2C0`, too. This sub is only called from `sub_49685C`, and appears to be related to changing the year. Note that `sub_49685C` includes an immediate `1800` as well, so that warrants looking into.
