### ISSUE TITLE
Create a separate repository for dockerfiles

### ISSUE THREAD

**Issue by janisozaur** [OpenLoco/OpenLoco#365]
**Note: This is a copy of https://github.com/OpenRCT2/OpenRCT2/issues/9511, please keep discussion in there**

Rather than rebuild docker image over and over again, producing each time pretty much the same image and losing ability to restore older version, there should be a separate repository that would be used instead to store dockerfiles and only rebuild images when necessary.

**Comment by AaronVanGeffen** [comment]
Has since been done, cf. https://github.com/OpenLoco/openloco-docker-build
