### ISSUE TITLE
Error while linking

### ISSUE THREAD

**Issue by ask6155** [OpenLoco/OpenLoco#369]
**OS:**  ArchLinux amd64
**Commit/Build:**  f42ed80be8fac5c1c5d122352a212585d54aa71f

when running make, the linker ld spits out this fatal error:
`/usr/bin/ld: /usr/lib/libSDL2_mixer.so: error adding symbols: file in wrong format`

**Steps to reproduce:**
1.make build directory
2.cd into it
3.run cmake using the given flags
4.run make

**Comment by AaronVanGeffen** [comment]
Your linker appears to be using the 64-bits version of SDL2 mixer. You may need to manually specify the lib32 location for it. If installed, it should be in `/usr/lib32` on Arch Linux.

**Comment by janisozaur** [comment]
I run into the same issue and I'm aware of that problem. I usually address it by manually executing the link step with sdl2 path modified. I don't know how to properly solve it yet.

**Comment by ask6155** [comment]
can you tell me how to do that?

**Comment by AaronVanGeffen** [comment]
Sorry this was left unanswered for so long.

In such cases, you'll need to pass the library in question directly in the cmake invocation. For example:

`cmake .. -DSDL2MIXER_SDL2=/usr/lib32/libSDL2.so -DSDL2MIXER_SDL2_mixer=/usr/lib32/libSDL2_mixer.so`

**Comment by blargle-ragequit** [comment]
Do you have lib32-sdl2 & lib32-sdl2_mixer installed?  They're in [multilib].

**Comment by hazelnot** [comment]
> Sorry this was left unanswered for so long.
> 
> In such cases, you'll need to pass the library in question directly in the cmake invocation. For example:
> 
> `cmake .. -DSDL2MIXER_SDL2=/usr/lib32/libSDL2.so -DSDL2MIXER_SDL2_mixer=/usr/lib32/libSDL2_mixer.so`

I'm having the same issue, but when I used those arguments I got 
```
CMake Warning:
  Manually-specified variables were not used by the project:

    SDL2MIXER_SDL2
    SDL2MIXER_SDL2_mixer
```
and the build still failed.

**Comment by MrMelon54** [comment]
would be so much easier if there was full x64 build support

it that being worked on?

**Comment by duncanspumpkin** [comment]
> my pc complains about installing sdl2mixer 32-bit because its incompatible with other packages
> 
> would be so much easier if there was full x64 build support
> 
> it that being worked on?

We can't easily do 64bit without reimplementing the whole game (although there have been some interesting attempts at it with the current code). I'm about to drop sdl_mixer but it's being replaced with openal-soft which might have similar issues.
