### ISSUE TITLE
openloco.exe closes on startup

### ISSUE THREAD

**Issue by iF1GHTx** [OpenLoco/OpenLoco#370]
**OS:** Windows 10
**Version:** v19.03
**Commit/Build:** 0162d4d 

After opening openloco.exe and defining the steam installation folder for the game via the popup, the cmd closes. I attempt to launch the openloco.exe after but the cmd window hangs with a printed line of "OpenLoco, v19.03 (0162d4d on v19.03)' then immediately closes. I've reinstalled v18.02 after deleting all of the _dlls_ from v19.03, and the issue does not occur. The game launches successfully on v18.02.

**Steps to reproduce:**
1. Copy contents from provided v19.03 archive to Locomotion install folder.
2. Launch openloco.exe.
3. Select the game install folder via the subsequent popup (The cmd closes).
4. Relaunch openloco.exe (The cmd closes, again).

**Is the issue reproducible in Locomotion (vanilla)?**
No.

**Screenshots / Video:**
![Capture](https://user-images.githubusercontent.com/53846504/62592685-0fc08a00-b8a2-11e9-9d3d-84b2355d6fc6.PNG)

**Comment by iF1GHTx** [comment]
EDIT: It was a user error. After deleting the files in %appdata%\OpenLoco directory and performing a reinstall with the archived files, the game launched.

**Comment by iF1GHTx** [comment]
After messing around with the in-game settings after the reinstall and closing the game, relaunching it caused the original issue. I was able to track it down to the audio settings where one can select the sound device. 

In openloco.yml, from `audio: {}` or `audio: {play_title_music: false}`, specifying an audio device, `audio: {play_title_music: false, device: Headphones (2- Astro MixAmp Pro Game)}`, causes the issue.  I've tried to select all three audio device options from the in-game menu, and each one causes the issue. Leaving the audio device undefined doesn't cause the issue.

**Comment by AaronVanGeffen** [comment]
Thanks for the additional info. When I change my audio device to a non-existing one, the game still starts for me, however. Interestingly, the game does hang when I try to change it to an existing one.

Audio devices are handled differently on Windows and Linux, though — specifically the default devices. Perhaps it is related to the fallback code.

**Comment by ERRORTEK23** [comment]
I uninstalled the locomotion and installed it again and the game closes. What should I do ?

**Comment by AaronVanGeffen** [comment]
I believe this has been resolved with #431.
