### ISSUE TITLE
Can't save game nor scenario

### ISSUE THREAD

**Issue by Alepod** [OpenLoco/OpenLoco#375]
**OS:**  Win 8.1 S. L.
**Version:**  v19.03

No any error message, just no file is saved in result

**Comment by AaronVanGeffen** [comment]
Could you try a more recent build, e.g. [this one](https://ci.appveyor.com/project/AaronVanGeffen/openloco/builds/26663016/artifacts)?

**Comment by Alepod** [comment]
> Could you try a more recent build, e.g. [this one](https://ci.appveyor.com/project/AaronVanGeffen/openloco/builds/26663016/artifacts)?

Did not help unfortunately

**Comment by AaronVanGeffen** [comment]
Are you saving to a folder you have write access to?

**Comment by duncanspumpkin** [comment]
Closing this as its been a while.
