### ISSUE TITLE
Missing non-integer scaling? 

### ISSUE THREAD

**Issue by Ryder17z** [OpenLoco/OpenLoco#376]
v19.03 

There is no obvious way to set the interface scaling to a non-integer value even though it looks like that should be possible

1.00 is a tad bit small, and 2.00 is too big for me.

**Comment by AaronVanGeffen** [comment]
Yes, the aim is to do this in much the same way OpenRCT2 does. However, we currently do not have a hardware-backed canvas to work with. Someone needs to implement that first.

**Comment by AaronVanGeffen** [comment]
@ZehMatt This could work properly if #418 has been tackled, too.
