### ISSUE TITLE
Alternative filesystem implementation

### ISSUE THREAD

**Issue by chfast** [OpenLoco/OpenLoco#381]
Hey,

I've noticed you are using `boost::filesystem` on macOS. I had similar issue in my project, but I had solved it differently - by using the https://github.com/gulrak/filesystem project. It provides drop-in replacement for `std::filesystem` as a single header. You can easily download the header from CMake and people will not even notice the dependency exists. Example: https://github.com/ethereum/evmone/blob/master/test/bench/CMakeLists.txt#L29-L36.

**Comment by IntelOrca** [comment]
Might be useful for https://github.com/OpenRCT2/OpenRCT2/issues/8032

**Comment by AaronVanGeffen** [comment]
This has since been implemented. Thank you!
