### ISSUE TITLE
Construction window crash

### ISSUE THREAD

**Issue by Milow** [OpenLoco/OpenLoco#383]
**OS:** Windows 10
**Commit/Build:**  b74c88ea12c07f018df651b7d9d516e4865407ca

**Steps to reproduce:**
1. Open either the build track or build road window
2. Click on the build station tab
3. Click back on the build track/road tab and the game will crash

Interestingly, if you build a piece of road or track first, then follow the steps above, the game does not crash.

**Comment by blargle-ragequit** [comment]
I'm also having crashes in the build window, running Arch Linux and same build of Loco.

**Comment by AaronVanGeffen** [comment]
Does the problem persist when using a build from https://github.com/OpenLoco/OpenLoco/pull/356 ?

**Comment by blargle-ragequit** [comment]
It doesn't seem to.  I'm getting a lot further without a crash on those builds.

**Comment by Milow** [comment]
I can confirm that pull request fixes the issue, in particular the only changes needed to fix it are to apply lines 790 & 792 in openloco/interop/hooks.cpp
