### ISSUE TITLE
Whistle sound volume does not scale with zoom

### ISSUE THREAD

**Issue by MellerYeller** [OpenLoco/OpenLoco#387]
**OS:**  Windows 10
**Version:**  19.03 release

When I zoom out fully, I can only hear a few whistles, but they are as loud as if I am zoomed in fully, unlike base where most if not all visible trains' whistles are audible, but very quiet.

**Steps to reproduce:**
1. Open a game with a decent system already in place
2. Zoom out fully

Video example: [https://youtu.be/umRCgPG9Gao](https://youtu.be/umRCgPG9Gao)

**Comment by AaronVanGeffen** [comment]
Has this been fixed by #809, by any chance?

**Comment by AaronVanGeffen** [comment]
Assuming this has been fixed.

**Comment by MellerYeller** [comment]
It has, sorry for not responding sooner.
