### ISSUE TITLE
Changing window scaling forces options window off screen

### ISSUE THREAD

**Issue by MellerYeller** [OpenLoco/OpenLoco#388]
**OS:**  Windows 10
**Version:**  19.03 release

When the options menu window has been moved a bit down and to the right, and the window scaling is increased (1x to 2x) the window leaves the range of the screen, which is alleviated only by reset of the game.

**Steps to reproduce:**
1. Open options menu
2. Move options menu window down and to the right (50 pixels each maybe, not sure on the exactness of that)
3. Increase scaling

Video Explaination: [https://youtu.be/CPIwT9BO9k4](https://youtu.be/CPIwT9BO9k4)

**Comment by loveletslive7** [comment]
This bug does not only affect the Options menu.
It affects any Window that is opened before changing the window scaling.

**Comment by loveletslive7** [comment]
Would closing all windows except the Options menu (and re-centering it) be acceptable?
I can accomplish that pretty easily.

Repositioning all open windows into a suitable location could be achieved, but would be more difficult.

**Comment by janisozaur** [comment]
I don't think that's a good solution. If it's anything like the other games, you can already close current window with backspace or all of them with shift backspace. I don't see doing this on every ratio change a good experience. In OpenRCT2 we had a request for hotkeys to change it and I assume people want to do it whilst building rides or having some other detail visible.

**Comment by janisozaur** [comment]
Just repositioning the options window should suffice and be enough of a solution.

**Comment by AaronVanGeffen** [comment]
It doesn’t help that currently only integer scales are supported. To support fractions, we’ll need to implement a hardware-backed SDL canvas. 

@janisozaur I believe you implemented this for OpenRCT2, right? Would you be willing to pick this up for OpenLoco?

**Comment by janisozaur** [comment]
I sure could, but as always short on time and this is such a good target for `good first issue`, especially with reference in OpenRCT2, I think I would leave it to someone else at least for now. @AaronVanGeffen can you create a ticket?

**Comment by AaronVanGeffen** [comment]
@janisozaur Good idea. #418

**Comment by seifer7** [comment]
I've fixed this. I will be submitting a pull request soon.
It'll also include fixes for issue #396 , and #264
