### ISSUE TITLE
android

### ISSUE THREAD

**Issue by rctfan** [OpenLoco/OpenLoco#394]
Hello

Is there a android version planned?

**Comment by janisozaur** [comment]
Is hard to say about "planned". It could happen one day, but that's long way in the future still, the current code still requires execution of the old x86 assembly, until that is resolved there's going to be little work on Android port. It can take a few years and currently development is slow.

**Comment by AaronVanGeffen** [comment]
In the mean time, if you'd like to play Locomotion on Android, there's the official port: [Transport Tycoon](https://play.google.com/store/apps/details?id=com.thirtyonex.TransportTycoon).
