### ISSUE TITLE
Setting preferred owner name does not work correctly

### ISSUE THREAD

**Issue by SokyranTheDragon** [OpenLoco/OpenLoco#396]
**OS:**  Windows 10
**Version:**   19.03
**Commit/Build:**  0162d4d

Selecting a preferred owner name and starting a new game causes to owner name to become `Unnamed` and the company name to become ` Transport` (including the space at the start). Trying to change it again and again does not fix it at all, and the name needs to be set manually every time.

**Steps to reproduce:**
1. Go to options menu (either in the main menu or in-game) and change your preferred owner name
2. Start a new game

**Comment by blargle-ragequit** [comment]
Confirming bug on b74c88e (latest master) on up-to-date Arch Linux.

**Comment by seifer7** [comment]
I've fixed this. I will be submitting a pull request soon.
It'll also include fixes for issue #388 , and #264
