### ISSUE TITLE
Deleting track with a signal on it costs ~$3.4 million

### ISSUE THREAD

**Issue by Gregory-404** [OpenLoco/OpenLoco#409]
**OS:** Windows 10
**Version:** 20.03
**Commit/Build:** 2e212af

Noticed after updating OpenLoco from v19.03 to v20.03. When deleting track with a signal on it, it costs too much. Deleting track alone results in receiving a normal amount of money back, so the issue is likely the signal. The cost seems to vary, though it is always ~$3.4m. Done in an unmodded install of OpenLoco. Seems to exist regardless of in-game year (under assumption it was related to inflation somehow), was tested in 1900, 1925, and 1956. Does not seem to exist prior to v20.03.

Additional testing reveals that deleting a signal, regardless of whether it is through the rail building tool or the signal placing tool, costs me ~$3.4m.

**Steps to reproduce:**
1. Start a scenario
2. Build a length of track
3. Place a signal on the track
4. Delete the signal

**Is the issue reproducible in Locomotion (vanilla)?**
In an install of Locomotion without OpenLoco, signals return a normal amount of money when they are removed in this way.

**Screenshots / Video:**
![Bugged OpenLoco](https://user-images.githubusercontent.com/62667512/77575383-af15aa00-6e90-11ea-984f-fbb72f721460.png)

![Bugged OpenLoco 2](https://user-images.githubusercontent.com/62667512/77576245-1ed86480-6e92-11ea-81c2-a999e11d248f.png)

![Bugged OpenLoco 3](https://user-images.githubusercontent.com/62667512/77596644-d3d24780-6eb9-11ea-9319-d2ce5fdd79a4.png)
Above: Removing a signal without removing the track beneath it still costs ~$3.4m

**Comment by blargle-ragequit** [comment]
I went to reproduce on Arch Linux (same build), and instead gained ~$7m for each deleted signal:

![Screenshot_20200326_094724](https://user-images.githubusercontent.com/15690966/77674435-d334c200-6f48-11ea-842a-b46b6b6deaa7.png)

**Comment by AaronVanGeffen** [comment]
Thanks for filing an issue. This sounds all too similar to #349, which I had hoped we'd tackled with  #356. It would seem that was not enough.
