### ISSUE TITLE
A few feature requests

### ISSUE THREAD

**Issue by Wuzzle** [OpenLoco/OpenLoco#411]
I've been using this mod for a long time now and i've played the vanilla game for at least a decade.
I've had a few ideas bubble up during that time and I figured i'd share them here where they might get added.

Some of these ideas are very unorthodox, others are just quality of life improvements i'd expect to be implemented later rather than sooner, if at all:

1. **Shuffling route destinations**
This is meant to help prevent vehicles from going to the same destinations at the same time.
A confirmation box would be a definite must here for obvious reasons.

2. **Amphibious hovercraft**
Hovercraft would still only service docks but they could also go over land that's at the same height as the water it's on or if it has a slope on it.

3. **Demolishing and/or moving pre-existing industries**
This one comes from the fact that as cities expand they tend to swallow up land that certain industries need to produce stuff and make them harder and more expensive to access in general.

4. **Adjustable passenger fare prices**
I'm surprised this isn't already a thing now that I think about it. You'd balance it by increasing and decreasing the number of passengers willing/able to use your services in proportion to how much you're charging.
If you wanted to you could even add luggage fees if you wanted to add another layer of complexity.

5. **The ability to buy obsolete vehicles**
This would ideally have two different versions, being able to buy leftover stock for a limited time after a vehicle is taken off the market, and buying old steam trains when you reach modern times and use them as a novelty to attract more passengers to your line.
You could even tie it into idea 4 and make passengers tolerate higher fare prices.

6. **Second hand vehicles**
The ability to buy vehicles from and sell vehicles to, other companies at a reduced price than what you brought it for/would normally pay for it.

7. **Public transit services run by cities**
Ideally this'd be optional. You could also buy the services from the council that made it and be able to sell your lines, routes and vehicles to the city it services for a bit of short term profit.

8. **Open stations**
Stations that anyone can use and the builder either gets a cut or can build the stations at notably reduced prices. This option wouldn't be available on maps without competing companies and they'd most commonly be built by councils.

9. **Improved city building AI**
Self-explanatory and because I can't be the only one bugged by how bad the councils are at building towns/cities/etc.

10. **Junction copying ala Cities Skylines**
This is pure quality of life. If you have one junction that already works you could copy it and use it elsewhere, so doing things like building junctions for dual track lines wouldn't as intimidating and scary because you can just use a junction made and tested by someone else.

That's all for now, i'll revisit this issue if I get more ideas.

**Comment by Wuzzle** [comment]
I wanted to suggest adding taxis but i've no idea how they'd work or be implemented

**Comment by pwnage2apps** [comment]
Some features (such improved AI) could be implemented with adapted OpenTTD code.

**Comment by Wuzzle** [comment]
> 
> 
> Some features (such improved AI) could be implemented with adapted OpenTTD code.

Improved AI is already being worked on, i'm talking about city building AI, please stay on topic and check the pre-existing issues first.

**Comment by AaronVanGeffen** [comment]
While I appreciate your enthusiasm for the project, I have to caution that the project is currently not at a stage where any of these can be feasibly implemented. It will take a long time, perhaps years, before they can be realised.

It is much easier to search for separate feature requests instead wading through wish lists like these, however. I will therefore close this issue. However, I would therefore like to encourage you to file separate issues for a few of your favourites.
