### ISSUE TITLE
Game crashes when changing from Windows to Fullscreen display mode (using clean install or empty openloco.yml)

### ISSUE THREAD

**Issue by seifer7** [OpenLoco/OpenLoco#429]
**OS:**  Windows 20
**Version:**  20.03
**Commit/Build:**  69b8a6749dc1846105f612c4b80cbdf4ddcaba8a

When using new install and/or display settings deleted from openloco.yml file
Game launches in Windowed mode, going to options and selecting Fullscreen causes game to crash.

This is **directly** related to PR# https://github.com/OpenLoco/OpenLoco/pull/426 and as such it I believe it should be reverted until further testing is done.

**Steps to reproduce:**
1. Clean install OpenLoco (or remove display settings from openloco.yml file)
2. Launch game (note: it defaults to Windowed mode)
3. Click options
4. Change display type to Fullscreen

**Is the issue reproducible in Locomotion (vanilla)?**
N/A

**Comment by AaronVanGeffen** [comment]
This is likely due to using an uninitialised resolution value (65554x65554, or -1x-1). If no resolution is defined yet, the first available should be used. 

I don’t think there’s a need to revert #426, as there aren’t many (if any) people running dev builds.

**Comment by seifer7** [comment]
@AaronVanGeffen I've created a new pull request# https://github.com/OpenLoco/OpenLoco/pull/431
It fixes this issue plus makes the display type control a lot more simple + reusable.
