### ISSUE TITLE
Feature request: add keyboard shortcut bindings for the slow/medium/fast simulation speed buttons

### ISSUE THREAD

**Issue by jgottula** [OpenLoco/OpenLoco#43]
In vanilla Locomotion, there are no keyboard shortcuts for the `>` `>>` `>>>` simulation speed buttons; the Keyboard Shortcuts options window only offers a binding for toggling the `||` button ("Pause/Unpause Game"; defaults to the `Pause` key). The omission is frankly a bit baffling.

(This is another feature request that'll have to wait a while, but I wanted to open it now.)

**Comment by AaronVanGeffen** [comment]
This can be tackled once #1141 has been merged.

**Comment by LeftofZen** [comment]
I don't seem to have permission to close this issue, but the changes for this were merged in with #1310 so this can be closed now.
