### ISSUE TITLE
Null bytes in openloco.yml preventing launch of OpenLoco

### ISSUE THREAD

**Issue by Svelbeard** [OpenLoco/OpenLoco#430]
**OS:**  Windows 10
**Version:**  20.03

**Commit/Build:**  69b8a67

After loco.exe asks for the path to the Locomotion Directory. The window disappears. Nul bytes have been added to the loco_install_path in openloco.yml see:

[openloco.txt](https://github.com/OpenLoco/OpenLoco/files/4515653/openloco.txt)

Deleting the nul bytes allows the game to launch.

**Steps to reproduce:**
1. Build in Visual Studio
2. run loco.exe and enter Locomotion Directory path

**Is the issue reproducible in Locomotion (vanilla)?**
No

**Comment by seifer7** [comment]
Confirmed that this bug occurs for me also.

**Comment by seifer7** [comment]
The commit that caues the issue is 821c26495efd682e7e248101b863efb1164dd30b
I'm looking into the changes now.

**Comment by seifer7** [comment]
Confirmed that the auto-detected path is saved correctly.
The bug only occurs when you need to manually select a path.

**Comment by AaronVanGeffen** [comment]
Thanks for investigating. I don't see how 821c26495efd682e7e248101b863efb1164dd30b could cause this, though. The new library that commit introduces is not used by the MSVC/Windows builds.

**Comment by seifer7** [comment]
It seems to stem from Line 67 of [platform.windows.cpp](https://github.com/OpenLoco/OpenLoco/blob/master/src/openloco/platform/platform.windows.cpp)

`result = utility::to_utf8(SHGetPathFromIDListLongPath(pidl));`

According to the debugger, function `SHGetPathFromIDListLongPath(pidl)` returns:
`Name | Value | Type
SHGetPathFromIDListLongPath(pidl) | L"G:\\Games\\GOG Games\\Locomotion" | std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> >

When I further inspect that variable it has a size of 260, capacity of 263, and then [0] - [28] contains the path, but [29] - [259] contains `\0`

The further processing, `utility::to_utf8` does not remove them.

**Comment by seifer7** [comment]
```
-		SHGetPathFromIDListLongPath(pidl)	L"G:\\Games\\GOG Games\\Locomotion"	std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t> >
		[size]	260	unsigned int
		[capacity]	263	unsigned int
+		[allocator]	allocator	std::_Compressed_pair<std::allocator<wchar_t>,std::_String_val<std::_Simple_types<wchar_t> >,1>
		[0]	71 'G'	wchar_t
		[1]	58 ':'	wchar_t
		[2]	92 '\\'	wchar_t
		[3]	71 'G'	wchar_t
		[4]	97 'a'	wchar_t
		[5]	109 'm'	wchar_t
		[6]	101 'e'	wchar_t
		[7]	115 's'	wchar_t
		[8]	92 '\\'	wchar_t
		[9]	71 'G'	wchar_t
		[10]	79 'O'	wchar_t
		[11]	71 'G'	wchar_t
		[12]	32 ' '	wchar_t
		[13]	71 'G'	wchar_t
		[14]	97 'a'	wchar_t
		[15]	109 'm'	wchar_t
		[16]	101 'e'	wchar_t
		[17]	115 's'	wchar_t
		[18]	92 '\\'	wchar_t
		[19]	76 'L'	wchar_t
		[20]	111 'o'	wchar_t
		[21]	99 'c'	wchar_t
		[22]	111 'o'	wchar_t
		[23]	109 'm'	wchar_t
		[24]	111 'o'	wchar_t
		[25]	116 't'	wchar_t
		[26]	105 'i'	wchar_t
		[27]	111 'o'	wchar_t
		[28]	110 'n'	wchar_t
		[29]	0 '\0'	wchar_t
		~~~ SNIP ~~~
		[259]	0 '\0'	wchar_t

```

**Comment by AaronVanGeffen** [comment]
I think it may be due to how the Windows version of `to_utf8` allocates its strings:
```
        auto result = std::string(sizeReq, 0);
```
My guess is that the `sizeReq` yielded by the line above is too high. Please try the following patch for utility/string.cpp:
```diff
         auto result = std::string(sizeReq, 0);
         WideCharToMultiByte(CP_UTF8, 0, src.data(), srcLen, result.data(), sizeReq, nullptr, nullptr);
+        result.erase(std::find(result.begin(), result.end(), '\0'), result.end());
         return result;
```
This is not a fix, just a workaround.

**Comment by seifer7** [comment]
Yes I thought about doing that, but do you think that could side affects elsewhere (modifying the string function)?
I thought perhaps a similar workaround but in the `prompt_directory` function so it doesn't affect anything else that uses the `to_utf8` function.
Opinion?

**Comment by AaronVanGeffen** [comment]
It's something that I'd prefer not to commit to the repo. Just to verify if it is indeed a case of too large a buffer.

I'd verify it myself, but this appears to be happening in the Windows code path only, and I'm on Linux.
