### ISSUE TITLE
Option for FPS display

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenLoco/OpenLoco#451]
Currently, there is no way to monitor FPS in-game. We would like there to be an option to do this, similarly to how OpenRCT2 achieves this.

This will require quite a bit of tinkering, but in principle, not much knowledge of the OpenLoco codebase is required. I am therefore labelling this a 'good first issue'.

For reference and inspiration, a relevant commit from OpenRCT2:
[add show fps](https://github.com/OpenRCT2/OpenRCT2/commit/ca01e55fa898ad1a021b627e42d157216a288286)

**Comment by janisozaur** [comment]
Having this would be great, the first step to watch for possible regressions like https://github.com/OpenRCT2/OpenRCT2/issues/7908
