### ISSUE TITLE
Openloco/ Locomotion On Mac Impressions/Questions

### ISSUE THREAD

**Issue by BlaxlandAlex3** [OpenLoco/OpenLoco#465]
Hi, I'm new here, this is my first post, please bear with me, and I apologize if this has been asked or answered before. I have a Mac, and am not sure on how to exactly run Locomotion with OpenLoco on it. I'm no coder or programmer, so if that sort of stuff is involved, there's a good chance I won't be able to figure it out. (Sorry). 

So any help with getting this all set up would be greatly appreciated! :)

Also I was wondering about multiplayer servers for Locomotion... 

Thanks!
Alex

**Comment by AaronVanGeffen** [comment]
Hi Alex,

Thanks for your interest in OpenLoco. You can run the game on macOS, but only if you haven’t yet upgraded to macOS 10.15 (Catalina). What version are you on?

Unfortunately, there is no feasible way for us to support macOS 10.15 and later in the near future. This is tracked in #

**Comment by BlaxlandAlex3** [comment]
Unfortunately, I just upgraded. I guess it's all over then. Thanks.

I would still like to know, how exactly was it supposed to work, with Loco on Mac?

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/wiki/Installation-on-Linux-and-macOS#steam

The steps would be the same for loco.

**Comment by BlaxlandAlex3** [comment]
Wine did work, however, but you could only access your games through the small steam icon at the top bar of a mac. Basically, it would not be able to connect Steam to the internet, and you could not go into your games library to access the local files to implement mods. I could try again.

**Comment by IntelOrca** [comment]
@BlaxlandAlex3 Unfortunately due to Apple dropping 32-bit support on macOS, the only way you can now play OpenLoco or Loco on your current system is using a virtual machine or booting into a different OS.

**Comment by BlaxlandAlex3** [comment]
Yeah, I'm aware of that.

**Comment by BlaxlandAlex3** [comment]
What I'm most likely going to do is purchase a windows laptop and make that my gaming laptop. 

Another question: Is it possible to have one vanilla game so I can play multiplayer with my friend and one OpenLoco game for single - player only with mods etc. ?

**Comment by AaronVanGeffen** [comment]
For what it's worth, Apple supports each major macOS version for three years after release. It is therefore still possible to downgrade to Mojave, assuming you have a Mac that didn't ship with Catalina. Doing so may be a bit time-consuming, however there are quite a few guides on the internet to help you if you decide to take this route.

**Comment by BlaxlandAlex3** [comment]
Thanks Aaron, But I don't think I'll go down that path. See my above post

**Comment by AaronVanGeffen** [comment]
Yes, custom objects are supported, but any modifications to the executable are not.

Unfortunately, this rules out certain mods, like the extended stations one. Eventually, the most popular of these features will be implemented in the core OpenLoco game, but we're not there yet.

**Comment by BlaxlandAlex3** [comment]
Ah, that's good to hear. I'm aware that you guys spend more time on OpenRCT2 than Lomo, is there any chance of OpenRCT2 being completed so that you can devote all your time to OpenLoco? I just cant wait for all these ideas and changes to come to fruition! :D

**Comment by BlaxlandAlex3** [comment]
Ah, that's good to hear. I'm aware that you guys spend more time on OpenRCT2 than Lomo, is there any chance of OpenRCT2 being completed so that you can devote all your time to OpenLoco? I just cant wait for all these ideas and changes to come to fruition! :D

**Comment by AaronVanGeffen** [comment]
The reverse engineering work for OpenRCT2 has been done for years, so the work we're putting in there now is very different from OpenLoco. It's still a fun project for us to work on, so I don't see that changing anytime soon.

(You do realise we're all doing this in our spare time, right? This is definitely a multi-year project.)

**Comment by duncanspumpkin** [comment]
And if you want it to be completed sooner well you've got enough time to learn how to code and start contributing

**Comment by BlaxlandAlex3** [comment]
Yes, i'm aware you're doing it in your spare time. Sorry if I'm sounding a bit too needy without actually contributing anything. Me, and the rest of the locomotion community really appreciate what you're doing. I have tried coding before, but I'm not sure it's for me.

**Comment by AaronVanGeffen** [comment]
No worries. Let's hope we can impress the community with our progress over the years to come.

Unless you have any further questions at this point, I think this issue can be closed?

**Comment by BlaxlandAlex3** [comment]
Yes, I think so, thank you all for answering!
