### ISSUE TITLE
Crash when opening narrow gauge tab on train purchasing window

### ISSUE THREAD

**Issue by js984** [OpenLoco/OpenLoco#478]
**OS:**  MacOS High Sierra 10.13.6
**Version:**  20.03

When I go into any scenario that includes narrow gauge vehicles (eg. Swiss Alps 1930), open the build new trains window, then open the narrow gauge tab, the game crashes. This was using a clean download

Edit: added note about clean download

**Steps to reproduce:**
1. Open Swiss Alps 1930
2. Open Build Trains Menu
3. Click Narrow Gauge tab
[Swiss Alps 1930.SV5.zip](https://github.com/OpenLoco/OpenLoco/files/4669075/Swiss.Alps.1930.SV5.zip)

**Comment by AaronVanGeffen** [comment]
You've omitted your OS and OpenLoco version. This is very important information to us. Is this using the v20.03 release, or did you download a development build somewhere?

**Comment by js984** [comment]
Oh I'm sorry!

OS: Mac High Sierra 10.13.6
Version 20.03

**Comment by AaronVanGeffen** [comment]
Thank you. I think I see what went wrong -- there are HTML comment tokens (`<!--` and `-->`) around the info in the issue, hiding the contents. Perhaps the issue template should be amended to leave them out.

As for the issue, I think this was solved by #413 -- I made a similar remark in that PR. Could you try the attached macOS build to verify the issue has been resolved for you as well? Thanks! If the issue has indeed been resolved, we should probably list this in the changelog for the next version, too. 

[OpenLoco-v20.03-203-gb2b9b06.zip](https://github.com/OpenLoco/OpenLoco/files/4669637/OpenLoco-v20.03-203-gb2b9b06.zip)

**Comment by js984** [comment]
It's all good now! Thanks

**Comment by AaronVanGeffen** [comment]
Thanks for confirming! I'll add it to the changelog then.
