### ISSUE TITLE
Bus exhaust smoke appears on the wrong end

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenLoco/OpenLoco#485]
**OS:**  Windows 10
**Version:**  20.05
**Commit/Build:**  a137181

Exhaust smoke for buses is added on the front end of the vehicle rather than the rear.

**Screenshots / Video:**
![Boulder Breakers](https://user-images.githubusercontent.com/604665/82754952-babe1800-9dd0-11ea-9e60-752a033cf169.png)

**Comment by duncanspumpkin** [comment]
Ah I thought that was a bug in my vehicle create functions.

**Comment by duncanspumpkin** [comment]
Issue caused by incorrect variable use. Type gets expanded from a int8 to an int32 during an addition in the assembly but this has not been done in loco causing an addition to end up being a negation. See referenced commit
