### ISSUE TITLE
`register_hook_stub` only remembers the last address passed

### ISSUE THREAD

**Issue by marijnvdwerf** [OpenLoco/OpenLoco#49]

**Comment by marijnvdwerf** [comment]
@janisozaur Any idea how to fix this easily?

**Comment by duncanspumpkin** [comment]
Can you store the addresss in an array?

**Comment by IntelOrca** [comment]
Is this a problem or are you experience calls on multiple threads?

**Comment by marijnvdwerf** [comment]
I guess my title was not clear enough.

The issue is that after this is executed:
```
    register_hook_stub(0x489cb5);
    register_hook_stub(0x489f1b);
    register_hook_stub(0x48a4bf);
    register_hook_stub(0x123);
```

Every call to either of these functions causes `00000123` to be logged.

**Comment by IntelOrca** [comment]
I guess you'll just have to make it a template function in the header so that you can use address inside the hook.

**Comment by duncanspumpkin** [comment]
Closing as this has been fixed for a while
