### ISSUE TITLE
Station/city name labels are hidden when saving.

### ISSUE THREAD

**Issue by conorsut1** [OpenLoco/OpenLoco#491]
**OS:**  Windows 10 Pro 1909
**Version:**  20.05
**Commit/Build:**  a137181

Station name labels and city name labels are hidden when saving the game.

**Steps to reproduce:**
1. Have station/city name labels enabled.
2. Save game.

**Is the issue reproducible in Locomotion (vanilla)?**
No.

**Screenshots / Video:**
https://www.youtube.com/watch?v=9xyxC_YxMIQ&feature=youtu.be

**Comment by jacobjdev** [comment]
Hello, I have run into this issue as well.

**Comment by AaronVanGeffen** [comment]
Looks like the main window's viewport flags are completely reset when saving. This including height marks, underground view, and the labels mentioned in this issue. When the browse window is closed without saving, the viewport flags are left untouched.
