### ISSUE TITLE
Mountain Mayhem scenario farms not producing grain for stations

### ISSUE THREAD

**Issue by jacobjdev** [OpenLoco/OpenLoco#494]
**OS:**  e.g. Windows 10 Pro 1903
**Version:**  e.g. 20.05
**Commit/Build:**  a137181

In the Mountain Mayhem scenario but the Trickleborough and Drumborough farms don't seem to produce any grain for train stations and cargo terminals.  I tried a new fresh save for it and I had the same issue.

**Steps to reproduce:**
1. New game using that scenario
2. Try creating a station around them, no grain goes to the station.

**Is the issue reproducible in Locomotion (vanilla)?**
No

**Comment by AaronVanGeffen** [comment]
Confirmed. Reverting 8c76881 fixes the issue, so it's a problem introduced in #472.

![Mountain Mayhem](https://user-images.githubusercontent.com/604665/82842826-4e7c0b00-9edb-11ea-9bc7-46e3627a3f9b.png)

**Comment by AaronVanGeffen** [comment]
Looks like #496 only fixed part of the problem. On Discord, users SoraTheReaper and Brushed Aluminum report they are still having problems with grain farms, livestock farms, and managed forests.
