### ISSUE TITLE
Incorrect Audio playing for vehicles

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenLoco/OpenLoco#504]
**OS:**  Windows 10
**Version:**  20.05.01
**Commit/Build:**  84729a

Incorrect audio can be played by vehicles after loading a save.

**Steps to reproduce:**
1. Load two saves with a different audio (for example one which only has diesel and newer trains and one with older trains such as steam)
2. Observe the audio on the second save for a variety of vehicles

**Is the issue reproducible in Locomotion (vanilla)?**
No

**Screenshots / Video:**
https://www.youtube.com/watch?v=KX96cm7O-SA&feature=youtu.be

Issue is being caused by `_object_samples` in `audio.cpp` not being cleared after loading a new save. This causes object id's that have been allocated to a different audio source to be incorrectly associated with previously loaded audio.

Fix would be to clear `_object_samples` when loading a save.

**Comment by AaronVanGeffen** [comment]
Is this still an issue?

**Comment by duncanspumpkin** [comment]
Shouldn't be anymore

**Comment by duncanspumpkin** [comment]
Shouldn't be anymore

**Comment by duncanspumpkin** [comment]
Shouldn't be anymore
