### ISSUE TITLE
Game absolutely refusing to start

### ISSUE THREAD

**Issue by Derpercoaster** [OpenLoco/OpenLoco#511]
OS: Windows 10
Version: 1909, Build 18363.900

Issue: When I try to start the game, it shows the usual command prompt, but immediately afterwards, the game closes itself without even getting to the pre-game credits. On top of this, the game never "freezes," or stops responding. It just never starts.

Steps to reproduce: I honestly have no idea. All I do is attempt to start the program, and it never starts.

Can be reproduced in original game: No (to my knowledge)

**Comment by AaronVanGeffen** [comment]
Version 19.09 is an old release of the game with this as a known bug. Please try the latest release, version 20.05.1, instead.

You may need to delete the game config before version 20.05.1 will work.

**Comment by Derpercoaster** [comment]
The version I have is 20.05. 1909 is my windows build. (It said to specify that so I did).

**Comment by AaronVanGeffen** [comment]
> The version I have is 20.05. 1909 is my windows build. (It said to specify that so I did).

Oh, no, that's not what we meant in our issue template. Your Windows build version is irrelevant to us, but the OpenLoco version very much is!

> Also, where do I find the game config?

On Windows, it should be in `%APPDATA%\Roaming\OpenLoco`.

**Comment by Derpercoaster** [comment]
Huh. I can't seem to find it in that area. I tried looking it up in file explorer, but it couldn't find it.
I also can't see the folder just by navigating by myself.

**Comment by AaronVanGeffen** [comment]
The 'AppData' folder is hidden by default, but it's a member of your user folder. You should be able to access it directly through `cmd`, or explorer's address bar. Alternatively, you can make it visible by making explorer show hidden folders. (I'd take a screenshot for you, but I'm not on Windows, myself.)

**Comment by Derpercoaster** [comment]
I finally got this to work. Thank you so much! I think this can be closed now.
