### ISSUE TITLE
Playing game fullscreen requires deletion of game.cfg, openloco.yml on next attempt to launch game.

### ISSUE THREAD

**Issue by Derpercoaster** [OpenLoco/OpenLoco#514]
OS: Windows 10
Version: 25.05.1
Build: Unknown (I downloaded the version I have on June 15th, if that helps.)

Issue: I opened the game and set it to fullscreen, played a while, and then quit. When I attempted to start the game again, It never started, and only would do so after I deleted both the game.cfg file and the openloco.yml file. I tried playing in windowed mode and borderless fullscreen, and this issue never occurred.

To reproduce:

1 Start the game.
2. Set to fullscreen mode.
3. Close the game (playing anything isn't required).
4. Attempt to launch the game. It will fail and not give a reason why.

Repeat the above steps for windowed mode and fullscreen borderless mode. Note that the game will run perfectly without issues, regardless of how many times it is started and quit.

Bug in original game: No. OpenLoco relies on files that the original game does not rely on.

**Comment by AaronVanGeffen** [comment]
Could you attach a failing openloco.yml file?

**Comment by AaronVanGeffen** [comment]
I'm closing this on the assumption this does not happen in v20.10.

**Comment by Derpercoaster** [comment]
> I'm closing this on the assumption this does not happen in v20.10.

It does not appear to, although fullscreen still has issues.
