### ISSUE TITLE
Sound plug-in object improper dependencies in scenarios

### ISSUE THREAD

**Issue by spacek531** [OpenLoco/OpenLoco#520]
It's been a while since I dealt with Locomotion objects, so please bear with my hazy memory. I believe people talk about it in the Locomotion subforum of TT-forums.

The bug is that if you have custom sound objects installed, creating new scenarios will improperly add these sounds to the required objects.

**Steps to reproduce:**
1. Install custom sound object (pikabird MSTS packs, etc.)
2. Create new scenario, do not select any object that uses custom sound object
3. Uninstall custom sound objects
4. Scenario will not load because custom sound objects required

**Comment by AaronVanGeffen** [comment]
I think this has been addressed with #1925. Please comment to reopen if we haven't.
