### ISSUE TITLE
Snow rendering problems using Steam game version

### ISSUE THREAD

**Issue by Zcooger** [OpenLoco/OpenLoco#528]
**OS:**  Windows 7 x64
**Version:**  20.05.1
**Commit/Build:**  (d0d7686 on master)

**Steps to reproduce:**
Load attached game or any other and look for some snow on different zoom factors.

**Is the issue reproducible in Locomotion (vanilla)?**
No

**Screenshots / Video:**
Vanilla 0 - Ok
Open 0 - Ok
Vanilla 1 - Ok
![vanilla-1](https://user-images.githubusercontent.com/42012614/86893346-04e52980-c0f1-11ea-8673-c7a76b5d6a5e.png)
Open 1 - Errors
![open-1](https://user-images.githubusercontent.com/42012614/86893351-06aeed00-c0f1-11ea-9e3c-ab903fade0c5.png)
Vanilla 2 - Ok
![vanilla-2](https://user-images.githubusercontent.com/42012614/86893359-0878b080-c0f1-11ea-8025-4548925edba9.png)
Open 2 - Errors
![open-2](https://user-images.githubusercontent.com/42012614/86893362-09a9dd80-c0f1-11ea-856a-f1d3178c67ed.png)
Vanilla 3 - Ok
![vanilla-3](https://user-images.githubusercontent.com/42012614/86893370-0adb0a80-c0f1-11ea-9062-040f011b00d2.png)
Open 3 - Ok
![open-3](https://user-images.githubusercontent.com/42012614/86893376-0ca4ce00-c0f1-11ea-9d59-969e95dcea88.png)

**Save game:**
[North America (Mid) 1945.7z.zip](https://github.com/OpenLoco/OpenLoco/files/4889244/North.America.Mid.1945.7z.zip)

**Comment by AaronVanGeffen** [comment]
This is a bit puzzling, as we're still using the original routines for updating the snow lines and rendering them. I wonder what's going wrong. I haven't noticed any oddities myself, either.

Perhaps this is due to a difference in assets between the Steam and GOG versions of the game? We'll have to investigate.

**Comment by Zcooger** [comment]
Yes, GOG version and my original CD look normal.
![image](https://user-images.githubusercontent.com/42012614/86904796-ba6ba900-c100-11ea-9452-c69eca1fa2ec.png)

**Comment by Zcooger** [comment]
Steam
```
Name: SNOW.DAT
Rsize: 52595 bytes (51 KiB)
CRC32: 5EB232E2
```
GOG/CD
```
Name: SNOW.DAT
Size: 52634 bytes (51 KiB)
CRC32: 32D1E10A
```

**Comment by AaronVanGeffen** [comment]
Thanks. So far, we have only looked at compensating for differences in G1.dat. This begs the question what other differences there might be between the objects in both versions. I think we still want to support both, though.

**Comment by Zcooger** [comment]
I've tried MD5/CDC32 duplicate search between Steam and GoG versions. No duplicates found. All files are different to some degree.

**Comment by AaronVanGeffen** [comment]
Thanks, that's interesting to say the least. There may be other incompatibility problems we're not yet aware of, then.

We haven't implemented object loading yet, and still rely on the vanilla routines there. Once we have our own implementation, we can hopefully take both versions into account.

**Comment by Derpercoaster** [comment]
> This is a bit puzzling, as we're still using the original routines for updating the snow lines and rendering them. I wonder what's going wrong. I haven't noticed any oddities myself, either.
> 
> Perhaps this is due to a difference in assets between the Steam and GOG versions of the game? We'll have to investigate.

It might have to do with assets. I use the Steam version too, and every time the game is booted in Openloco, the output log throws an error (which it then corrects as far as I can tell) related to it being the Steam version.

![image](https://user-images.githubusercontent.com/60452987/137604523-837215b7-3a68-4d2f-9d50-616defdf6b69.png)

This is the error I see.

**Comment by Derpercoaster** [comment]
It seems that Openloco is, by default, expecting values that only the disc version provides.
