### ISSUE TITLE
Save game crashes on 18th march after livestock farm release fixes

### ISSUE THREAD

**Issue by Zcooger** [OpenLoco/OpenLoco#531]
**OS:**  Windows 7 x64
**Version:**  20.05.1
**Commit/Build:**  a9a0d68 (regression from 20.05.1 release)

Game crashes in the scenario on 18th march.

**Steps to reproduce:**
1. Run the game.
2. Load save game.
3. Open livestock farm graph.
4. Set highest tempo.
5. Click on the train.

**Is the issue reproducible in Locomotion (vanilla)?**
No

**Screenshots / Video:**
https://dbree.org/v/5f0639

**Save game:**
[US no snow.SV5.txt](https://github.com/OpenLoco/OpenLoco/files/4893507/US.no.snow.SV5.txt)

**Crash dump:**
https://dbree.org/v/205f06

**Comment by AaronVanGeffen** [comment]
We need to narrow this down to a change set. I can't see how the livestock farm fixes could do this.

Does this happen on 433c35344bbde0745f579d272037aa8313e350a9 ([builds](https://github.com/OpenLoco/OpenLoco/runs/846932788)), or 5e2c51539d52ee3769c4f85ec60cf1c861593af1 ([builds](https://github.com/OpenLoco/OpenLoco/runs/847045864))? Both were merged before the livestock farm fixes. Indeed, the latter might explain why vehicles are affected.

**Comment by Zcooger** [comment]
433c353 - No crash, farm not working.
![Screenshot](https://user-images.githubusercontent.com/42012614/87181231-767bce00-c2d1-11ea-8e73-06ca1152a39e.png)
5e2c515 - 18th march crash, farm not working.
![image](https://user-images.githubusercontent.com/42012614/87181437-dbcfbf00-c2d1-11ea-96cd-56ee8cfd1294.png)

**Comment by duncanspumpkin** [comment]
@Zcooger unfortunately if you created a vehicle after https://github.com/OpenLoco/OpenLoco/commit/5e2c51539d52ee3769c4f85ec60cf1c861593af1 and then saved you will have corrupted the save. I couldn't open your specific save as I don't have the objects but I'm pretty sure my fix will solve this from happening.

**Comment by Zcooger** [comment]
I can open this save without crash on vanilla. Does it mean anything?

**Comment by AaronVanGeffen** [comment]
@Zcooger Thanks for verifying. #534 should fix the issue. Unfortunately, the issue has corrupted the vehicle routing tables. See the PR for details. I hope it won't cause too much grief for you.

Being able to open it in vanilla without problems does not mean much, unfortunately. @duncanspumpkin and I just couldn't open it due to missing custom plugin objects.

**Comment by duncanspumpkin** [comment]
It is interesting that it works in vanilla maybe there is another issue. Is there any way you can provide all your objects?

**Comment by Zcooger** [comment]
[US no snow-4th-september-crash.SV5.txt](https://github.com/OpenLoco/OpenLoco/files/4905019/US.no.snow-4th-september-crash.SV5.txt)
I reopened the save in vanilla and saved again, then opened it in ce882d2. The crash occurs at 4th september.
Here's new dump file: https://dbree.org/v/81018c
Here is my ObjData folder: https://dbree.org/v/8c355a
This scenario was provided with the original game so I did not include any additional objects.

**Comment by duncanspumpkin** [comment]
Thanks for the obj folder. I was able to open it and it is not crashing for me anymore on the 4th september after ce882d2 is applied.

**Comment by duncanspumpkin** [comment]
I also checked it against the broken version. The reason its crashing on 18th March is due to the AI building a vehicle and hitting my bug that ce882d2 fixes.

**Comment by Zcooger** [comment]
After ce882d2, it was no longer possible to cause an error (fresh games with livestock and grain farms working as usual).
