### ISSUE TITLE
Repetitve main menu crash (title background game is the cause?)

### ISSUE THREAD

**Issue by Zcooger** [OpenLoco/OpenLoco#537]
**OS:**  Windows 7 x64
**Version:**  20.05.1
**Commit/Build:**  0d6dc5e & 0d6dc5e

Repetitve crash when main menu is opened.

**Steps to reproduce:**
Open the game and stay on the main menu.

**Is the issue reproducible in Locomotion (vanilla)?**
No

**Screenshots / Video:**
https://www.youtube.com/watch?v=0OBmlLDhf-U

**Crash dump:**
https://dbree.org/v/9efa32

**Comment by duncanspumpkin** [comment]
This should be fixed by #534. In the video the main menu spawns a vehicle almost exactly at the same time as the crash and I no longer crash after the application of #534.

**Comment by duncanspumpkin** [comment]
Fixed in #534. Confirmed by @Zcooger
