### ISSUE TITLE
Game silently ends process when browsing for C: drive (NVMe one)

### ISSUE THREAD

**Issue by Zcooger** [OpenLoco/OpenLoco#538]
**OS:**  Windows 7 x64
**Version:**  20.05.1
**Commit/Build:**  0d6dc5e & many before

OpenLoco might crash if you browse for savegame/scenario/landscape on the C: letter/System/NVMe volume.
The rest of the drives are SATA and USB 3.0 flash memory.

**Steps to reproduce:**
1. Open the game.
2. Load a savegame/scenario/landscape on C: drive or NVMe volume.

**Is the issue reproducible in Locomotion (vanilla)?**
No

**Screenshots / Video:**
https://www.youtube.com/watch?v=2yb_5B4dn4E

**Crash dump:**
https://dbree.org/v/5f09f3

**Comment by duncanspumpkin** [comment]
It's creating on a std filesystem call. I was getting this as well but haven't investigated it much.

**Comment by Zcooger** [comment]
👍 
![image](https://user-images.githubusercontent.com/42012614/87256294-c1881380-c480-11ea-8ecc-b5828400fe64.png)
