### ISSUE TITLE
Toggling station catchment area not invalidating map properly

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenLoco/OpenLoco#558]
**OS:**  Arch Linux
**Version:**  20.05.1+
**Commit/Build:**  b46d0bceb32fa3488b5e792c652d2d58cd656ff1

Toggling the catchment area in the station window is not invalidating the map properly:

![Screenshot](https://user-images.githubusercontent.com/604665/88392540-7513d080-cdbc-11ea-93b3-0b6d91172a6a.png)

**Comment by AaronVanGeffen** [comment]
And yes, the AI is undermining my transport operation…! :stuck_out_tongue:

**Comment by Svelbeard** [comment]
The station catchment area also stays after the window is closed unlike vanilla
