### ISSUE TITLE
Trying to open "Road Construction" with "One-Way Road Construction" open crashes the game

### ISSUE THREAD

**Issue by qstar-inc** [OpenLoco/OpenLoco#573]
**OS:**  Windows 10
**Version:**  20.07
**Commit/Build:**  1dcc29b

Trying to open "Road Construction" with "One-Way Road Construction" open crashes the game.

**Steps to reproduce:**
1. Open "One-Way Road Construction" panel
2. Switch to station/depot tab 
3. With that panel open, open (normal 2 way) "Road Construction" panel
4. CONGRATULATIONS! You've successfully made it stuck.

**Is the issue reproducible in Locomotion (vanilla)?**
No, I think.

**Screenshots / Video:**
https://youtu.be/A05VxAdfbag

**Comment by AaronVanGeffen** [comment]
Unable to reproduce. It's possible that this doesn't happen in all scenarios — that is, it depends on what objects are available. Which scenario did you try?

![Screenshot 2020-08-09 at 17 26 14](https://user-images.githubusercontent.com/604665/89735823-72280980-da65-11ea-9448-ef6aa0998a47.png)

**Comment by qstar-inc** [comment]
> 
> 
> Unable to reproduce. It's possible that this doesn't happen in all scenarios — that is, it depends on what objects are available. Which scenario did you try?
> 
> ![Screenshot 2020-08-09 at 17 26 14](https://user-images.githubusercontent.com/604665/89735823-72280980-da65-11ea-9448-ef6aa0998a47.png)

Sorry I missed a step on my steps to reproduce. I've updated my previous comment. Open 1-way > Switch to Passenger Stop tab > Open Road construction > CRASH!

**Comment by Svelbeard** [comment]
@qstar-inc could you downloading the artifacts (on the right hand side) of the following build https://github.com/OpenLoco/OpenLoco/pull/578/checks unzip the files and run openloco.exe to see if it's fixed the bug for you please?

**Comment by qstar-inc** [comment]
Hello @Svelbeard I've tried the build and that particular bug is no longer there.
