### ISSUE TITLE
Build window cargo capacity

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenLoco/OpenLoco#581]
**Version:**  20.07
Taken from discord
I have found a new bug. Every year (when the prices and values of vehicles change) the capacities of the cargo wagons will break.

**Comment by fjack125** [comment]
Just to expand on this a bit.

**Original Game Version: Steam**
**Operating System: Windows**

This occurs when hovering over the cargo wagon in question, when hovering over a different wagon and returning to the first, it will rectify the issue and display the normal amount. See below for bug.

![broke wagon](https://user-images.githubusercontent.com/69923761/90683033-d31dc180-e25d-11ea-8579-0d80517dcce0.png)
