### ISSUE TITLE
Z Key doesn't rotate track/road

### ISSUE THREAD

**Issue by fjack125** [OpenLoco/OpenLoco#582]
**OS:** Windows 10
**Version:** 20.07
**Commit/Build:** 1dcc29b

Pressing the Z key to rotate a road/track piece does not rotate said piece when in the build menu. It however can still be rotated by pressing the rotate button (red arrow) in the menu. The track will flash for a moment as if it is changing the sprite, but it will remain the same direction

**Steps to reproduce:**
1. Load my scenario or a new scenario.
2. Open up the track builder menu or road builder (type doesn't matter).
3. Press the Z key to rotate the straight piece, observe as it doesn't rotate.

**Is the issue reproducible in Locomotion (vanilla)?**
No.

**Screenshots / Video:**
![Track machine broke](https://user-images.githubusercontent.com/69923761/90751260-ccc72e00-e2cd-11ea-89f1-8acf44e8eec3.png)

**Save game:**
[Boulder Breakers (Comp).txt](https://github.com/OpenLoco/OpenLoco/files/5101936/Boulder.Breakers.Comp.txt)

**Comment by senner007** [comment]
Confirmed
