### ISSUE TITLE
CRASH_DUMP and DEBUG_AUTO_DUMP saves are invalid

### ISSUE THREAD

**Issue by CodingKoopa** [OpenLoco/OpenLoco#584]
**OS:**  Arch Linux
**Version:**  20.07-32
**Commit/Build:** a4e4392

When OpenLoco crashes, it seems to produce files in `Locomotion/Single Player Saved Games` with the save `SV5` extension, of the same file sizes of saves, so I assume these are meant to be "emergency" autosaves for when the game crashes. However, out of the `CRASH_DUMP000000000x.SV5` and `DEBUG_AUTO_DUMP.SV5` files in my save folder, both vanilla Locomotion and OpenLoco show that the "File contains invalid data". If these are meant to be functional saves, they should work. If these are not meant to be functional saves, perhaps these shouldn't be put in the save directory, or their purpose be documented.

If the events leading up to the crash corrupted the game state in an unpredictable way that is causing this save data to be invalid, then that's understandable - in that case, it would be nice to document the possibility of this occurring, somewhere ;)

**Steps to reproduce:**
1. Trigger a game crash. My crashes are seemingly random, so I don't have any specific reproduction steps for this.
2. Load one of the DUMP saves.

**Is the issue reproducible in Locomotion (vanilla)?**
I'm not sure, as I haven't observed vanilla Locomotion crash while playing (but the string `CRASH_DUMP` doesn't turn up in the OpenLoco source, so I assume this functionality is implemented in the original game?).

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/13039555/90987760-5b041400-e55b-11ea-96fe-a2018f9246c0.png)
![image](https://user-images.githubusercontent.com/13039555/90987763-622b2200-e55b-11ea-9717-1c3e9c9313e8.png)

**Save game:**
[CRASH_DUMP0000000001.SV5.zip](https://github.com/OpenLoco/OpenLoco/files/5114842/CRASH_DUMP0000000001.SV5.zip)
[CRASH_DUMP0000000002.SV5.zip](https://github.com/OpenLoco/OpenLoco/files/5114843/CRASH_DUMP0000000002.SV5.zip)
[DEBUG_AUTO_DUMP.SV5.zip](https://github.com/OpenLoco/OpenLoco/files/5114844/DEBUG_AUTO_DUMP.SV5.zip)

**Comment by AaronVanGeffen** [comment]
Interesting! I have never seen these before.

**Comment by CodingKoopa** [comment]
I've gotten the vanilla game to make the files. Running it in Proton, starting the tutorial either crashes the game immediately (creating a `CRASH` save), or proceeds normally, and creates a `DEBUG_AUTO_DUMP` save. In fact, some of the saves I attached may be from that, as I had tried the tutorials as well as experienced an OpenLoco crash around the same times.
