### ISSUE TITLE
Changing default sound device prevents launching OpenLoco; can't find openloco.yml

### ISSUE THREAD

**Issue by PaperPlayerX** [OpenLoco/OpenLoco#588]
**OS:** Windows 10
**Version:** 20.07

I downloaded v20.07 for the first time just today, changed a few options, notably the default sound device, played Boulder Breakers as a test, and closed the game. Now, the command window and game window open for a split second before immediately closing with no explanation. Even deleting the files I'd just downloaded and redownloading them didn't fix it, presumably because there are other files I can't find. I saw the issue posted earlier in July about needing to delete openloco.yml, but I can't even find it! If I knew where to look for openloco.yml and deleted it, I should be set.

**Steps to reproduce:**
1. Open OpenLoco
2. Change the default sound device
3. Close OpenLoco

Apologies if I'm not handling this issue correctly, I only just today discovered this project exists.

**Comment by PaperPlayerX** [comment]
Didn't think to look in %appdata% until now. Major apologies for creating a redundant issue thread.

**Comment by IntelOrca** [comment]
@PaperPlayerX This is still something that should be fixed. So I have re-opened.
