### ISSUE TITLE
Add some screenshots in the README

### ISSUE THREAD

**Issue by neuromancer** [OpenLoco/OpenLoco#59]
I think people will be more interested in testing this re-implementation and maybe collaborate with some code if you show the current state of this port.

**Comment by duncanspumpkin** [comment]
At present there is no visual change to the base game but i agree it would make sense to add an image.

**Comment by neuromancer** [comment]
>At present there is no visual change to the base game

This is great! In any case, a screenshot of the game running in Linux/OSX could be very nice.

**Comment by AaronVanGeffen** [comment]
A screenshot has since been added.
