### ISSUE TITLE
Crash to desktop when toggling between build menus in main toolbar

### ISSUE THREAD

**Issue by Jeanfeels** [OpenLoco/OpenLoco#592]
**OS:**  Windows 10
**Version:**  20.07 (Latest release as of writing)
**Commit/Build:**  1dcc29b

This is a very easy to reproduce, if sometimes seemingly random, CTD-causing glitch involving a straight up crash without errors or other debug information I could see. The most reliable way to reproduce it for debug purposes is below, and I have uploaded a video of it in action.

Note that while this is the most reliable way, it is not the only situation in which it has occured. The first time was after an hour of play - it may be to do with the very first time clicking the port icon when airports are not yet unlocked, but that's a completely wild guess without anything backing it up as i haven't tested this. The crash is essentially immediate, and no errors appear.

Do note that I have seen another glitch that may or may not be related on this in play that i have yet to reliably reproduce in a recording in which the currently open build menu has a major visual glitch and stops responding, requiring switching away from it using the other menus.  

**Steps to reproduce:**
1. Start a new game
2. Single click the road icon in the main toolbar (the main icon, not the sub-menu that appears on hover)
3. Single click the port icon on the toolbar (the main icon, not the sub-menu that appears on hover)

**Is the issue reproducible in Locomotion (vanilla)?**
Unknown; Loco original does not run on my system. Testing would be appreciated.

**Screenshots / Video:**
https://youtu.be/2vbXc7hmJIs

**Comment by AaronVanGeffen** [comment]
We released v21.02 today. Does the problem persist on that version?

**Comment by AaronVanGeffen** [comment]
Assuming this has been resolved.
