### ISSUE TITLE
Consistently Timed Crash of Unknown Cause

### ISSUE THREAD

**Issue by PaperPlayerX** [OpenLoco/OpenLoco#596]
**OS:** Windows 10
**Version:** 20.07

Doing a casual playthrough on a custom scenario with random gen (not sure if relevant), and the game crashes consistently for an unknown reason. All I know is that it happens at the exact same time, _every_ time, and that it does _not_ happen in the original game, only in OpenLoco. I tried to investigate what in particular could be happening at the time of the crash to cause it, but there are so many moving parts that I wouldn't know where to begin. I attached the save if anyone thinks they can find the cause.

**Steps to reproduce:**
1. Load the attached save in OpenLoco.
2. Wait until Train 10 is about to stop at the factory (not the definitive cause, just a good frame of reference for what time the crash occurs).
3. Game crashes.

**Is the issue reproducible in Locomotion (vanilla)?**
No, surprisingly.

**Save game:**

[crashing_save.zip](https://github.com/OpenLoco/OpenLoco/files/5157895/crashing_save.zip)

**Comment by duncanspumpkin** [comment]
As this save was created during the time when there was a mistake in CreateVehicle I think we can close this as resolved as it is most likely related to that.
