### ISSUE TITLE
Track construction indicator is askew

### ISSUE THREAD

**Issue by shdeva** [OpenLoco/OpenLoco#625]
**OS:**  Win10
**Version:** 20.07
**Error found based on Steam version of Locomotion, other versions not tested**

When building diagonally the orange outline showing what blocks a track piece will occupy is rotated 90° counterclockwise to where it should be.

**Steps to reproduce:**
1. Start building train tracks
2. Build first half of a large curve

**Is the issue reproducible in Locomotion (vanilla)?**
No.

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/70460715/93029992-84114500-f5ed-11ea-983c-af4650d314c0.png)
![image](https://user-images.githubusercontent.com/70460715/93029997-8bd0e980-f5ed-11ea-8413-fa77c7954a15.png)

**Comment by AaronVanGeffen** [comment]
We had trouble reproducing this issue. Today, we released v21.02. Does the problem persist on that version? If so, could you tell us a bit more on how we reproduce it? Thanks.
