### ISSUE TITLE
Crash at a specific time. Repeatable

### ISSUE THREAD

**Issue by 3shirts** [OpenLoco/OpenLoco#630]
Windows 10
20.07

**Steps to reproduce:**
1. Load attached save
2. Wait a few seconds (until game date of 2nd December 1938)

**Is the issue reproducible in Locomotion (vanilla)?**
Yes. It also crashes with a Access Violation error message.

**Save game:**
[Oil Oasis.SV5.txt](https://github.com/OpenLoco/OpenLoco/files/5246708/Oil.Oasis.SV5.txt)

The game ran fine up until just after this save. Just as the date changes to December 1938 it crashes every time.

**Comment by AaronVanGeffen** [comment]
The save crashes for me on Linux as well.
```
Process 6344 stopped
* thread #1, name = 'openloco', stop reason = signal SIGSEGV: invalid address (fault address: 0xd5482002)
    frame #0: 0x004a3f85 openloco`_binary__home_aaron_Repositories_OpenLoco_build_openloco_text_start + 667525
openloco`_binary__home_aaron_Repositories_OpenLoco_build_openloco_text_start:
->  0x4a3f85 <+667525>: cmpb   0x2(%esi), %dl
    0x4a3f88 <+667528>: jne    0x4a3fbe                  ; <+667582>
    0x4a3f8a <+667530>: movb   (%esi), %al
    0x4a3f8c <+667532>: andb   $0x3c, %al
```

That's in `sub_4A3EF6`, which we haven't implemented in C++ yet.

**Comment by duncanspumpkin** [comment]
As this save was created during the time when there was a mistake in CreateVehicle I think we can close this as resolved as it is most likely related to that.
