### ISSUE TITLE
Spacebar (or other key if remapped) works to show recent message but it doesn't dismiss it.

### ISSUE THREAD

**Issue by 3shirts** [OpenLoco/OpenLoco#632]
Windows 10
20.07

The keyboard shortcut (spacebar by default) to show and hide the messages like 'citizens celebrate' or 'new land speed record' only works to show them, not to dismiss them.

**Steps to reproduce:**
1. Press spacebar to recall most recent message item (works as intended)
2. Press it to dismiss the current showing message (does not work)

**Is the issue reproducible in Locomotion (vanilla)?**
No. In vanilla the keyboard shortcut works correctly for show and dismiss.

**Comment by marijnvdwerf** [comment]
Fixed by #676
