### ISSUE TITLE
Games crashes after clicking on Train Name to edit name

### ISSUE THREAD

**Issue by poland153** [OpenLoco/OpenLoco#653]
**OS:** Microsoft Windows 10 Pro
**Version:**  10.0.18363 Build 18363
**Commit/Build:**  OpenLoco, v20.07 (1dcc29b on master)

Came crashes after clicking on the title of a train with the intention of editing the name. This doesn't happen always. Seems to be random at times. 

**Steps to reproduce:**
1. Have train window open.
2. Click on train name 
3. Edit Name window opens and then game crashes

**Is the issue reproducible in Locomotion (vanilla)?**
No

**Screenshots / Video:**
![openloco crashes](https://user-images.githubusercontent.com/10625890/95383613-08837a80-08b1-11eb-8437-52cd39009e78.png)

**Save game:**
[savegame.zip](https://github.com/OpenLoco/OpenLoco/files/5343612/savegame.zip)

**Comment by duncanspumpkin** [comment]
I can't reproduce this. Could you check see if it is still occuring.

**Comment by poland153** [comment]
I'm not able to reproduce either. For what its worth I am currently on v20.10 so maybe something in that release fixed it? 🤷 Anyways, closing issue.
