### ISSUE TITLE
Question: do this have crashlogs? Frustrating crash I wouldn't know how to reproduce.

### ISSUE THREAD

**Issue by JSJosh** [OpenLoco/OpenLoco#655]
OS: Windows 10
Version: 20.07

Hi, this is not proper formatting, I know, but I suffered a frustrating crash yesterday that of which I do not even know the cause or how to reproduce it. I was just playing campaign games one after another and far into the easy oil campaign, I noticed that the airplanes had negative capacity of passengers, I think at the integer limit; then when I went to another tab it crashed, losing a lot of progress.
I have no idea what caused this or how to even help you guys, it just happened during what I would call a normal game. Are there any crashlogs with OpenLoco? It would such if this would happen again. Maybe autosaves would also help.

**Comment by duncanspumpkin** [comment]
Unfortunatly 20.07 has a bug in the vehicle creation code that will eventually cause a crash. Its fixed in the master branch and we will send out an updated build hopefully sometime this month.

**Comment by IntelOrca** [comment]
@JSJosh you can try out the latest development build by downloading the latest build artefacts:

https://github.com/OpenLoco/OpenLoco/actions/runs/297788859

**Comment by JSJosh** [comment]
How does openloco handle a new install over itself? Do I lose any of my saves?

**Comment by IntelOrca** [comment]
These are just portable builds, you can extract them wherever you like or overwrite your existing build. Saves are not lost.

**Comment by JSJosh** [comment]
Ok I extracted it to my openloco folder, is this the right version?

![image](https://user-images.githubusercontent.com/34352316/95622564-26381780-0a4a-11eb-9655-164557600efe.png)

**Comment by AaronVanGeffen** [comment]
@JSJosh That is the v20.07 release version (1dcc29b), not the latest master build. See e.g. the artifacts over at https://github.com/OpenLoco/OpenLoco/actions/runs/297681440 for the newest build at the time of writing.

**Comment by JSJosh** [comment]
Yeah, I took that there and exported it into my openloco folder, I guess I should just delete the OpenLoco folder and install that, eh? 😅

**Comment by AaronVanGeffen** [comment]
In this case, the difference is mainly/only the `openloco.dll` file. You just replace that and leave the rest.

**Comment by JSJosh** [comment]
Ah, that did it, thank you!

![image](https://user-images.githubusercontent.com/34352316/95624540-6947ba00-0a4d-11eb-8392-bcfb1e94fdd8.png)
