### ISSUE TITLE
MSVCP140.dll file not found - Game will not launch

### ISSUE THREAD

**Issue by Derpercoaster** [OpenLoco/OpenLoco#667]
OS: Windows 10
Version: 20.07
Build: I do not know

Issue: I recently got a new computer, and downloaded the OpenLoco files (I also installed the original game disc files). However, when attempting to launch the game, the game refused to launch and gave this error message: 

"The code execution cannot proceed because MSVCP140.dll was not found. Reinstalling the program may fix this problem."

I already reinstalled the program, and it made no difference.

Steps to reproduce:
I do not know how to/if this can be reproduced reliably, but all I did was download OpenLoco, install the game disc, and attempt to launch the game, with no results other than the aforementioned error.

Reproducible: No

**Comment by duncanspumpkin** [comment]
You'll need to install the VC++ runtimes. https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads you'll need the x86 vc redistributable package. Normally most people have this installed from other programs they install so that is why it hasn't been installed yet on your new computer.

**Comment by Derpercoaster** [comment]
I know this is closed, but would this be considered a bug? The files that are needed are not supposed to be provided with OpenLoco, so I am unsure, and just want clarification.

**Comment by AaronVanGeffen** [comment]
No, this is not a bug. As has been mentioned, the VC++ runtime needs to be installed separately. This is not something we can or should ship with OpenLoco.
