### ISSUE TITLE
Will not build for Pi4/buster

### ISSUE THREAD

**Issue by Exarkuniv** [OpenLoco/OpenLoco#677]
-->
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian

im trying to build this on my Pi4 and i get this error when i try cmake 
im still learning what to add where to get cmake to do different things. so im lost here

-- Check for working CXX compiler: /usr/bin/c++ -- broken
CMake Error at /usr/local/share/cmake-3.15/Modules/CMakeTestCXXCompiler.cmake:53 (message):
  The C++ compiler

    "/usr/bin/c++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/pi/OpenLoco/build/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/make cmTC_b7c1a/fast && /usr/bin/make -f CMakeFiles/cmTC_b7c1a.dir/build.make CMakeFiles/cmTC_b7c1a.dir/build
    make[1]: Entering directory '/home/pi/OpenLoco/build/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_b7c1a.dir/testCXXCompiler.cxx.o
    /usr/bin/c++    -m32    -o CMakeFiles/cmTC_b7c1a.dir/testCXXCompiler.cxx.o -c /home/pi/OpenLoco/build/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    c++: error: unrecognized command line option ‘-m32’; did you mean ‘-mbe32’?
    make[1]: *** [CMakeFiles/cmTC_b7c1a.dir/build.make:66: CMakeFiles/cmTC_b7c1a.dir/testCXXCompiler.cxx.o] Error 1
    make[1]: Leaving directory '/home/pi/OpenLoco/build/CMakeFiles/CMakeTmp'
    make: *** [Makefile:121: cmTC_b7c1a/fast] Error 2

**Steps to reproduce:**
1. follow the steps in the read me
2.

**Is the issue reproducible in Locomotion (vanilla)?**
No idea

**Comment by duncanspumpkin** [comment]
Pi4 is not x86 and therefore will not be compatible with openloco at this time.

**Comment by Exarkuniv** [comment]
got it, thanks
