### ISSUE TITLE
Saving does not work when path contains a period

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenLoco/OpenLoco#715]
**OS:**  Arch Linux
**Version:**  20.10+
**Commit/Build:** 57e4018671bdc4605ab8756046fb583b3545ea5d

On Linux, the config path (user dir) has a `.` in it. However, the game assumes the first occurrence of a `.` to be a file extension of some sort, and overrides it with `.SV5`. This means that, when I try to save, it ends up saving to `/home/aaron/.SV5` instead of `/home/aaron/.config/OpenLoco/save/whatever.SV5`.

This problem happens in vanilla routines related to saving, so more implementation is required to solve it.

Loading works fine, which is probably how this went unnoticed during initial testing.

**Comment by IntelOrca** [comment]
Ah, it did cause problems in the loading window, but I fixed it by appending a slash there and then rather than on the global path field.

**Comment by AaronVanGeffen** [comment]
Did some more investigating, and it appears the issue is different from what I suspected:

```diff
diff --git a/src/OpenLoco/Windows/PromptBrowseWindow.cpp b/src/OpenLoco/Windows/PromptBrowseWindow.cpp
index c1b7b2ba..46814d39 100644
--- a/src/OpenLoco/Windows/PromptBrowseWindow.cpp
+++ b/src/OpenLoco/Windows/PromptBrowseWindow.cpp
@@ -857,9 +857,13 @@ namespace OpenLoco::Ui::PromptBrowse
             // Create full path to target file.
             fs::path path = fs::path(&_directory[0]) / std::string(&_text_input_buffer[0]);
 
+            printf("1 > %s\n", path.c_str());
+
             // Append extension to filename.
             path += getExtensionFromFileType(_fileType);
 
+            printf("2 > %s\n", path.c_str());
+
             // Does the file already exist?
             if (fs::exists(path))
             {
@@ -885,6 +889,8 @@ namespace OpenLoco::Ui::PromptBrowse
             // Copy directory and filename to buffer.
             strncpy(&_directory[0], path.u8string().c_str(), std::size(_directory));
 
+            printf("3 > %s\n", _directory);
+
             // Close browse window to continue saving.
             WindowManager::close(self);
         }
```

Curiously, the output is as expected:
```
1 > /home/aaron/.config/OpenLoco/save/Boulder Breakers 9
2 > /home/aaron/.config/OpenLoco/save/Boulder Breakers 9.SV5
3 > /home/aaron/.config/OpenLoco/save/Boulder Breakers 9.SV5
```

However, the file ends up being saved as `/home/aaron/.SV5`. The next time the prompt window is opened, it is browsing `/home/aaron/.SV5/` instead of the save dir as well.

**Comment by AaronVanGeffen** [comment]
Narrowing this down a bit further: 9f790371 is fine, but 28a0f2c9 is not.

**Comment by AaronVanGeffen** [comment]
Some debugging / steps to reproduce on my end.

#### 1. Load a save
```
PromptBrowse::open: path is '/home/aaron/.config/OpenLoco/save/'
getDirectory path does not have extension
getDirectory: path1 is '/home/aaron/.config/OpenLoco/save/'
getBasename 1: '/home/aaron/.config/OpenLoco/save/'
getBasename 2: ''
tick prematurely ended
```

So far so good.

#### 2. Save the game again immediately
```
PromptBrowse::open: path is '/home/aaron/.config/OpenLoco/save/North America (West) 1955 Aaron 2.SV5'
getDirectory: path has extension
getDirectory: Dir is '/home/aaron/.config/OpenLoco/save/'
getBasename 1: '/home/aaron/.config/OpenLoco/save/North America (West) 1955 Aaron 2.SV5'
getBasename 2: 'North America (West) 1955 Aaron 2'
```

Looks like getBasename is may not be dealing well with the given path.

#### 3. Try loading again
```
PromptBrowse::open: path is '/home/aaron/.SV5'
getDirectory path does not have extension
getDirectory: path2 is '/home/aaron/.SV5'
getBasename 1: '/home/aaron/.SV5'
getBasename 2: '.SV5'
```

All is fubar now.

**Comment by AaronVanGeffen** [comment]
Adding the trailing slash to `saveDirectory` did not make a difference. The bug does not present itself when I use the original paths instead:
```diff
-       auto saveDirectory = getPathNoWarning(path_id::save) / "";
-       setDirectory(_path_saves_single_player, saveDirectory);
-       setDirectory(_path_saves_two_player, saveDirectory);
+       setDirectory(_path_saves_single_player, basePath / "Single Player Saved Games/");
+       setDirectory(_path_saves_two_player, basePath / "Two Player Saved Games/");
```

This leads me to believe that the period in `.config` may be responsible, somehow.

**Comment by AaronVanGeffen** [comment]
I think it's mucking it up around 0x00446ED2 (in sub_446E87)

**Comment by AaronVanGeffen** [comment]
I think I have narrowed the issue down to sub_4454BE, specifically around loc_44552F. Here, the input save path is read until the first occurrence of `.`, after which `.SV5` is appended.

Should be solved by implementing sub_4454BE, at least partially.

**Comment by AaronVanGeffen** [comment]
> I think I have narrowed the issue down to sub_4454BE, specifically around loc_44552F. Here, the input save path is read until the first occurrence of `.`, after which `.SV5` is appended.
> 
> Should be solved by implementing sub_4454BE, at least partially.

**Comment by IntelOrca** [comment]
Fix by more implementation is a productive resolution.

**Comment by AaronVanGeffen** [comment]
Unfortunately, this pattern is present in several places, not just sub_4454BE. Look for cross-references of unk_112CE03 (offset savePath - 1). At least we know what to look for now…
