### ISSUE TITLE
Airport Catchment Area 

### ISSUE THREAD

**Issue by mackbookpro1** [OpenLoco/OpenLoco#721]
v20.10 - Build ee516cf

Whenever an airport is placed, a few seconds later the catchment area will change and is no longer centered with the airport. This confuses the AI and prevents them from using airports efficiently, and requires each airport be placed according to the bugged catchment area.

![airport_catchment](https://user-images.githubusercontent.com/77592231/104858181-882ad780-58eb-11eb-9c9e-a054ecb3ebd3.png)

**Comment by AaronVanGeffen** [comment]
Possibly a regression of #90?
