### ISSUE TITLE
Tick permanently ended

### ISSUE THREAD

**Issue by ror30394** [OpenLoco/OpenLoco#723]
"Tick Permanently Ended" crash error

**Comment by AaronVanGeffen** [comment]
Please fill out the issue template. What version of the game were you using? How can we reproduce the issue? (What were you doing when the issue occurred?) Without this information, we cannot help you.

**Comment by ror30394** [comment]
I was using 20.10, now I changed to 20.1-46-Win32.

**Comment by AaronVanGeffen** [comment]
We released v21.02 today. If the problem persists on that version, please file a new issue with detailed steps to reproduce. Thanks.
