### ISSUE TITLE
Waypoints not visible on viewport when vehicle route tab is active

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenLoco/OpenLoco#739]
**Version information:**
 - Platform: Linux
 - Version: 20.10+
 - Build/commit: 8f3edd00068be4b570457d79a8c26ecf7510d417

**Describe the bug**
Waypoints are not visible on the viewport when the route tab (vehicle window) is active.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a vehicle window (one with several waypoints)
2. Click the route tab
3. Double-click one of the waypoints to centre viewport
4. Note how there _isn't_ a corresponding circled number for it in the viewport
5. Delete one of the other waypoints
6. Note how the waypoints _are_ showing up now.

**Expected behaviour**
The waypoints are displayed in the viewport immediately.

**Comment by duncanspumpkin** [comment]
Fixed in the orders pr

**Comment by AaronVanGeffen** [comment]
Nice! What was the issue?

**Comment by duncanspumpkin** [comment]
The tool set function returns the inverse of what you would expect. I switched it around to be the correct way. The vehicle window was the only window that used the tool set return value.
