### ISSUE TITLE
Flickering effect under the bridge since release 20.05

### ISSUE THREAD

**Issue by petergaal** [OpenLoco/OpenLoco#744]
- Platform: Windows 10
 - Version: 20.07 and later, including recent master versions

Flickering effect under the bridge

Not the black areas - that is present also in the original game (maybe that should be fixed as well later). The flickering light-brown areas. This bug is not visible in version 19.03 but it's visible in 20.07, 20.10 and recent master versions.
**Update: It seems 20.03 is fine and 20.05 has this bug**

Steps to reproduce the behaviour:
1. Load the included savegame.
2. Watch the screen and see the bug after the crash (in the next few seconds). Sometimes it's happening more, sometimes less. Visible in the video which I will include as well.

Attached save game:
[Water.explosions.test.2b.SV5.zip](https://github.com/OpenLoco/OpenLoco/files/5953810/Water.explosions.test.2b.SV5.zip)

Video recorded in 19.03 without that bug (only the original bug with black areas under the bridge which is also in the original game):
[openloco-19.03.zip](https://github.com/OpenLoco/OpenLoco/files/5953820/openloco-19.03.zip)

Video recorded in 20.07 with a flickering effect under the bridge:
[openloco-20.07.zip](https://github.com/OpenLoco/OpenLoco/files/5953821/openloco-20.07.zip)

**Comment by petergaal** [comment]
I noticed there are more releases (I didn't have all of them) so I tested them. It seems 20.03 is still without that bug and the bug is visible in 20.05.

**Comment by AaronVanGeffen** [comment]
@marijnvdwerf Possibly something to do with the viewport rendering routines?

**Comment by marijnvdwerf** [comment]
Honestly I don't remember. I'd expect Z-fighting to only appear when we reimplement the sprite sorting though...

@petergaal Thanks for taking the effort of making those clips, and testing various builds

**Comment by petergaal** [comment]
https://github.com/OpenLoco/OpenLoco/commit/5c2d19068ed1622cf33e7facae4ac6d6195cd571 - this seems to be a commit where the error was introduced.

5c2d19068ed1622cf33e7facae4ac6d6195cd571 - broken
a340b239836d247d6a644dd747aab1669d952146 - good
