### ISSUE TITLE
Feature request: add "Quit OpenLoco" menu item to the main menu

### ISSUE THREAD

**Issue by jgottula** [OpenLoco/OpenLoco#77]
Just like vanilla RCT2, vanilla Locomotion only gives you a single "Quit Game" main menu item when you're in a scenario; and this menu item merely kicks you back to the game's title screen. So to actually completely quit the game, you have to do two actions: "Quit Game" in the main menu, and then "Exit Game" from the title screen. (I always thought that "quit" and "exit" were synonyms in computer UI design... I guess Chris doesn't share that point of view.)

OpenLoco should implement an additional main menu item to quit the game entirely, as was done in OpenRCT2.

**Comment by Jump-Suit** [comment]
So, under the 'Quit Game' we should also add 'Exit Game' below, well if that be the case. Please also rename 'quit Game' to : 'Quit Scenario'. For Consistency.

**Comment by seifer7** [comment]
I'm working on this, but I don't think the **Scenario Editor toolbar** has been implemented yet so I can't change it.

In a normal game:
- Changed menu item "Quit Game" to "Quit to menu" 
- Added an additional item "Exit OpenLocomotion"

This is the same as what is present in OpenRCT2.

Should I add a pull request for this, or wait until the other toolbar is done?

**Comment by AaronVanGeffen** [comment]
The scenario editor toolbar is not that different from the top toolbar — it's mainly missing options. I'll happily implement it some time this week, taking your changes to the main toolbar into account.

If you do implement this feature request, please note that quitting the game is a game command.

**Comment by seifer7** [comment]
I did see that game command and I am using it.

What do I do about the other languages where I've changed "Quit Game" to "Quit to menu" ?
At the moment I changed the existing string, should I create a new string instead and only enter it into the English language file?

**Comment by AaronVanGeffen** [comment]
> What do I do about the other languages where I've changed "Quit Game" to "Quit to menu" ?

You can leave them be, for now. I think I'll add a note to them to say the string needs reviewing, but I'm not sure how yet.

>  At the moment I changed the existing string, should I create a new string instead and only enter it into the English language file?

It's fine to change the string, I think — the language's equivalent of "Quit game" probably still makes more sense than having an English "Quit to menu" all of a sudden. You will need a new string for 'Exit OpenLoco' though, of course. It's fine to just add that to `en-GB.yml` only — other languages use this as a fallback.

**Comment by seifer7** [comment]
Perhaps we could just add `// TODO: requires translation` on the language file on strings that have been changed in English but not in other languages. 

We could write a PERL script or something to find missing strings in non-english languages and strings that have that 'requires translation' comment on them.

**Comment by AaronVanGeffen** [comment]
Rather than leaving such notes in the English language file, I would prefer to add them to the files for the languages in question. Just a note above the string that has been changed, in the same vein you describe, e.g. `// TODO: requires updating. English now reads: '...'`

Ideally, we would switch to a separate Localisation repository in a manner similar to [how OpenRCT2 does this](https://github.com/OpenRCT2/Localisation/). This would allow us to create issues for all strings that require updating. However, we do not have a team of active translators yet, so I think it's fine to leave comments in the mean time.
