### ISSUE TITLE
Crash when opening large windows

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenLoco/OpenLoco#788]
**Version information:**
 - Platform: Windows 10
 - Version: 21.02
 - Build/commit: f5f75f8

**Describe the bug**
The game crashes  at  L862 WindowManager.cpp `origin.x = std::clamp<decltype(origin.x)>(origin.x, 0, Ui::width() - size.width);` due to the window being larger than the ui width. There should be additional protection from reaching this point to ensure this does not happen at L1008.

**To Reproduce**
Steps to reproduce the behaviour:
1. Set ui resolution to something low suggest 640 x 480
2. Open Map window (but I suspect a few resizable windows will cause this)
3. Make the map window larger than the ui width.
4. Close the map window
5. Reopen the map window **Crashes**

**Expected behaviour**
Map window is resized to prevent the crash.

**Comment by petergaal** [comment]
We can also fix the crash by changing line 862 to this:
`        origin.x = std::clamp<decltype(origin.x)>(origin.x, 0, Ui::width() - std::min<decltype(origin.x)>(size.width, Ui::width()));`

Let me know if it's enough and I can make a pull request for it.

**Comment by duncanspumpkin** [comment]
We could do that but we should really just solve the problem higher up in the chain imho. I feel it should truncate the size rather than try open a big window not fully visible. You don't want to end up in a situation where a huge window opens and you can't see the x to close button.
