### ISSUE TITLE
Waypoints broken

### ISSUE THREAD

**Issue by senner007** [OpenLoco/OpenLoco#798]
[**Version]([url](url)) information:**
 - Platform: [e.g. Windows 10]
 - Version: 21.02

**Describe the bug**
Trains can't follow route through waypoints.  

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Savegame
2. See the train called Memphis Lakeside Livestock

**Expected behaviour**
Should follow waypoints

[NorthAmerica4.zip](https://github.com/OpenLoco/OpenLoco/files/6052502/NorthAmerica4.zip)

**Comment by AaronVanGeffen** [comment]
Thanks for filing an issue. This has been reported on Discord a few times as well. Happily, #797 is addressing this. :)

**Comment by senner007** [comment]
Here is a screenshot from another game

![Screenshot (6)](https://user-images.githubusercontent.com/2807139/109385971-d0c8ae00-78f7-11eb-9698-97a04636dbae.png)

**Comment by senner007** [comment]
[WaypointTest.zip](https://github.com/OpenLoco/OpenLoco/files/6056735/WaypointTest.zip)

Here is the save for the screenshot above. 
As you can see, the train should continue clockwise but decides to turn around at Breaker's Bridge.
If the save is opened in vanilla, it will work if the waypoints are removed and then added back again.

Windows 10
Version: 21.02
PR: #797

**Comment by AaronVanGeffen** [comment]
Fixed by the latest commit in #797.
