### ISSUE TITLE
Fast forward buttons don't always work

### ISSUE THREAD

**Issue by senner007** [OpenLoco/OpenLoco#799]
**Version information:**
 - Platform: [e.g. Windows 10]
 - Version: 21.02

**Comment by AaronVanGeffen** [comment]
Could you give a bit more information? I haven't been able to reproduce this myself.

**Comment by senner007** [comment]
Can't really say more than that. Sometimes it just doesn't work

**Comment by senner007** [comment]
...Meaning nothing happens when clicked

**Comment by AaronVanGeffen** [comment]
Any particular windows open when you do? Anything that could help us reproduce the issue it's potentially useful information.

**Comment by AaronVanGeffen** [comment]
If this was happening during construction, I think this will have been fixed by #795. It doesn't just affect the paused state, but game speed as well. That would also explain why I can't reproduce it.
