### ISSUE TITLE
Game crashes when destroyed vehicles are removed before the crash event window popup disappears.

### ISSUE THREAD

**Issue by Jeanfeels** [OpenLoco/OpenLoco#854]
**Version information:**
 - Platform: Windows 10
 - Version: 21.03-30
 - Build/commit: e6de736

**Describe the bug**
After a vehicle crashes and is destroyed, a brief event window pops up showing the vehicle involved. Removing the vehicle - by hitting the stop flag in that vehicle's settings - causes the game to crash if the event window is still following that vehicle, with a very brief visual glitch present sometimes where the viewport goes partially black as the game freezes for a split second, then crashes. I am all but certain this was not an original Locomotion bug.

**To Reproduce**
Steps to reproduce the behaviour:
1. Set up a situation in which a vehicle will crash.
2. Once the vehicle crashes, a viewport window will pop up - "Vehicle x has crashed!"
3. Before this popup has disappeared, hit the stop flag in the crashed vehicle's window to delete it.
4. Observe game crashes silently to desktop.

**Expected behaviour**
This should not cause a crash.

**Screenshots**
I'll do ya one better: [Here's a video of this crash in action.](https://www.youtube.com/watch?v=cKTsoaMLdqY)

**Additional context**
I have noticed in hindsight other mysterious behaviour and crashes that may be related to the viewport window event popup and will attempt to test this out. One angle in particular I will test and report back on is whether I can replicate this crash on a different event that follows a vehicle - the "First delivery of <x> arrives in <town/industry>!" viewport.

**Comment by Jeanfeels** [comment]
Just confirming that both the "first delivery to x" and "new speed record" popups don't cause a crash when deleting the vehicle they are following, just a minor and benign visual glitch in the viewport. So it's likely something more specific is causing this.

**Comment by Derpercoaster** [comment]
I've experienced this too. I think the game crash occurs because when you delete something (or when an industry closes, among other things) and thus vanishes from the game map, there's nothing for the game to display in the pop up window. In other words, the game is trying to display something that no longer exists, causing it to pull up "null" values, which it isn't designed to handle.

**Comment by Jeanfeels** [comment]
Confirming this bug remains present in v21.10 and thus is still relevant for future investigation. Dump attached:
[cf69e429-8306-43f8-917c-064e15cebb4c(OpenLoco, v21.10 (3bec790 on master)).zip](https://github.com/OpenLoco/OpenLoco/files/7574160/cf69e429-8306-43f8-917c-064e15cebb4c.OpenLoco.v21.10.3bec790.on.master.zip)

**Comment by LeftofZen** [comment]
Just noticed this issue, this is a duplicate and the issue was fixed in #1340
