### ISSUE TITLE
Allow filtering the vehicle list window

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenLoco/OpenLoco#856]
I'd like us to introduce an option to filter the vehicle list window by more than just vehicle type. Currently, you can switch between vehicle types using tabs:
![Screenshot (3)](https://user-images.githubusercontent.com/604665/112728943-f4e4d280-8f29-11eb-9c4d-dd8186557729.png)

My suggestion is to add two dropdowns at the bottom: one to choose between {All, Stopping at station, Transporting cargo}, and the second either disabled, or showing stations or cargo types as appropriate. This should make managing vehicles much easier.

**Comment by TrevorCash** [comment]
I'd like to add-on to this:  The ability to select multiple vehicles on the list might be nice (maybe a checkbox to the left of each train? as well as highlighting multiple).  And then on the bottom of the window there could be region where there are buttons that do actions on the vehicles you have selected. for example deleting, de-railing, stopping, setting route, etc.  Any actions that could be applied to multiple trains.

**Comment by AaronVanGeffen** [comment]
That sounds useful, but like an entirely different feature. Could you file a separate issue for your request?

**Comment by TrevorCash** [comment]
#1002

**Comment by LeeSpork** [comment]
Noting for posterity that the ability to filter by stations was implemented, but later removed from this window in favour of #3080 by #3081. (The ability to filter by cargo still remains).
