### ISSUE TITLE
Change save location

### ISSUE THREAD

**Issue by GustavGoblin** [OpenLoco/OpenLoco#857]
Let the user change the default save/load location. All of my saves are located in my main Locomotion folder, and I would like to keep using this folder instead of having multiple save locations or moving all my saves.

**Comment by AaronVanGeffen** [comment]
We want to discourage the use of the original game directory, which is read-only in many cases. But I think we could relatively easily let the game remember the last directory you used. That might help? :slightly_smiling_face:

**Comment by GustavGoblin** [comment]
That's fine with me. If I would have to navigate to my main directory once and never again, that would still save me a lot of time.

**Comment by petergaal** [comment]
@GustavGoblin Can you give me more information about your original problem with national characters in file path? I would like to know your Windows version and your regional settings. We would like to fix this problem properly so it will work on Windows which are not English or Western European.

**Comment by GustavGoblin** [comment]
The problem is not with any characters in the directory. I just want to be able to access my old saves without having to navigate to my old folder every time.

**Comment by petergaal** [comment]
@GustavGoblin All right, no problem. We will look at it.

**Comment by petergaal** [comment]
This is now implemented and available in master branch.

**Comment by the-lne** [comment]
Where is the path stored?  I put in the wrong path and things obviously didn't work out lol. But now, fixing this seems to be quite the issue. I've completely deleted the repository, re-downloaded it, rebuilt it, and the program automatically searches for the incorrect path. Is there a config file stored somewhere on my system?
