### ISSUE TITLE
Music volume is not saved on exit

### ISSUE THREAD

**Issue by senner007** [OpenLoco/OpenLoco#859]
**Version information:**
 - Platform: Windows 10
 - Version: 21.03

**Describe the bug**
Music volume is not saved on exit

**To Reproduce**
1. Open game
2. Set Music volume slide to 50%
3. Exit game
4. Open game and music volume is at 100%

**Expected behaviour**
Volume should be saved

**Comment by senner007** [comment]
I would like to do a pr myself. I normally write ts and C# in vscode, so I just have to set up the VS with dependencies and compile it.

**Comment by AaronVanGeffen** [comment]
Duplicate of #729

**Comment by senner007** [comment]
Ahh, should have checked previous issues first. Thanks
