### ISSUE TITLE
'Load save' dialog lists files it shouldn't

### ISSUE THREAD

**Issue by Gymnasiast** [OpenLoco/OpenLoco#89]
Ubuntu 17.10, AMD64
Commit 0fa0aa545ed395c6c2a22102b8d1c84d12d32f8d

It lists 1.DAT (which is not a save) and Britain 1.SV5.BAK (which is a back-up save).

Locomotion:
![afbeelding](https://user-images.githubusercontent.com/1478678/35672241-30c64724-073e-11e8-8fed-f32e15fcb28c.png)

OpenLoco:
![schermafdruk van 2018-02-01 11-14-27](https://user-images.githubusercontent.com/1478678/35673188-170ddace-0741-11e8-9b34-510d66c72f8c.png)

**Comment by marijnvdwerf** [comment]
Has to do with the hooking in `fn_FindFirstFile`. I loop through parent directory contents and discard the `*.SV5` part.

**Comment by AaronVanGeffen** [comment]
To add to this: folders aren't processed as folders, either. (Works on Windows, not on Linux.)

**Comment by AaronVanGeffen** [comment]
This has since been resolved.
