### ISSUE TITLE
Unlimited Money While in Sandbox Mode

### ISSUE THREAD

**Issue by SteamsDev** [OpenLoco/OpenLoco#892]
I was excited to see the sandbox/debugging feature in OpenLoco but I feel like it's missing a very important aspect: The ability to have unlimited money in the game. I don't know if this feature is implemented or will be implemented, but I would personally appreciate it if the ability to get as much money as you want was a feature of the sandbox/debugging mode.

One way I find this working is the following: While in sandbox/debugging mode, instead of taking out a loan when increasing it, the moan amount remains unchanged and straight-up gives you the money instead. This makes it possible to get unlimited money through the in-game finance feature.

Alternatively, you could also just have an extra set of buttons next to the player's money counter, which said player can use to obtain money.

Either way should be feasible. Let me know if there are any issues.

Thanks for doing this!

**Comment by duncanspumpkin** [comment]
We will likely add a cheats window where you can give yourself money.
