### ISSUE TITLE
Windows Xp Error

### ISSUE THREAD

**Issue by dimaspaf14** [OpenLoco/OpenLoco#894]
**Version information:**
 - Platform: Windows Xp Sp3
 - Version: 21.03
 - Build/commit: idk what this..

**Describe the bug**
After extracting the zip file, then im double click the openloco.exe, then it show me cmd with nothin and a window that say "The procedure entry point ReleaseSRWLockExclusive could not be located in the dynamic link library KERNEL32.dll."

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'extracted file'
2. Double Click on 'openloco.exe'

**Expected behaviour**
I was expecting that the game run correctly

**Screenshots**
![IMG_20210405_145208](https://user-images.githubusercontent.com/71385492/113553922-aff42680-9622-11eb-9b06-2fbd52ab2c1b.jpg)

**Additional context**
I dont know what happen but the other game like openttd jgrpp & openrct2 is same like this, error

**Comment by AaronVanGeffen** [comment]
Sorry, we do not support Windows XP. It is too much of a burden on development to keep Windows XP into account.

**Comment by dimaspaf14** [comment]
But this game was maked for xp :(

**Comment by AaronVanGeffen** [comment]
Well, ours is not. We are reimplementing the game entirely in C++. What platforms the original game supported has no relevance to our code.

Windows XP was released in 2001. Like OpenRCT2, someone might come and make a limited build that does support Windows XP eventually. We are a limited number of devs, though, and personally I would rather focus on modern platforms.

**Comment by dimaspaf14** [comment]
Oh, ok
Thanks for answering the bugs :)
(can i close now or later?)

**Comment by dimaspaf14** [comment]
Hey @AaronVanGeffen , i meesing up with openloco v20.10, i use vista2xp, it works but the newer ver. Isnt work anymore, kinda sad though

**Comment by luk3ZPL** [comment]
> Hey @AaronVanGeffen , i meesing up with openloco v20.10, i use vista2xp, it works but the newer ver. Isnt work anymore, kinda sad though

You may try XP x64 + SP2 + (vista2xp if needed) https://en.wikipedia.org/wiki/Windows_XP_Professional_x64_Edition

**Comment by dimaspaf14** [comment]
> > Hey @AaronVanGeffen , i meesing up with openloco v20.10, i use vista2xp, it works but the newer ver. Isnt work anymore, kinda sad though
> 
> You may try XP x64 + SP2 + (vista2xp if needed on virtual machine) https://en.wikipedia.org/wiki/Windows_XP_Professional_x64_Edition But I doubt it will work.

Virtual machine are bad for me, weak gpu..

**Comment by duncanspumpkin** [comment]
> > > Hey @AaronVanGeffen , i meesing up with openloco v20.10, i use vista2xp, it works but the newer ver. Isnt work anymore, kinda sad though
> > 
> > 
> > You may try XP x64 + SP2 + (vista2xp if needed on virtual machine) https://en.wikipedia.org/wiki/Windows_XP_Professional_x64_Edition But I doubt it will work.
> 
> Virtual machine are bad for me, weak gpu..

Locomotion doesn't use the GPU it is a purely software game so it's all on the CPU.
