### ISSUE TITLE
Scenario high scores not saving with non-ASCII chars in path

### ISSUE THREAD

**Issue by anon569** [OpenLoco/OpenLoco#913]
**Version information:**
 - Platform: Windows 10
 - Version: 21.04
 - Build/commit: 8409067

**Describe the bug**
My settings are reverting back to the default settings after restarting the game. Only loco path, resolution and autosave are preserved.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have a username with UTF-8 characters, like éáűúőí
2. Change some in-game settings
3. Restart the game

**Expected behaviour**
All settings are properly saved after restarting the game. 

**Screenshots**
<img width="674" alt="BUG" src="https://user-images.githubusercontent.com/42820802/114287375-9c075500-9a66-11eb-844f-b6b7afd77fbb.png">
(I have an á in my username)

**Additional context**
According to IntelOrca "it probably is due to files like game.cfg still being written by original game code which isn't UTF-8 compatible."

**Comment by LeftofZen** [comment]
@anon569 can you confirm this still happens on 22.02? there have been a few changes since this was reported

**Comment by anon569** [comment]
> @anon569 can you confirm this still happens on 22.02? there have been a few changes since this was reported
High scores still doesn't get saved but otherwise everything works as it should.

**Comment by duncanspumpkin** [comment]
I think high scores is the only bit of code still using vanilla for saving unfortunately.

**Comment by AaronVanGeffen** [comment]
I believe this has been addressed by #1728 and #1744. @anon569, could you confirm?
