### ISSUE TITLE
G1 element doesn't match expected value

### ISSUE THREAD

**Issue by yadudemyboi** [OpenLoco/OpenLoco#937]
**Version information:**
 - Platform: Windows 10
 - Version: 21.04.1
 - Build/commit: 753b60e

**Describe the bug**
i cannot open openloco while allowing me to play, all it says in the console is: OpenLoco, v21.04.1 (753b60e)
G1 element count doesn't match expected value: Expected 4122; Got 3896
Got Steam G1.DAT variant, will fix elements automatically. and it does not fix elements automatically which i assume is supposed to be the game its self because there is no visible game all it does is load the title music

**To Reproduce**
1. Click on 'Chris Sawyers Locomotion' on the desktop fast twice (i have replaced Loco.exe with openloco.exe but renamed)
2. see that there is no locomotion and see the error

**Expected behaviour**
i expected it to open and play after adding new station mods

**Additional context**
i had installed new trams and tram stations how ever i cannot play the game after installing said mods, i only get the console and hear the music i cannot do anything since i have waited a while now and it still has not opened the actual game and its still only the music

**Comment by duncanspumpkin** [comment]
There is a known issue with the steam version of Locomotion atm. You can switch to version 19.03 whilst we work on fixing it as I understand that that version does work with steam.
