### ISSUE TITLE
add station mods with out needing to edit with locotool

### ISSUE THREAD

**Issue by yadudemyboi** [OpenLoco/OpenLoco#938]
**Describe the solution you'd like**
i would like if there was a window to add station mods without needing to read a tutorial from forever ago and it actually adds them

**Describe alternatives you've considered**
an alternate feature could be a type of drag and drop system and that automatically adds the station or other vehicle path side object

**Additional context**
i tried to install station mods and it went wrong now i cant open openloco

**Comment by duncanspumpkin** [comment]
What are station mods in this context you have not made it clear as to what they are.

**Comment by yadudemyboi** [comment]
> What are station mods in this context you have not made it clear as to what they are.

stations that would normally need to be added via editing the .dat with locotool with the respected type of road or track, like a new standard gauge station that is for freight while not allowing passengers, a new station like the new coalmine and station mod from the forums.
